### ISSUE TITLE
RuntimeException: Failed to call observer method

### ISSUE THREAD

**Issue by savked** [GetStream/stream-chat-android#105]
2019-10-07 19:33:30.507 10951-10951/de.tourlina.Tourlina.staging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.tourlina.Tourlina.staging, PID: 10951
    java.lang.RuntimeException: Unable to resume activity {de.tourlina.Tourlina.staging/de.tourlina.tourlina.MainActivity}: java.lang.RuntimeException: Failed to call observer method
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.lifecycle.ProcessLifecycleOwner.activityResumed(ProcessLifecycleOwner.java:118)
        at androidx.lifecycle.ProcessLifecycleOwner$2.onResume(ProcessLifecycleOwner.java:85)
        at androidx.lifecycle.ReportFragment.dispatchResume(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment.onResume(ReportFragment.java:89)
        at android.app.Fragment.performResume(Fragment.java:2580)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
        at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3014)
        at android.app.FragmentController.dispatchResume(FragmentController.java:206)
        at android.app.Activity.performResume(Activity.java:7961)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacksAndMessages(java.lang.Object)' on a null object reference
        at com.getstream.sdk.chat.rest.WebSocketService.disconnect(WebSocketService.java:168)
        at com.getstream.sdk.chat.rest.core.Client.disconnect(Client.java:991)
        at com.getstream.sdk.chat.rest.core.Client.reconnect(Client.java:1003)
        at com.getstream.sdk.chat.StreamChat$2$1.resume(StreamChat.java:118)
        at com.getstream.sdk.chat.StreamLifecycleObserver.onResume(StreamLifecycleObserver.java:18)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361) 
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131) 
        at androidx.lifecycle.ProcessLifecycleOwner.activityResumed(ProcessLifecycleOwner.java:118) 
        at androidx.lifecycle.ProcessLifecycleOwner$2.onResume(ProcessLifecycleOwner.java:85) 
        at androidx.lifecycle.ReportFragment.dispatchResume(ReportFragment.java:68) 
        at androidx.lifecycle.ReportFragment.onResume(ReportFragment.java:89) 
        at android.app.Fragment.performResume(Fragment.java:2580) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346) 
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642) 
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052) 
        at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3014) 
        at android.app.FragmentController.dispatchResume(FragmentController.java:206) 
        at android.app.Activity.performResume(Activity.java:7961) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Chikrix** [comment]
Same here, also getting this crash

**Comment by tbarbugli** [comment]
can you share some info on how you get to this error?

**Comment by savked** [comment]
For me, it was usually when going to background and coming to the foreground inside the ChannelActivity but can happen in MainActivity too.

**Comment by tschellenbach** [comment]
Fixed on master
