### ISSUE TITLE
Crash when sending video.

### ISSUE THREAD

**Issue by harrunisk** [GetStream/stream-chat-android#1077]
**Describe the bug**
Crash when sending video. It doesn't happen always. But it happens frequently.

**Stack trace**  
```
    Process: io.getstream.chat.sample.debug, PID: 9012
    java.lang.IllegalStateException: Result is not successful. Check result.isSuccess before reading the data.
        at io.getstream.chat.android.client.utils.Result.data(Result.kt:20)
        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl.uploadAttachment$stream_chat_android_offline_debug(ChannelControllerImpl.kt:603)
        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl.sendMessage(ChannelControllerImpl.kt:540)
        at io.getstream.chat.android.livedata.controller.ChannelControllerImpl$sendMessage$1.invokeSuspend(Unknown Source:16)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**SDK version**
- 4.4.9
- 4.4.0

**To Reproduce**
1. Go to `channel`
2. Click on `add a file`
3. Click on `upload a photo or video`
4. Select a video 
4. Wait to see the crash

**Expected behavior**
Sent video

**Device:**
 - Emulator
 - Pixel 2 API 30

https://user-images.githubusercontent.com/31736480/102902227-c5807e80-447f-11eb-838c-700c27562c4b.mp4

**Comment by zsmb13** [comment]
This should be fixed by https://github.com/GetStream/stream-chat-android/pull/1069, which will ship in the next release.

**Comment by harrunisk** [comment]
I checked the `develop` branch, it is fixed. Thanks for your information @zsmb13 .
