### ISSUE TITLE
Error deleting channels

### ISSUE THREAD

**Issue by CrispBull** [GetStream/stream-chat-android#1127]
**Describe the bug**
When trying to delete a channel, it throws an error, the request is successful but there seems to be a response parsing error which makes it impossible for the delete channel request callback to be successful. I get the following error;

```E/LoggingTracker: logging caught exception
    io.getstream.chat.android.client.errors.ChatParsingError: custom object deserialisation error of class io.getstream.chat.android.client.models.Channel
        at io.getstream.chat.android.client.parser.adapters.CustomObjectGsonAdapter.read(CustomObjectGsonAdapter.kt:100)
        at io.getstream.chat.android.client.parser.adapters.CustomObjectGsonAdapter.read(CustomObjectGsonAdapter.kt:16)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:40)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: io.getstream.chat.android.client.errors.ChatParsingError: custom object deserialisation error of class io.getstream.chat.android.client.models.User
        at io.getstream.chat.android.client.parser.adapters.CustomObjectGsonAdapter.read(CustomObjectGsonAdapter.kt:100)
        at io.getstream.chat.android.client.parser.adapters.CustomObjectGsonAdapter.read(CustomObjectGsonAdapter.kt:16)
        at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:260)
        at com.google.gson.TypeAdapter.fromJson(TypeAdapter.java:273)
        at io.getstream.chat.android.client.parser.adapters.CustomObjectGsonAdapter.read(CustomObjectGsonAdapter.kt:86)
        at io.getstream.chat.android.client.parser.adapters.CustomObjectGsonAdapter.read(CustomObjectGsonAdapter.kt:16) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:40) 
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27) 
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243) 
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153) 
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.NullPointerException: delegateMapAdapter.read(reader) must not be null
        at io.getstream.chat.android.client.parser.MapAdapter.read(MapAdapter.kt:8)
        at io.getstream.chat.android.client.parser.MapAdapter.read(MapAdapter.kt:7)
```
This makes the enqueue callback is not successful and

**SDK version**
- 4.4.9

**To Reproduce**
Try to delete a channel and enqueue. I'm using the following method to try to delete
```kotlin
ChatClient.instance().channel(channelCid).delete().enqueue {
            ...
 }
```

**Expected behavior**
When request to delete a channel is successful, the enqueue callback task should be successful and return the right response, instead it returns the cause of the error as `io.getstream.chat.android.client.errors.ChatParsingError: custom object deserialisation error of class io.getstream.chat.android.client.models.Channel` given the error log above

**Comment by adasiewiczr** [comment]
Hello @CrispBull, thanks for reporting that issue.
#1130 PR should fix this error and it will be shipped in our next release (4.4.10).

**Comment by zsmb13** [comment]
The new version that contains this fix is 4.5.0, please try it when you can.

**Comment by CrispBull** [comment]
Awesome! Thanks

**Comment by zsmb13** [comment]
Closing this for now, let us know if you have any issues with the new version.
