### ISSUE TITLE
Offline support 2.0

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-android#114]
1. Current offline support needs a thorough round of testing before we make it default enabled instead of default disabled.

2. Push notifications should ensure that local storage is up to date:

- receive push notification
- query data and store it in the local storage
- show the push notification to the user (and it will be there when they open the app)

3. Background/foreground behaviour needs to improve:

- we always send the push notification
background:
- we close the websocket connection after 1 minute
foreground:
- if the websocket connection was closed we recover

4. Image sending

- You should be able to send a message with an image, without waiting for the image to upload

5. Data cleanup

- the offline storage should remove data that is no longer needed to preserve storage

6. Schema export

- Once we enable offline by default we should export the room schema

7. Correctly handle user changes (user.updated, not user.presence.changed)

8. Muting users or hiding channels should also be stored locally

**Comment by tschellenbach** [comment]
9. Reactions should be stored locally before sending to the server

**Comment by tschellenbach** [comment]
@tbarbugli what do you think about always sending push notifications from the API and ignoring it client-side.

**Comment by lukenowakcom** [comment]
I was thinking about creating new issue for it(maybe I should?) but I just tried to enable offlineStorage to see how it works and it immediately crashed
```
2019-11-04 17:39:30.449 9123-9332/io.ahoy.ahoy.rc E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: io.ahoy.ahoy.rc, PID: 9123
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: No enum constant com.getstream.sdk.chat.enums.MessageStatus.received
        at java.lang.Enum.valueOf(Enum.java:258)
        at com.getstream.sdk.chat.enums.MessageStatus.valueOf(MessageStatus.java:3)
        at com.getstream.sdk.chat.storage.converter.MessageStatusConverter.fromString(MessageStatusConverter.java:11)
        at com.getstream.sdk.chat.storage.ChannelsDao_Impl.getChannel(ChannelsDao_Impl.java:1043)
        at com.getstream.sdk.chat.storage.Storage$ChannelQuery.doInBackground(Storage.java:475)
        at com.getstream.sdk.chat.storage.Storage$ChannelQuery.doInBackground(Storage.java:462)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by lukenowakcom** [comment]
I was thinking about creating new issue for it(maybe I should?) but I just tried to enable offlineStorage to see how it works and it immediately crashed
```
AsyncTask #2
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: No enum constant com.getstream.sdk.chat.enums.MessageStatus.received
        at java.lang.Enum.valueOf(Enum.java:258)
        at com.getstream.sdk.chat.enums.MessageStatus.valueOf(MessageStatus.java:3)
        at com.getstream.sdk.chat.storage.converter.MessageStatusConverter.fromString(MessageStatusConverter.java:11)
        at com.getstream.sdk.chat.storage.ChannelsDao_Impl.getChannel(ChannelsDao_Impl.java:1043)
        at com.getstream.sdk.chat.storage.Storage$ChannelQuery.doInBackground(Storage.java:475)
        at com.getstream.sdk.chat.storage.Storage$ChannelQuery.doInBackground(Storage.java:462)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by adrian09h** [comment]
@lukenowakcom it seems your crash has to do with MessageStatus enum. we removed the enum already.
Please try new version of library.

**Comment by lukenowakcom** [comment]
@adrian09h Just tried **3.2.1** , same error. 
Unless the fix is one of the pre-release versions?

**Comment by adrian09h** [comment]
> @adrian09h Just tried **3.2.1** , same error.
> Unless the fix is one of the pre-release versions?

`3.2.1` is not latest version.
Please try `3.2.3-glide-logs`
