### ISSUE TITLE
[4.6.0] Notifications don't appear when app is not open

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1497]
Following crash is logged when a notification is received and app is not in foreground (not in recents as well). The notification is not shown.

```
2021-03-02 11:00:15.006 E/AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
    Process: com.appname.chat, PID: 8186
    kotlin.UninitializedPropertyAccessException: lateinit property initJob has not been initialized
        at io.getstream.chat.android.livedata.ChatDomainImpl.replayEventsForActiveChannels(ChatDomainImpl.kt:589)
        at io.getstream.chat.android.livedata.usecase.ReplayEventsForActiveChannelsImpl$invoke$1.invokeSuspend(ReplayEventsForActiveChannelsImpl.kt:29)
        at io.getstream.chat.android.livedata.usecase.ReplayEventsForActiveChannelsImpl$invoke$1.invoke(Unknown Source:10)
        at io.getstream.chat.android.client.call.CoroutineCall$execute$1.invokeSuspend(CoroutineCall.kt:25)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
        at io.getstream.chat.android.client.call.CoroutineCall.execute(CoroutineCall.kt:25)
        at io.getstream.chat.android.livedata.service.sync.PushMessageSyncHandler.performSync(PushMessageSyncHandler.kt:119)
        at io.getstream.chat.android.livedata.service.sync.PushMessageSyncHandler.onMessageReceived(PushMessageSyncHandler.kt:84)
        at com.appname.chat.startup.push.ChatPushMessageHandler.handlePushMessage(ChatPushMessageHandler.kt:20)
        at com.appname.core.integrations.firebase.PushNotificationsService.onMessageReceived(PushNotificationsService.kt:17)
        at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@21.0.1:13)
        at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@21.0.1:8)
        at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@21.0.1:3)
        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@21.0.1:3)
        at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(Unknown Source:1)
        at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.2.1:6)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by samiuelson** [comment]
Can you provide more details of the device and OS version?
Does the crash happen only / always when app's process is killed and push notification is received?

**Comment by rupinderjeet** [comment]
Yes, device is Samsung's Galaxy A50 running Android 10. Reproducible on Android Emulator Pixel 3 running Android 10.

This crash happens only if app's process is not alive.

Suppose I am chatting with someone;

- I remove app from recents, completely killing it
- Someone sends me a message
- App crashes; notification is not shown.

Android shows dialog "App has stopped."

**Comment by kplanz** [comment]
We have the same issue on a Samsung device and on a Google Pixel 3 XL.

It mainly happens when the app was killed and a notification was received. The empty "sync" notification appears, but our custom notification does not appear and these errors are shown in the logs:

```
2021-03-05 10:52:02.274 11659-11720/? E/AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
    Process: com.openwt.****.test, PID: 11659
    kotlin.UninitializedPropertyAccessException: lateinit property initJob has not been initialized
        at io.getstream.chat.android.livedata.ChatDomainImpl.replayEventsForActiveChannels(ChatDomainImpl.kt:589)
        at io.getstream.chat.android.livedata.usecase.ReplayEventsForActiveChannelsImpl$invoke$1.invokeSuspend(ReplayEventsForActiveChannelsImpl.kt:29)
        at io.getstream.chat.android.livedata.usecase.ReplayEventsForActiveChannelsImpl$invoke$1.invoke(Unknown Source:10)
        at io.getstream.chat.android.client.call.CoroutineCall$execute$1.invokeSuspend(CoroutineCall.kt:25)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
        at io.getstream.chat.android.client.call.CoroutineCall.execute(CoroutineCall.kt:25)
        at io.getstream.chat.android.livedata.service.sync.PushMessageSyncHandler.performSync(PushMessageSyncHandler.kt:119)
        at io.getstream.chat.android.livedata.service.sync.PushMessageSyncHandler.onMessageReceived(PushMessageSyncHandler.kt:84)
        at io.getstream.chat.android.livedata.service.sync.OfflineSyncFirebaseMessagingService.onMessageReceived(OfflineSyncFirebaseMessagingService.kt:16)
        at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@21.0.1:13)
        at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@21.0.1:8)
        at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@21.0.1:3)
        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@21.0.1:3)
        at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(Unknown Source:1)
        at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.2.1:6)
        at java.lang.Thread.run(Thread.java:923)
2021-03-05 10:52:02.274 11659-11720/? E/****$CustomExceptionHandler: lateinit property initJob has not been initialized
    kotlin.UninitializedPropertyAccessException: lateinit property initJob has not been initialized
        at io.getstream.chat.android.livedata.ChatDomainImpl.replayEventsForActiveChannels(ChatDomainImpl.kt:589)
        at io.getstream.chat.android.livedata.usecase.ReplayEventsForActiveChannelsImpl$invoke$1.invokeSuspend(ReplayEventsForActiveChannelsImpl.kt:29)
        at io.getstream.chat.android.livedata.usecase.ReplayEventsForActiveChannelsImpl$invoke$1.invoke(Unknown Source:10)
        at io.getstream.chat.android.client.call.CoroutineCall$execute$1.invokeSuspend(CoroutineCall.kt:25)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
        at io.getstream.chat.android.client.call.CoroutineCall.execute(CoroutineCall.kt:25)
        at io.getstream.chat.android.livedata.service.sync.PushMessageSyncHandler.performSync(PushMessageSyncHandler.kt:119)
        at io.getstream.chat.android.livedata.service.sync.PushMessageSyncHandler.onMessageReceived(PushMessageSyncHandler.kt:84)
        at io.getstream.chat.android.livedata.service.sync.OfflineSyncFirebaseMessagingService.onMessageReceived(OfflineSyncFirebaseMessagingService.kt:16)
        at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@21.0.1:13)
        at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@21.0.1:8)
        at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@21.0.1:3)
        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@21.0.1:3)
        at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(Unknown Source:1)
        at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.2.1:6)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by samiuelson** [comment]
Thanks for the bug report. We will fix it.

**Comment by JcMinarro** [comment]
Hello @kplanz @rupinderjeet 
It has been fixed and it is ready on the [last release](https://github.com/GetStream/stream-chat-android/releases/latest)
Could you check it?
