### ISSUE TITLE
String.equals on Null

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-android#156]
"Crash
NPE: String.equals on a null object reference
        at com.getstream.sdk.chat.view.MessageListView$1.getDrawableForAttachment(MessageListView.java:182)"

I've asked for a full stack trace, will update once i get it

**Comment by TwinkyMoon** [comment]
FATAL EXCEPTION: main
    Process: com.imgur.mobile.debug, PID: 28038
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.getstream.sdk.chat.view.MessageListView$1.getDrawableForAttachment(MessageListView.java:182)
        at com.getstream.sdk.chat.adapter.AttachmentViewHolder.configImageThumbBackground(AttachmentViewHolder.java:107)
        at com.getstream.sdk.chat.adapter.AttachmentViewHolder.configMediaAttach(AttachmentViewHolder.java:179)
        at com.getstream.sdk.chat.adapter.AttachmentViewHolder.configAttachment(AttachmentViewHolder.java:76)
        at com.getstream.sdk.chat.adapter.AttachmentViewHolder.bind(AttachmentViewHolder.java:58)
        at com.getstream.sdk.chat.adapter.AttachmentListItemAdapter.onBindViewHolder(AttachmentListItemAdapter.java:68)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
        at com.getstream.sdk.chat.view.AttachmentListView.onMeasure(Unknown Source:13)
        at android.view.View.measure(View.java:24938)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:722)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:373)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measureChildren(BasicMeasure.java:112)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:213)
        at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:113)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1458)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1537)
        at android.view.View.measure(View.java:24938)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9119)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1583)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:587)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:22397)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1654)
        at android.view.View.layout(View.java:22397)
        at android.view.ViewGroup.layout(ViewGroup.java:6572)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22397)

**Comment by TwinkyMoon** [comment]
the QA reports awkward message
![image](https://user-images.githubusercontent.com/11149519/66830262-be95dc00-ef5d-11e9-97f2-271fc377a9b9.png)

**Comment by adrian09h** [comment]
@TwinkyMoon  can you please show me message object of the problem?
{"hash":"..."}

**Comment by TwinkyMoon** [comment]
I'll try get it. It is replicating only for one of our QAs, just now we have a new host you know... and old channels are missed. But I'll make a build for old one and ask to provide logs for response

**Comment by TwinkyMoon** [comment]
{
    "id": "77a17133-1cf4-4a69-8e4f-c984addaaffb",
    "text": "@testuser321 sent an image",
    "html": "\u003cp\u003e@testuser321 sent an image\u003c/p\u003e\n",
    "type": "regular",
    "user": {
      "id": "107464597",
      "role": "user",
      "created_at": "2019-09-25T09:37:03.067658Z",
      "updated_at": "2019-10-17T13:15:39.696468Z",
      "last_active": "2019-10-17T13:15:39.694916Z",
      "online": false,
      "unread_count": 0,
      "name": "testuser321",
      "image": null
    },
    "attachments": [
      {
        "body": "{\"hash\":\"PL071mg\",\"ext\":\"mp4\"}",
        "mime_type": "application/vnd.imgur.layer+image"
      }
    ],

**Comment by TwinkyMoon** [comment]
now we are not having a crash, and the issue does not replicate, might be some specific steps or whats so ever
