### ISSUE TITLE
NPE/Crash: channel is null in sendStoppedTyping

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android#157]
In some case when sample app is started NPE is thrown.
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Date com.getstream.sdk.chat.model.Channel.getLastStartTypingEvent()' on a null object reference
    at com.getstream.sdk.chat.viewmodel.ChannelViewModel$Looper.sendStoppedTyping(ChannelViewModel.java:1147)
    at com.getstream.sdk.chat.viewmodel.ChannelViewModel$Looper.run(ChannelViewModel.java:1177)
```
```java
private void sendStoppedTyping() {
    if (channel.getLastStartTypingEvent() == null) {
        return;
    }
}
```

**Comment by elevenetc** [comment]
Already fixed by @adrian09h 
https://github.com/GetStream/stream-chat-android/blob/70f8a32b7bef1c7e8648dec37a8336805668733f/library/src/main/java/com/getstream/sdk/chat/viewmodel/ChannelViewModel.java#L1144
