### ISSUE TITLE
InvalidProtocolBufferException (Protocol message contained an invalid tag (zero))

### ISSUE THREAD

**Issue by beckmartin** [GetStream/stream-chat-android#1823]
**Describe the bug**
Hey stream team, some of my users are facing a crash during app start/ initialization of the stream sdk. The errors suggests that it might be revolving Androids EncryptedSharedPreferences, any idea what could cause this crash? 
Below is the log

`Caused by com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
       at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
       at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
       at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
       at io.getstream.chat.android.livedata.service.sync.EncryptedBackgroundSyncConfigStore.<init>(EncryptedBackgroundSyncConfigStore.kt:21)
       at io.getstream.chat.android.livedata.service.sync.SyncProvider$encryptedBackgroundSyncConfigStore$2.invoke(SyncProvider.kt:8)
       at io.getstream.chat.android.livedata.service.sync.SyncProvider$encryptedBackgroundSyncConfigStore$2.invoke(SyncProvider.kt:5)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at io.getstream.chat.android.livedata.service.sync.SyncProvider.getEncryptedBackgroundSyncConfigStore$stream_chat_android_offline_release(:2)
       at io.getstream.chat.android.livedata.ChatDomainImpl.storeBgSyncData(ChatDomainImpl.kt:467)
       at io.getstream.chat.android.livedata.ChatDomainImpl.access$storeBgSyncData(ChatDomainImpl.kt:99)
       at io.getstream.chat.android.livedata.ChatDomainImpl$storeBgSyncDataWhenUserConnects$1.onConnected(ChatDomainImpl.kt:456)
       at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$$special$$inlined$observable$1$lambda$1.invoke(ChatSocketServiceImpl.kt:70)
       at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$$special$$inlined$observable$1$lambda$1.invoke(ChatSocketServiceImpl.kt:23)
       at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$callListeners$$inlined$synchronized$lambda$1.run(ChatSocketServiceImpl.kt:214)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7660)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**SDK version**
- com.github.GetStream:stream-chat-android:4.7.0

App info:
  minSdkVersion = 22
  targetSdkVersion = 29
  compileSdkVersion = 28
  buildToolsVersion = '28.0.2'

**To Reproduce**
1. Open app
2. Crashes for limited number of users

**Expected behavior**
No crash, shared prefs are loaded normally.

**Device:**
 - Vendor and model: Google Pixel 4
 - Android version: 11

**Screenshots**

**Comment by zsmb13** [comment]
Hi @beckmartin! This issue was fixed in 4.8.1, and the latest version of our SDK is 4.9.1. Could you please update to the latest?

**Comment by beckmartin** [comment]
Thank you @zsmb13 for the quick response, after upgrading to the latest version I get module import errors as of below

> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.getstream.sdk.chat.ChatUI found in modules jetified-stream-chat-android-4.9.1-runtime (com.github.GetStream.stream-chat-android:stream-chat-android:4.9.1) and jetified-stream-chat-android-ui-components-4.9.1-runtime (com.github.GetStream.stream-chat-android:stream-chat-android-ui-components:4.9.1)
     Duplicate class com.getstream.sdk.chat.ChatUI$Builder found in modules jetified-stream-chat-android-4.9.1-runtime (com.github.GetStream.stream-chat-android:stream-chat-android:4.9.1) and jetified-stream-chat-android-ui-components-4.9.1-runtime (com.github.GetStream.stream-chat-android:stream-chat-android-ui-components:4.9.1)
     Duplicate class com.getstream.sdk.chat.ChatUI$Companion found in modules jetified-stream-chat-android-4.9.1-runtime (com.github.GetStream.stream-chat-android:stream-chat-android:4.9.1) and jetified-stream-chat-android-ui-components-4.9.1-runtime (com.github.GetStream.stream-chat-android:stream-chat-android-ui-components:4.9.1)

This happens for 4.8.1 as well as 4.9.1

**Comment by beckmartin** [comment]
Switched from
>     implementation 'com.github.GetStream:stream-chat-android:4.7.0'
to
>     implementation 'com.github.GetStream:stream-chat-android-ui-components:4.9.1'

However now I get 

> > Could not GET 'https://jitpack.io/com/github/GetStream/stream-chat-android-ui-components/4.9.1/stream-chat-android-ui-components-4.9.1.pom'. Received status code 401 from server: Unauthorized

even though its a public repo? Did I miss some auth settings that I have to set in the docs...?

**Comment by beckmartin** [comment]
Moved from
>     implementation 'com.github.GetStream:stream-chat-android:4.7.0'
to
>     implementation "io.getstream:stream-chat-android-ui-components:4.9.1"

After some code changes it seems to work now, will test a little more and update here afterwards

**Comment by beckmartin** [comment]
Works with latest UI-components, cheers!
