### ISSUE TITLE
Using Exoplayer v2.13.3 in app crashes AttachmentMediaActivity

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1843]
Activity `io.getstream.chat.android.ui.gallery.AttachmentMediaActivity` crashes if I use latest version of ExoPlayer. The crash reason is as following:

```
Caused by: java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Lcom/google/android/exoplayer2/trackselection/TrackSelection$Factory;)V in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in /data/app/com.appname-LLxPjrhFcnoGJGuK2dvaWg==/base.apk!classes3.dex)
        at com.getstream.sdk.chat.utils.exomedia.core.exoplayer.ExoMediaPlayer.<init>(ExoMediaPlayer.java:159)
        at com.getstream.sdk.chat.utils.exomedia.core.video.exo.ExoVideoDelegate.initExoPlayer(ExoVideoDelegate.java:274)
        at com.getstream.sdk.chat.utils.exomedia.core.video.exo.ExoVideoDelegate.setup(ExoVideoDelegate.java:270)
        at com.getstream.sdk.chat.utils.exomedia.core.video.exo.ExoVideoDelegate.<init>(ExoVideoDelegate.java:59)
        at com.getstream.sdk.chat.utils.exomedia.core.video.exo.ExoSurfaceVideoView.setup(ExoSurfaceVideoView.java:234)
        at com.getstream.sdk.chat.utils.exomedia.core.video.exo.ExoSurfaceVideoView.<init>(ExoSurfaceVideoView.java:59)
        	... 41 more
```

I noticed that `Dependencies` file in this sdk uses `2.12.1` version of ExoPlayer, so I downgraded to use this version instead. 
```
private const val EXOPLAYER_VERSION = "2.12.1"
```

Today, I saw that you guys are working on [Exomedia Cleanup](https://github.com/GetStream/stream-chat-android/pull/1841). And, declaration for `exoplayer` dependency has disappeared from stream-chat. And, @zsmb13's comment says 
> We didn't use ExoPlayer directly anywhere, we're using it via the ExoMedia wrapper

Do you think that I can use the latest version of Exoplayer now?

**Comment by zsmb13** [comment]
There are some incompatible changes in ExoPlayer 2.13.3 from 2.12.1 which is currently integrated in the latest released version of our SDK (4.9.2).

We'll ship that mentioned PR in an upcoming release, that will update our library's integration to 2.13.3 as well. Please hold off on upgrading the ExoPlayer version until then.

**Comment by rupinderjeet** [comment]
Thank you for clarification.

**Comment by zsmb13** [comment]
The PR above is now merged, it'll be part of the next release (sometime next week).

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 

The ExoPlayer dependency has been already upgrade and a [new version](https://github.com/GetStream/stream-chat-android/releases/latest) of Stream's Artifacs have been released
