### ISSUE TITLE
Error inflating stream_ui_dialog_attachment layout. 

### ISSUE THREAD

**Issue by rpadma** [GetStream/stream-chat-android#1901]
**Describe the bug**
App crashed when tapped on the Attachment/ Paper clip icon on the `io.getstream.chat.android.ui.message.input.MessageInputView`. 
 I'm using the stream android UI components library - `io.getstream:stream-chat-android-ui-components:4.10.0`

**SDK version**
- 4.10.0

**To Reproduce**
 1) Open a channel with messages
 2) Click on the Attachment/ Paper clip icon. 

**Expected behavior**
Should open the view/ bottom sheet dialog as shown in the example app showing all the images from the device. 

**Device:**
 - Pixel 4 
 - Android version: S

**More logs:**
`layout/stream_ui_dialog_attachment: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at io.getstream.chat.android.ui.databinding.StreamUiDialogAttachmentBinding.inflate(StreamUiDialogAttachmentBinding.java:75)
        at io.getstream.chat.android.ui.message.input.attachment.internal.AttachmentDialogFragment.onCreateView(AttachmentDialogFragment.kt:36)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)`

**Comment by ogkuzmin** [comment]
Hello, @rpadma
Do you have in your Gradle dependency list a dependency for material library artifact? If yes could you say which version?
Also, please, check that your app theme uses MaterialTheme as a base.

**Comment by ogkuzmin** [comment]
@rpadma Yes, having Matherial Theme is required. Because we use a lot of material widget and style them. At least try to use BridgeTheme

**Comment by rpadma** [comment]
> @rpadma Yes, having Matherial Theme is required. Because we use a lot of material widget and style them. At least try to use BridgeTheme

@ogkuzmin - I'm still seeing the crash after using the MaterialTheme for the app theme.  `parent="Base.Theme.MaterialComponents"`

**Comment by ogkuzmin** [comment]
@rpadma It's really strange. Please make Build -> Clean Project in android studio and try again. If crash still happens, please can you show your build.gradle file, especially with dependency part?

**Comment by rpadma** [comment]
> @rpadma It's really strange. Please make Build -> Clean Project in android studio and try again. If crash still happens, please can you show your build.gradle file, especially with dependency part?

@ogkuzmin  - I did try to clean the build and invalidate the cache/ restarted the Android studio. Here is the screenshot of the Gradle dependencies 
![image](https://user-images.githubusercontent.com/5199471/119865177-679e0a00-bee9-11eb-810d-8ac825f5e1a5.png)

**Comment by ogkuzmin** [comment]
@rpadma I reproduce this crash. It happens when the activity with message input view has an `AppCompat` base theme. So, please, make sure that you applied the right theme based on `Theme.MaterialComponents`. 
You could have a theme for different SDK levels (`values-v*API-LEVEL*\`) and be sure that you have the correct theme for the according device level.

**Comment by rpadma** [comment]
> @rpadma I reproduce this crash. It happens when the activity with message input view has an `AppCompat` base theme. So, please, make sure that you applied the right theme based on `Theme.MaterialComponents`.
> You could have a theme for different SDK levels (`values-v*API-LEVEL*\`) and be sure that you have the correct theme for the according device level.

@ogkuzmin - Thank you. Applying the theme to the chat activity worked. The app is still using a different theme. This is working so closing the issue.
