### ISSUE TITLE
Push notification does not open

### ISSUE THREAD

**Issue by SeanOThomas** [GetStream/stream-chat-android#1922]
**Describe the bug**
When I tap a push notification, nothing happens. The following exception is logged:

```
2021-06-03 12:54:32.733 12495-12530/nz.co.trademe.trademe.debug W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjc@bb8f0c9
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1466)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1622)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:697)
        at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
        at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
        at com.google.android.gms.measurement.internal.zzik.zzah(com.google.android.gms:play-services-measurement-impl@@17.2.0:240)
        at com.google.android.gms.measurement.internal.zzik.zzak(com.google.android.gms:play-services-measurement-impl@@17.2.0:257)
        at com.google.android.gms.measurement.internal.zzik.zzc(com.google.android.gms:play-services-measurement-impl@@17.2.0:319)
        at com.google.android.gms.measurement.internal.zzij.zza(com.google.android.gms:play-services-measurement-impl@@17.2.0:2)
        at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.2.0:7)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.android.gms.measurement.internal.zzfy.run(com.google.android.gms:play-services-measurement-impl@@17.2.0:20)
```       

The service is registered like the following: 
```
    <service
            android:name="io.getstream.chat.android.livedata.service.sync.OfflineSyncFirebaseMessagingService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

Custom handler:

```
class CustomChatNotificationHandler(context: Context, notificationConfig: NotificationConfig) :
    ChatNotificationHandler(context, notificationConfig) {

    override fun getNewMessageIntent(
        messageId: String,
        channelType: String,
        channelId: String
    ): Intent {
        return ChatActivity.newIntent(context, channelId).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
        }
    }
    override fun getNotificationChannelName(): String {
        return "Messaging"
    }
}
```

ChatActivity.newIntent

```
        fun newIntent(context: Context, channelId: String): Intent =
            Intent(context, ChatActivity::class.java).putExtra(CID_KEY, channelId)
```     

SDK initialisation

```
object ChatInitializer {

    fun initSdk(context: Context, apiKey: String) {
        val logLevel = if (BuildConfig.DEBUG) ChatLogLevel.ALL else ChatLogLevel.NOTHING

        val client = ChatClient.Builder(apiKey, context)
            .logLevel(logLevel)
            .notifications(CustomChatNotificationHandler(context, NotificationConfig()))
            .build()

        ChatDomain.Builder(client, context)
            .offlineEnabled()
            .build()
    }
}
```       

**SDK version**
- io.getstream:stream-chat-android-ui-components:4.9.2

**To Reproduce**
1. Receive a push notification
2. Tap the push notification
3. The push notification disappears, but the app is not launched

**Expected behavior**
The app/chat is opened 

**Device:**
 - Reproduced on multiple Android devices

**Comment by samiuelson** [comment]
Hi @SeanOThomas , the issue should be already solved in the latest [release](https://github.com/GetStream/stream-chat-android/releases/tag/4.11.0). We've improved notifications implementation API and fixed a lot of issues. Please give it a try and let us know if it works for you.
