### ISSUE TITLE
App Crash when using system generated token 

### ISSUE THREAD

**Issue by pratikvyas1991** [GetStream/stream-chat-android#1930]
**Describe the bug**
Application is crashing when using token generated using backend server.

**Ref Link** : [GetStream Char tutorial](https://getstream.io/chat/docs/android/?language=kotlin)
I am using above link for developing chat demo for my app and app works fine when i use token generated statically as mentioned in the example, how ever when I am using token generated from our backend server it is causing crash. same token is working in IOS counterpart so there is something i am missing in implementation .

 Note : I am using firebase crashlytics also and i am not sure what causing this error  

**SDK version**

   ```
 implementation "io.getstream:stream-chat-android-ui-components:4.10.0"
    implementation "io.getstream:stream-chat-android-offline:4.10.0"
    implementation "io.getstream:stream-chat-android-client:4.10.0"
    implementation 'io.coil-kt:coil:1.2.0'
    implementation "androidx.activity:activity-ktx:1.2.3"
    implementation platform('com.google.firebase:firebase-bom:28.0.1')
    implementation 'com.google.firebase:firebase-analytics:19.0.0'
    implementation 'com.google.firebase:firebase-crashlytics:18.0.0'
```

**Code Snippet** 

```
fun init(contextCompat: Context) = initStreamClient {
        val tokenProvider = object : TokenProvider {
            override fun loadToken(): String {
                return UserPref.streamIOToken
            }
        }
        val key = "api key##"
        streamChatClient = ChatClient.Builder(key.trim(),contextCompat).build()

        chatDomain = ChatDomain.Builder(streamChatClient,contextCompat).build()
        val usr1 = User(
            id = UserPref.userId,
            extraData = mutableMapOf(
                "name" to "pratik",
                "image" to "https://bit.ly/2TIt8NR"
            )
        )
        streamChatClient.connectUser(
            user = usr1,
            tokenProvider = tokenProvider
        ).await()
    }

```

**Crash Trace**

```
  --------- beginning of crash
2021-06-03 19:05:45.314 20272-20272/nutritiion.charge E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nutritiion.charge, PID: 20272
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
        at io.getstream.chat.android.client.notifications.handler.ChatNotificationHandler.getFirebaseInstanceId(ChatNotificationHandler.kt:259)
        at io.getstream.chat.android.client.notifications.ChatNotifications.onSetUser(ChatNotifications.kt:37)
        at io.getstream.chat.android.client.ChatClient$1.onEvent(ChatClient.kt:124)
        at io.getstream.chat.android.client.utils.observable.SubscriptionImpl.onNext(Subscriptions.kt:36)
        at io.getstream.chat.android.client.utils.observable.ChatEventsObservable.onNext(ChatEventsObservable.kt:29)
        at io.getstream.chat.android.client.utils.observable.ChatEventsObservable.access$onNext(ChatEventsObservable.kt:17)
        at io.getstream.chat.android.client.utils.observable.ChatEventsObservable$EventsMapper.onConnected(ChatEventsObservable.kt:89)
        at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$$special$$inlined$observable$1$lambda$1.invoke(ChatSocketServiceImpl.kt:74)
        at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$$special$$inlined$observable$1$lambda$1.invoke(ChatSocketServiceImpl.kt:24)
        at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$callListeners$$inlined$synchronized$lambda$1.run(ChatSocketServiceImpl.kt:224)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/nutritiion.charge-f698yuGX9SUjHUsM9bVaxg==/base.apk"],nativeLibraryDirectories=[/data/app/nutritiion.charge-f698yuGX9SUjHUsM9bVaxg==/lib/arm64, /data/app/nutritiion.charge-f698yuGX9SUjHUsM9bVaxg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.getstream.chat.android.client.notifications.handler.ChatNotificationHandler.getFirebaseInstanceId(ChatNotificationHandler.kt:259) 
        at io.getstream.chat.android.client.notifications.ChatNotifications.onSetUser(ChatNotifications.kt:37) 
        at io.getstream.chat.android.client.ChatClient$1.onEvent(ChatClient.kt:124) 
        at io.getstream.chat.android.client.utils.observable.SubscriptionImpl.onNext(Subscriptions.kt:36) 
        at io.getstream.chat.android.client.utils.observable.ChatEventsObservable.onNext(ChatEventsObservable.kt:29) 
        at io.getstream.chat.android.client.utils.observable.ChatEventsObservable.access$onNext(ChatEventsObservable.kt:17) 
        at io.getstream.chat.android.client.utils.observable.ChatEventsObservable$EventsMapper.onConnected(ChatEventsObservable.kt:89) 
        at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$$special$$inlined$observable$1$lambda$1.invoke(ChatSocketServiceImpl.kt:74) 
        at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$$special$$inlined$observable$1$lambda$1.invoke(ChatSocketServiceImpl.kt:24) 
        at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$callListeners$$inlined$synchronized$lambda$1.run(ChatSocketServiceImpl.kt:224) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:241) 
        at android.app.ActivityThread.main(ActivityThread.java:7617) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941) 
2021-06-03 19:05:45.608 20272-20399/nutritiion.charge D/TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
2021-06-03 19:05:45.626 20272-20419/nutritiion.charge V/FA: Connecting to remote service
2021-06-03 19:05:45.639 20272-20399/nutritiion.charge D/TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=1766928631 in 11618ms(Backend next call timestamp 1622727357255). Attempt 1
2021-06-03 19:05:45.643 20272-20419/nutritiion.charge V/FA: Recording user engagement, ms: 13858
2021-06-03 19:05:45.703 20272-20419/nutritiion.charge V/FA: Connection attempt already in progress
```

**To Reproduce**
1. Go to connection class connect chat client using system generated token .
2. Wait after sometime 
3. Observe the crash

**Expected behavior**
App needed to get connected using system generated tokens 

**Device:**
 - Observed in all devices , Pixels, motorola one power
 - Android version: [9,10]

**Comment by samiuelson** [comment]
Hi @pratikvyas1991 , the issue should be already solved in the latest [release](https://github.com/GetStream/stream-chat-android/releases/tag/4.11.0). Please give it a try and let us know if it works for you.

**Comment by pratikvyas1991** [comment]
Hello @samiuelson ,
thanks for so quick reply update and providing proper guidance  .
Changing the latest version solved my issue .
Thanks again
