### ISSUE TITLE
Crash after the first time installed then when try to reopen it again it works fine

### ISSUE THREAD

**Issue by MostafaAnter** [GetStream/stream-chat-android#1943]
**Describe the bug**
My App crash after the first time installed then when try to open it again it works fine
I think the main problem is calling 
`override fun onNewToken(token: String) { 
        // Update device's token on Stream backend 
        try { 
            ChatClient.setFirebaseToken(token) 
        } catch (exception: IllegalStateException) { 
            // ChatClient was not initialized 
        } 
    } `

inside ChatFirebaseMessagingService before init chat client so how I can manage onNewToken call
because it seems call automatic after install the app and crash but the next time open app its work well because 
there is no call for onNewToken 

**SDK version**
- 4.11.0

**Expected behavior**
after the first time open the app and work without a crash.

**Device:**
 - all devices and emulators

**Screenshots**
`2021-06-08 12:23:46.868 24914-25241/app.Application E/AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
    Process: app.aplication, PID: 24914
    java.lang.IllegalArgumentException: ChatClient should be initialized first!
        at io.getstream.chat.android.client.ChatClient$Companion.ensureClientInitialized(ChatClient.kt:1705)
        at io.getstream.chat.android.client.ChatClient$Companion.setFirebaseToken(ChatClient.kt:1700)
        at io.getstream.chat.android.client.notifications.ChatFirebaseMessagingService.onNewToken(ChatFirebaseMessagingService.kt:25)
        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@22.0.0:5)
        at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@22.0.0:1)
        at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(Unknown Source:6)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.3.0:6)
        at java.lang.Thread.run(Thread.java:929)`

**Comment by adasiewiczr** [comment]
Hey @MostafaAnter, thanks for submitting this issue. It was resolved in the PR mentioned above and will be shipped in the next release

**Comment by MostafaAnter** [comment]
For suggesting I think the best solution will be to prevent token autogeneration, disable Analytics collection and FCM auto initialization (you must disable both) by adding these metadata values to your AndroidManifest.xml:

`<meta-data
    android:name="firebase_messaging_auto_init_enabled"
    android:value="false" />
<meta-data
    android:name="firebase_analytics_collection_enabled"
    android:value="false" />`

To re-enable FCM auto-init after ensure that the chat client initiates successfully, make a runtime call:

`Firebase.messaging.isAutoInitEnabled = true`

reference --> [Prevent auto initialization](https://firebase.google.com/docs/cloud-messaging/android/client#prevent-auto-init)

**Comment by adasiewiczr** [comment]
Hello @MostafaAnter,
We've released a new version with the fix mentioned above. You can check it [here](https://github.com/GetStream/stream-chat-android/releases/tag/4.12.0).
