### ISSUE TITLE
[Crash][AttachmentGalleryActivity] Empty list doesn't contain element at index 0.

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#1959]
Crashlytics logs indicate that Application was just launched when the issue occurs. So, I believe, user paused on AttachmentGalleryActivity, and something like process death happens.

Following is the stack trace I received:
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
       at kotlin.collections.EmptyList.get(Collections.kt:36)
       at kotlin.collections.EmptyList.get(Collections.kt:24)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.onGalleryPageSelected(AttachmentGalleryActivity.kt:157)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.observePageChanges(AttachmentGalleryActivity.kt:139)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.setupGallery(AttachmentGalleryActivity.kt:86)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.access$setupGallery(AttachmentGalleryActivity.kt:36)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity$onCreate$2.invoke(AttachmentGalleryActivity.kt:78)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity$onCreate$2.invoke(AttachmentGalleryActivity.kt:36)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity$sam$androidx_lifecycle_Observer$0.onChanged(:2)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
       at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
       at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
       at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
       at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
       at android.app.Activity.dispatchActivityPostStarted(Activity.java:1278)
       at android.app.Activity.performStart(Activity.java:8018)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3580)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

v4.10.0

**Comment by JcMinarro** [comment]
Hello @rupinderjeet 
Thanks for reporting this issue. We are fixing it

**Comment by adasiewiczr** [comment]
Hello @rupinderjeet,
We've released a new version with the fix mentioned above. You can check it [here](https://github.com/GetStream/stream-chat-android/releases/tag/4.12.0).
