### ISSUE TITLE
Crash when it get channel

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#2029]
**Describe the bug**
I have the crash below

```E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6
     java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:899)
        at java.util.TimSort.mergeAt(TimSort.java:516)
        at java.util.TimSort.mergeCollapse(TimSort.java:441)
        at java.util.TimSort.sort(TimSort.java:245)
        at java.util.Arrays.sort(Arrays.java:1492)
        at java.util.ArrayList.sort(ArrayList.java:1470)
        at java.util.Collections.sort(Collections.java:206)
        at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:42)
        at kotlin.sequences.SequencesKt___SequencesKt$sortedWith$1.iterator(_Sequences.kt:638)
        at kotlin.sequences.TakeSequence$iterator$1.<init>(Sequences.kt:411)
        at kotlin.sequences.TakeSequence.iterator(Sequences.kt:409)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
        at io.getstream.chat.android.offline.extensions.ChannelKt.applyPagination(Channel.kt:62)
        at io.getstream.chat.android.offline.ChatDomainImpl.selectAndEnrichChannels(ChatDomainImpl.kt:858)
        at io.getstream.chat.android.offline.ChatDomainImpl.access$selectAndEnrichChannels(ChatDomainImpl.kt:137)
        at io.getstream.chat.android.offline.ChatDomainImpl$selectAndEnrichChannels$2.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**SDK version**
- 4.12.1

**To Reproduce**
1. No precise step to reproduce. I just launch my app

**Expected behavior**
No crash

**Device:**
 - Vendor and model: Google pixel 2 xl
 - Android version: 11

**Comment by ogkuzmin** [comment]
Hey! Is this crash 100% reproducible in your case? Has it any repeats? Could you delete the app and run it again? Does it happen again?

**Comment by spvince** [comment]
If i relaunch my app i still have the crash. If i clear the app data, my app works normally.

**Comment by ogkuzmin** [comment]
@spvince I think your started screen should be some with `ChannelList`. If it is so could you show what kind of `QuerySort` do you apply for this `ChannelList`?

**Comment by spvince** [comment]
Sure @ogkuzmin 

'''
          sort = QuerySort<Channel>()
                .desc(Channel::hasUnread)
                .desc(Channel::lastMessageAt)
'''

**Comment by ogkuzmin** [comment]
@spvince thanks for submitting the issue. The fix was merged and will be available in the next release (I hope it will happen this week)

**Comment by adasiewiczr** [comment]
Hey @spvince,
We've released a new version with the fix mentioned above. You can check it [here](https://github.com/GetStream/stream-chat-android/releases/tag/4.14.0).
