### ISSUE TITLE
Crash with font

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#2171]
**Describe the bug**
I modified font of io.getstream.chat.android.ui.message.list.MessageListView

`          
app:streamUiMessageTextFontMine="@font/roboto_regular"
       app:streamUiMessageTextFontTheirs="@font/roboto_regular"
`

And I have the crash below 

``` 
java.lang.NoSuchMethodError: No virtual method contains(I)Z in class Landroid/util/SparseArray; or its super classes (declaration of 'android.util.SparseArray' appears in /system/framework/framework.jar!classes2.dex)
        at io.getstream.chat.android.ui.common.style.ChatFontsImpl.getFont(ChatFontsImpl.kt:60)
        at io.getstream.chat.android.ui.common.style.ChatFontsImpl.getFont(ChatFontsImpl.kt:42)
        at io.getstream.chat.android.ui.common.style.TextStyle.getFont(TextStyle.kt:34)
        at io.getstream.chat.android.ui.common.style.ChatFontsImpl.setFont(ChatFontsImpl.kt:32)
        at io.getstream.chat.android.ui.common.style.TextStyle.apply(TextStyle.kt:53)
        at io.getstream.chat.android.ui.message.list.adapter.viewholder.decorator.internal.TextDecorator.setupTextView(TextDecorator.kt:28)
        at io.getstream.chat.android.ui.message.list.adapter.viewholder.decorator.internal.TextDecorator.decoratePlainTextMessage(TextDecorator.kt:19)
        at io.getstream.chat.android.ui.message.list.adapter.viewholder.decorator.internal.BaseDecorator.decorate(BaseDecorator.kt:23)
        at io.getstream.chat.android.ui.message.list.adapter.internal.DecoratedBaseMessageItemViewHolder.bindData(DecoratedBaseMessageItemViewHolder.kt:16)
        at io.getstream.chat.android.ui.message.list.adapter.viewholder.internal.MessagePlainTextViewHolder.bindData(MessagePlainTextViewHolder.kt:56)
        at io.getstream.chat.android.ui.message.list.adapter.viewholder.internal.MessagePlainTextViewHolder.bindData(MessagePlainTextViewHolder.kt:16)
        at io.getstream.chat.android.ui.message.list.adapter.BaseMessageItemViewHolder.bindListItem$stream_chat_android_ui_components_release(BaseMessageItemViewHolder.kt:33)
        at io.getstream.chat.android.ui.message.list.adapter.internal.MessageListItemAdapter.onBindViewHolder(MessageListItemAdapter.kt:50)
        at io.getstream.chat.android.ui.message.list.adapter.internal.MessageListItemAdapter.onBindViewHolder(MessageListItemAdapter.kt:12)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:643)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22419)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
```

**Project configuration:**
        minSdkVersion 21
        targetSdkVersion 30   
        compileSdkVersion 30
        buildToolsVersion "30.0.3"

**SDK version**
- 4.15.0

**To Reproduce**
1. Open Chat view

**Expected behavior**
No crash

**Device:**
 - Vendor and model: Samsung S8
 - Android version:10

**Comment by adasiewiczr** [comment]
Hey @spvince, thanks for reporting that. We'll check it and come up with a solution soon.
