### ISSUE TITLE
Compose SDK causes crash in release build

### ISSUE THREAD

**Issue by jeffnyauke** [GetStream/stream-chat-android#2229]
**Describe the bug**
The compose SDK causes my release build to crash with the following error:

```
2021-08-16 21:04:27.204 6653-6653/com.smartapplicationsgroup.pae.androidApp.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.smartapplicationsgroup.pae.androidApp.dev, PID: 6653
    java.lang.IllegalArgumentException: Unexpected signature for public final io.getstream.chat.android.client.api2.model.dto.DownstreamMessageDto io.getstream.chat.android.client.parser2.adapters.DownstreamMessageDtoAdapter.fromJson(com.squareup.moshi.t,com.squareup.moshi.n,com.squareup.moshi.n).
    @FromJson method signatures may have one of the following structures:
        <any access modifier> R fromJson(JsonReader jsonReader) throws <any>;
        <any access modifier> R fromJson(JsonReader jsonReader, JsonAdapter<any> delegate, <any more delegates>) throws <any>;
        <any access modifier> R fromJson(T value) throws <any>;
    
        at com.squareup.moshi.e.b(SourceFile:301)
        at com.squareup.moshi.e.d(SourceFile:135)
        at com.squareup.moshi.d0.b(SourceFile:223)
        at xa.a.a(SourceFile:49)
        at xa.a.invoke(SourceFile:45)
        at kotlin.SynchronizedLazyImpl.getValue(SourceFile:74)
        at xa.b.b(SourceFile:45)
        at xa.b.<init>(SourceFile:83)
        at oa.i.a(SourceFile:66)
        at oa.i.invoke(SourceFile:66)
        at kotlin.SynchronizedLazyImpl.getValue(SourceFile:74)
        at oa.k.D(SourceFile:66)
        at oa.k.i(SourceFile:54)
        at oa.k.p(SourceFile:266)
        at oa.k.b(SourceFile:54)
        at oa.c.a(SourceFile:71)
        at oa.c.invoke(SourceFile:71)
        at kotlin.SynchronizedLazyImpl.getValue(SourceFile:74)
        at oa.k.y(SourceFile:71)
        at oa.k.n(SourceFile:93)
        at ga.c.a(SourceFile:1558)
        at e9.i5.a(SourceFile:177)
        at we.t1.d(SourceFile:398)
        at we.s1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
        at te.h1.d(SourceFile:234)
        at te.h1.e(SourceFile:190)
        at te.h1.a(SourceFile:161)
        at te.q.p(SourceFile:397)
        at te.q.H(SourceFile:431)
        at te.q.I(SourceFile:420)
        at te.q.resumeWith(SourceFile:328)
        at we.v1.f(SourceFile:286)
        at we.t1.s(SourceFile:351)
        at we.t1.r(SourceFile:318)
        at e9.u0.a(SourceFile:135)
        at q9.m.a(SourceFile:138)
        at we.o.c(SourceFile:62)
        at we.o.a(SourceFile:1)
        at we.n.invokeSuspend(Unknown Source:11)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
        at te.g1.run(SourceFile:106)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6819)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
```
My debug build works fine

**SDK version**
- 4.15.1-beta (io.getstream:stream-chat-android-compose:4.15.1-beta)

**To Reproduce**
1. Add the library dependency
2. Configure the composables

This is my build configuration:

```
    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("release")
            isDebuggable = true
        }
        getByName("debug") {
            applicationIdSuffix = ".debug"
            signingConfig = signingConfigs.getByName("debug")
        }
    }
```

**Expected behavior**
I expect the app to run smoothly like the debug build.

**Device:**
 - Vendor and model: Tecno Camon 12
 - Android version: 10

**Screenshots**

**Comment by zsmb13** [comment]
Hi @jeffnyauke, thanks for reporting this issue.

Do you have any other configuration related to Proguard or Moshi in your application? How do you include our library as a dependency?

The [sample app for the Compose UI Components](https://github.com/GetStream/stream-chat-android/tree/main/stream-chat-android-compose-sample) works in release mode with minification enabled (it's able to use the adapter mentioned in the stacktrace, and messages load correctly).

You can test the minified Compose sample app [on this branch](https://github.com/GetStream/stream-chat-android/tree/feature/enable-minification-in-compose-sample/stream-chat-android-compose-sample) temporarily, and on [`develop`](https://github.com/GetStream/stream-chat-android/tree/develop/stream-chat-android-compose-sample) soon (pending #2231).
