### ISSUE TITLE
App crash on clicking pdf 

### ISSUE THREAD

**Issue by bibinkrishnan** [GetStream/stream-chat-android#2320]
App is getting crashed when trying to view pdf

**SDK version**
- 4.17.3

**To Reproduce**
1. Go to message
2. Click on pdf
3. App getting crashed

**_java.lang.RuntimeException: Unable to start activity ComponentInfo{com.evero.android.digitalagency/com.getstream.sdk.chat.view.activity.AttachmentDocumentActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.getstream.sdk.chat.view.activity.AttachmentDocumentActivity.onCreate(AttachmentDocumentActivity.java:38)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)_**

**Comment by ogkuzmin** [comment]
Hello, @bibinkrishnan 
Did you apply some theme in your manifest for that activity?

**Comment by bibinkrishnan** [comment]
I replaced with your theme, now the crash issue got solved. But while clicking pdf its unable to load showing 'no preview available' 
This is the pdf url "https://docs.google.com/gview?embedded=true&url=https://us-east.stream-io-cdn.com/1116822/attachments/f6aada80-f177-43c6-ab9b-f6171b5a5b10.sample.pdf?dl=sample.pdf&Expires=1632457200&Signature=MAL~pxFiIbz6~rFh-7dkPPiYWDqMjdh8NHuUvkrcTEbPsuUSxJwu4lmXeNCfUoBrm2O2VBZb6D-i~XimbAEwuNl21DZTREAIKGMZ0NsSU-fMnTGOCqg020CKAK28EAJZrb2NvnYVZMrLk6I0ZBc2inW9aRIXTNXL7HfIUa4fUlH6MzVjxzgbfOv-NpDRtu0sV7u285WD-T8febCLNpMSZIIoAnJL-J4bFRRI4ywHkS2LXG2dnH2kqNMApehgLBvt9NWiX4rZirfrI6L-OpvJ75XwA1r74XgQWuzXoGsenCDPxc013D0CBqKtNaf2DJbNQNaRHF1nVBaUvFGc~nWN9Q__&Key-Pair-Id=APKAIHG36VEWPDULE23Q"

**Comment by ogkuzmin** [comment]
> I replaced with your theme, now the crash issue got solved. But while clicking pdf its unable to load showing 'no preview available'
> This is the pdf url "https://docs.google.com/gview?embedded=true&url=https://us-east.stream-io-cdn.com/1116822/attachments/f6aada80-f177-43c6-ab9b-f6171b5a5b10.sample.pdf?dl=sample.pdf&Expires=1632457200&Signature=MAL~pxFiIbz6~rFh-7dkPPiYWDqMjdh8NHuUvkrcTEbPsuUSxJwu4lmXeNCfUoBrm2O2VBZb6D-i~XimbAEwuNl21DZTREAIKGMZ0NsSU-fMnTGOCqg020CKAK28EAJZrb2NvnYVZMrLk6I0ZBc2inW9aRIXTNXL7HfIUa4fUlH6MzVjxzgbfOv-NpDRtu0sV7u285WD-T8febCLNpMSZIIoAnJL-J4bFRRI4ywHkS2LXG2dnH2kqNMApehgLBvt9NWiX4rZirfrI6L-OpvJ75XwA1r74XgQWuzXoGsenCDPxc013D0CBqKtNaf2DJbNQNaRHF1nVBaUvFGc~nWN9Q__&Key-Pair-Id=APKAIHG36VEWPDULE23Q"

I have "The preview isn't available" in my Google Chrome. I believe something wrong with this PDF

**Comment by ogkuzmin** [comment]
BTW, the crash is fixed in our current develop branch. Will be released at the beginning of the next week.

**Comment by bychkovdmitry** [comment]
Hello @bibinkrishnan  
We have released a new version that should fix your issue.
Could you check the [latest version](https://github.com/GetStream/stream-chat-android/releases/latest)?
