### ISSUE TITLE
Crash On Uploaded PDF click on chat

### ISSUE THREAD

**Issue by bibink874** [GetStream/stream-chat-android#2324]
**Describe the bug**
Crash occurs file click on uploaded pdf attachment in chat.

 Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.getstream.sdk.chat.view.activity.AttachmentDocumentActivity.onCreate(AttachmentDocumentActivity.java:38)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)

**SDK version**
- 4.17.3

**To Reproduce**
1. Go to single chat
2. Click on attachment
3. attach a pdf file and send
4. click on the send pdf

**Expected behavior**
Need to show pdf without crash

**Device:**
 - All Android Device

**Comment by ogkuzmin** [comment]
Hello @bibink874 
I see another one issue (#2320) related to the same problem. I tried to reproduce it and it works fine in our sample app. Did you apply some theme to this activity?

**Comment by bibink874** [comment]
Issue is related to AttachmentDocumentActivity.java activity which is inside your SDK. Not applied any theme.

**Comment by ogkuzmin** [comment]
The crash is fixed in our current develop branch. Will be released at the beginning of the next week.
I close this issue as doubling of #2320
