### ISSUE TITLE
MessageDeletedEvent is not delivered

### ISSUE THREAD

**Issue by YasserHossam** [GetStream/stream-chat-android#2360]
**Describe the issue**

When i watch a channel between me and some other client, then the other client removed a message, I don't receive a MessageDeletedEvent, instead, i get an exception in the logs, and then, the sdk stops delivering any other event 
here's the output logs i get

```
2021-09-17 14:24:22.817 2086-2951/com.eventtus.android.eventtusvirtual I/Chat:Events: {"type":"message.deleted","cid":"boe-qa:starwars-911fd179-a0f5-4b9e-aeaa-e87f54866def-qa-u","channel_id":"starwars-911fd179-a0f5-4b9e-aeaa-e87f54866def-qa-u","channel_type":"boe-qa","message":{"id":"1154f6d9-ad8c-4c7a-a0e7-40fc32f25e6b","text":"new","html":"\u003cp\u003enew\u003c/p\u003e\n","type":"deleted","user":{"id":"starwars-898","role":"user","created_at":"2021-08-01T09:50:36.04415Z","updated_at":"2021-09-17T12:24:16.209446Z","last_active":"2021-09-17T12:23:54.250372Z","banned":false,"online":true,"teams":["starwars"],"image":"","name":"Abdelrahman Badary"},"attachments":[],"latest_reactions":[],"own_reactions":[],"reaction_counts":{},"reaction_scores":{},"reply_count":0,"cid":"boe-qa:starwars-911fd179-a0f5-4b9e-aeaa-e87f54866def-qa-u","created_at":"2021-09-17T12:24:16.223Z","updated_at":"2021-09-17T12:24:16.223Z","deleted_at":"2021-09-17T12:24:23.673259179Z","shadowed":false,"mentioned_users":[],"silent":false,"pinned":false,"pinned_at":null,"pinned_by":null,"pin_expires":null},"team":"starwars","created_at":"2021-09-17T12:24:23.682317206Z","hard_delete":true}
2021-09-17 14:24:22.859 2086-2951/com.eventtus.android.eventtusvirtual E/Chat:NEW_SERIALIZATION_ERROR: com.squareup.moshi.JsonDataException: Required value 'user' missing at $
        at com.squareup.moshi.internal.Util.missingProperty(Util.java:649)
        at io.getstream.chat.android.client.api2.model.dto.MessageDeletedEventDtoJsonAdapter.fromJson(MessageDeletedEventDtoJsonAdapter.kt:77)
        at io.getstream.chat.android.client.api2.model.dto.MessageDeletedEventDtoJsonAdapter.fromJson(MessageDeletedEventDtoJsonAdapter.kt:21)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.JsonAdapter.fromJsonValue(JsonAdapter.java:126)
        at io.getstream.chat.android.client.parser2.adapters.EventDtoAdapter.fromJson(EventAdapter.kt:190)
        at io.getstream.chat.android.client.parser2.adapters.EventDtoAdapter.fromJson(EventAdapter.kt:66)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
        at io.getstream.chat.android.client.parser2.MoshiChatParser.parseAndProcessEvent(MoshiChatParser.kt:137)
        at io.getstream.chat.android.client.parser2.MoshiChatParser.fromJson(MoshiChatParser.kt:100)
        at io.getstream.chat.android.client.parser.ChatParser$DefaultImpls.fromJsonOrError(ChatParser.kt:23)
        at io.getstream.chat.android.client.parser2.MoshiChatParser.fromJsonOrError(MoshiChatParser.kt:41)
        at io.getstream.chat.android.client.socket.EventsParser.handleEvent(EventsParser.kt:72)
        at io.getstream.chat.android.client.socket.EventsParser.onMessage(EventsParser.kt:36)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2021-09-17 14:24:22.861 2086-2951/com.eventtus.android.eventtusvirtual E/Chat:SocketService: Status code: -1, with stream code: 1005, description: Unable to parse event
2021-09-17 14:24:22.863 2086-2951/com.eventtus.android.eventtusvirtual E/Chat:SocketService: com.squareup.moshi.JsonDataException: Required value 'user' missing at $
        at com.squareup.moshi.internal.Util.missingProperty(Util.java:649)
        at io.getstream.chat.android.client.api2.model.dto.MessageDeletedEventDtoJsonAdapter.fromJson(MessageDeletedEventDtoJsonAdapter.kt:77)
        at io.getstream.chat.android.client.api2.model.dto.MessageDeletedEventDtoJsonAdapter.fromJson(MessageDeletedEventDtoJsonAdapter.kt:21)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.JsonAdapter.fromJsonValue(JsonAdapter.java:126)
        at io.getstream.chat.android.client.parser2.adapters.EventDtoAdapter.fromJson(EventAdapter.kt:190)
        at io.getstream.chat.android.client.parser2.adapters.EventDtoAdapter.fromJson(EventAdapter.kt:66)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
        at io.getstream.chat.android.client.parser2.MoshiChatParser.parseAndProcessEvent(MoshiChatParser.kt:137)
        at io.getstream.chat.android.client.parser2.MoshiChatParser.fromJson(MoshiChatParser.kt:100)
        at io.getstream.chat.android.client.parser.ChatParser$DefaultImpls.fromJsonOrError(ChatParser.kt:23)
        at io.getstream.chat.android.client.parser2.MoshiChatParser.fromJsonOrError(MoshiChatParser.kt:41)
        at io.getstream.chat.android.client.socket.EventsParser.handleEvent(EventsParser.kt:72)
        at io.getstream.chat.android.client.socket.EventsParser.onMessage(EventsParser.kt:36)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:333)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:245)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**SDK versions**
- 4.18.0
- 4.17.1

**To Reproduce**
1. Watch a channel 
```
channelClient.watch().enqueue
```
2. Subscribe for all events for this channel  and log MessageDeletedEvent 
```
disposable = channelClient.subscribe { event -> 
                            when(event) {
                            is NewMessageEvent -> {
                                Timber.d("NewMessageEvent")
                                event.message 
                            }
                            is MessageDeletedEvent -> {
                                Timber.d("MessageDeletedEvent")
                                event.message
                            }
                       }
```
3. Make another user from another client (connecting to the same channel) create a new message then delete it
4. The NewMessageEvent will be reported but  MessageDeletedEvent will not be reported, instead, the exception in the logs will be raised
5. Make the other client create a new message
6. The NewMessageEvent will not be fired also because the exception raised in step number 4 will prevent any other events

**Expected behavior**

MessageDeletedEvent should be delivered

**Device:**
 - Vendor and model: Xiaomi note 5 plus and emulator
 - Android version: 8.1 and 9.0

**Comment by zsmb13** [comment]
Thanks for reporting this! We'll pick it up and fix it for the next release.

**Comment by bychkovdmitry** [comment]
Hello @YasserHossam,

Could you clarify what do you mean by "another client": 
- Another client SDK (e.g. swift, android, etc.)
- Or an SDK with server-side integration (e.g. JS client with server-side integration https://getstream.io/chat/docs/javascript/send_message/?language=javascript#delete-a-message)

**Comment by abdelrahman-badary** [comment]
@bychkovdmitry I verified the same behaviour happening in the iOS SDK when the delete is happening from the backend. here is more details about the issue https://github.com/GetStream/stream-chat-swift/issues/1477

**Comment by YasserHossam** [comment]
@bychkovdmitry
 As @abdelrahman-badary said, the deletion is happening from the backend, and the deletion is a hard delete
`{"hard_delete":true}`

This issue doesn't happen if the client was (swift, android, etc.), as the deletion method in this case is is a soft delete

**Comment by bychkovdmitry** [comment]
@YasserHossam 
We've addressed this problem in the PR above, the fix will be shipped in the next release.

**Comment by YasserHossam** [comment]
@bychkovdmitry
Thanks a lot for your help.
It will also be great if we can know when the next release will be released.
Thanks in advance.

**Comment by samiuelson** [comment]
Hey 👋🏼 The new [release](https://github.com/GetStream/stream-chat-android/releases/tag/4.19.0) containing the fix is now available. Please check it and let us know if you have any issues.

**Comment by YasserHossam** [comment]
Thanks @samiuelson it worked fine
