### ISSUE TITLE
Error in Logs

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#2394]
**Log**
```
E/Chat:NEW_SERIALIZATION_ERROR: com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: Non-null value 'mutes' was null at $.mutes at $.channels[6].read[0].user
        at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:101)
        at com.squareup.moshi.Moshi$Lookup.fromJson(Moshi.java:408)
        at io.getstream.chat.android.client.api2.model.dto.DownstreamChannelUserReadJsonAdapter.fromJson(DownstreamChannelUserReadJsonAdapter.kt:47)
        at io.getstream.chat.android.client.api2.model.dto.DownstreamChannelUserReadJsonAdapter.fromJson(DownstreamChannelUserReadJsonAdapter.kt:22)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at io.getstream.chat.android.client.api2.model.response.ChannelResponseJsonAdapter.fromJson(ChannelResponseJsonAdapter.kt:106)
        at io.getstream.chat.android.client.api2.model.response.ChannelResponseJsonAdapter.fromJson(ChannelResponseJsonAdapter.kt:32)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at io.getstream.chat.android.client.api2.model.response.QueryChannelsResponseJsonAdapter.fromJson(QueryChannelsResponseJsonAdapter.kt:39)
        at io.getstream.chat.android.client.api2.model.response.QueryChannelsResponseJsonAdapter.fromJson(QueryChannelsResponseJsonAdapter.kt:22)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:46)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
        at io.getstream.chat.android.client.parser2.MoshiErrorLoggingKt$withErrorLogging$1.responseBodyConverter$lambda-0(MoshiErrorLogging.kt:25)
        at io.getstream.chat.android.client.parser2.MoshiErrorLoggingKt$withErrorLogging$1.$r8$lambda$avdRyQtCDxTxehfl0DwpRaWHnVs(Unknown Source:0)
        at io.getstream.chat.android.client.parser2.MoshiErrorLoggingKt$withErrorLogging$1$$ExternalSyntheticLambda0.convert(Unknown Source:6)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.squareup.moshi.JsonDataException: Non-null value 'mutes' was null at $.mutes
        at com.squareup.moshi.internal.Util.unexpectedNull(Util.java:663)
        at io.getstream.chat.android.client.api2.model.dto.DownstreamUserDtoJsonAdapter.fromJson(DownstreamUserDtoJsonAdapter.kt:134)
        at io.getstream.chat.android.client.api2.model.dto.DownstreamUserDtoJsonAdapter.fromJson(DownstreamUserDtoJsonAdapter.kt:29)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.JsonAdapter.fromJsonValue(JsonAdapter.java:126)
        at io.getstream.chat.android.client.parser2.adapters.CustomObjectDtoAdapter.parseWithExtraData(CustomObjectDtoAdapter.kt:65)
        at io.getstream.chat.android.client.parser2.adapters.DownstreamUserDtoAdapter.fromJson(UserDtoAdapters.kt:19)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:383)
        at com.squareup.moshi.AdapterMethodsFactory$4.fromJson(AdapterMethodsFactory.java:269)
```

**SDK version**
- 4.18.0

**Device:**
 - Vendor and model: pixel 2 xl
 - Android version: 11

**Comment by samiuelson** [comment]
Hi thanks for reporting this. We will investigate. Is there any specific action to reproduce this error?

**Comment by spvince** [comment]
Hi, 
I haven't specific action to reproduce. I just saw this error during streamchat synchronisation.

I didn't have this error on sdk 4.17.0.

**Comment by bychkovdmitry** [comment]
Hello @spvince,

The fix was merged and will be shipped in the next release.

**Comment by samiuelson** [comment]
Hey 👋🏼 The new [release](https://github.com/GetStream/stream-chat-android/releases/tag/4.19.0) containing the fix is now available. Please check it and let us know if you have any issues.
