### ISSUE TITLE
Connection, sync problem when background networking is restricted

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#2411]
**Describe the bug**
App goes to background and come back to foreground while background networking is restricted(battery saver or network saver), connection is not restored. (sometimes)
we set LogLevel.ALL for debugging and find something to solve this issue

SocketServiceState is still `NetworkDisconnected` when activity is resumed

**SDK version**
- 4.19.0

**To Reproduce**
It is hard to reproduce.

1. Enable `Battery Saver` or `Data Saver`
2. Open some other apps and use them.
3. Go back to application, connection is disconnected (sometimes)

**Device:**
 - Samsung Galaxy S21 Ultra Android 11
 - Samsung Galaxy Note 10 Android 11

**Comment by workspace** [comment]
More information about this error.

## 1. sender's screenshot
![Sender](https://user-images.githubusercontent.com/7759511/135415092-12146756-a1d3-4103-9529-eb07d3104bf7.png)

## 2. receiver's video
- new messages are missing(last 3 messages in sender's screenshot), but loading more messages works well -> connection is restored?
https://user-images.githubusercontent.com/7759511/135415547-5af23799-3eb3-4566-bb00-f76cd6e711c5.mp4

## 3. receiver's crashlytics log
![Crashlytics](https://user-images.githubusercontent.com/7759511/135415067-e589f146-44c7-415c-9ab4-a28ff49caf71.png)
- parse event error -> I can't see more information via crashlytics. I guess it may be `NewMessagesEvent`
- connection errors has occured in SocketService
- unknown serialization error has also occured.
```
Non-fatal Exception: com.squareup.moshi.JsonDataException: Required value 'user' missing at $.member
       at com.squareup.moshi.internal.Util.missingProperty(Util.java:649)
       at io.getstream.chat.android.client.api2.model.dto.DownstreamMemberDtoJsonAdapter.fromJson(DownstreamMemberDtoJsonAdapter.java:90)
       at io.getstream.chat.android.client.api2.model.dto.DownstreamMemberDtoJsonAdapter.fromJson(DownstreamMemberDtoJsonAdapter.java:25)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
       at io.getstream.chat.android.client.api2.model.dto.NotificationRemovedFromChannelEventDtoJsonAdapter.fromJson(NotificationRemovedFromChannelEventDtoJsonAdapter.java:63)
       at io.getstream.chat.android.client.api2.model.dto.NotificationRemovedFromChannelEventDtoJsonAdapter.fromJson(NotificationRemovedFromChannelEventDtoJsonAdapter.java:21)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
       at com.squareup.moshi.JsonAdapter.fromJsonValue(JsonAdapter.java:126)
       at io.getstream.chat.android.client.parser2.adapters.EventDtoAdapter.fromJson(EventDtoAdapter.java:190)
       at io.getstream.chat.android.client.parser2.adapters.EventDtoAdapter.fromJson(EventDtoAdapter.java:66)
       at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
       at io.getstream.chat.android.client.parser2.MoshiChatParser.parseAndProcessEvent(MoshiChatParser.java:137)
       at io.getstream.chat.android.client.parser2.MoshiChatParser.fromJson(MoshiChatParser.java:100)
       at io.getstream.chat.android.client.parser.ChatParser$DefaultImpls.fromJsonOrError(ChatParser.java:23)
       at io.getstream.chat.android.client.parser2.MoshiChatParser.fromJsonOrError(MoshiChatParser.java:41)
       at io.getstream.chat.android.client.socket.EventsParser.handleEvent(EventsParser.java:72)
       at io.getstream.chat.android.client.socket.EventsParser.onMessage(EventsParser.java:36)
       at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:333)
       at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:245)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:106)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:293)
       at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.java:195)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
 ```

**Comment by bychkovdmitry** [comment]
Hello @workspace,

Thanks for reaching out. We'll take a look into this as soon as we can.

**Comment by ogkuzmin** [comment]
Hello, @workspace!
Speaking about reconnecting after going to background-foreground. We did some reconnection logic improvements in recent versions and it should work fine in our latest `4.20`. Could you please check it?
We can't verify behavior on enumerated devices, but on emulator and other devices it works fine.
