### ISSUE TITLE
Crash due to jetpack dependency related issue

### ISSUE THREAD

**Issue by yangkx1024** [GetStream/stream-chat-android#2419]
**Describe the bug**
I am try to using the `MessageListActivity` in my app, found that click the "attachment" button at the left bottom will cause a crash.

**SDK version**
- 4.19.0

**To Reproduce**
Integrated the android-ui-components:
```
implementation("io.getstream:stream-chat-android-ui-components:4.19.0")
implementation("io.coil-kt:coil:1.3.2")
```
Init the `ChatClient` and connect to a test user when app launched(in app application)
Create an Activity using the default `ChannelListFragment`
Created some channels.
Then click into the channel item, can send and receive message, but click the "attachment" button will cause a crash:
```
    android.view.InflateException: Binary XML file line #47 in com.myapp.test:layout/design_bottom_sheet_dialog: Could not inflate Behavior subclass com.google.android.material.bottomsheet.BottomSheetBehavior
    Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass com.google.android.material.bottomsheet.BottomSheetBehavior
        at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:649)
        at androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2896)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1740)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:112)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1128)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:684)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at android.view.View.inflate(View.java:27111)
        at com.google.android.material.bottomsheet.BottomSheetDialog.ensureContainerAndBehavior(BottomSheetDialog.java:273)
        at com.google.android.material.bottomsheet.BottomSheetDialog.wrapInBottomSheet(BottomSheetDialog.java:287)
        at com.google.android.material.bottomsheet.BottomSheetDialog.setContentView(BottomSheetDialog.java:148)
        at androidx.fragment.app.DialogFragment$4.onChanged(DialogFragment.java:158)
        at androidx.fragment.app.DialogFragment$4.onChanged(DialogFragment.java:143)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2974)
        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8061)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:647)
        at androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2896) 
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1740) 
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:112) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1128) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:684) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479) 
        at android.view.View.inflate(View.java:27111) 
        at com.google.android.material.bottomsheet.BottomSheetDialog.ensureContainerAndBehavior(BottomSheetDialog.java:273) 
        at com.google.android.material.bottomsheet.BottomSheetDialog.wrapInBottomSheet(BottomSheetDialog.java:287) 
        at com.google.android.material.bottomsheet.BottomSheetDialog.setContentView(BottomSheetDialog.java:148) 
        at androidx.fragment.app.DialogFragment$4.onChanged(DialogFragment.java:158) 
        at androidx.fragment.app.DialogFragment$4.onChanged(DialogFragment.java:143) 
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133) 
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151) 
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309) 
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2974) 
        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002) 
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8061) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f0400f5 a=15}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:599)
        at com.google.android.material.resources.MaterialResources.getColorStateList(MaterialResources.java:76)
        at com.google.android.material.bottomsheet.BottomSheetBehavior.<init>(BottomSheetBehavior.java:309)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:647) 
        at androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2896) 
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1740) 
        at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:112) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1128) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1086) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:684) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479) 
        at android.view.View.inflate(View.java:27111) 
        at com.google.android.material.bottomsheet.BottomSheetDialog.ensureContainerAndBehavior(BottomSheetDialog.java:273) 
        at com.google.android.material.bottomsheet.BottomSheetDialog.wrapInBottomSheet(BottomSheetDialog.java:287) 
        at com.google.android.material.bottomsheet.BottomSheetDialog.setContentView(BottomSheetDialog.java:148) 
        at androidx.fragment.app.DialogFragment$4.onChanged(DialogFragment.java:158) 
        at androidx.fragment.app.DialogFragment$4.onChanged(DialogFragment.java:143) 
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133) 
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151) 
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309) 
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2974) 
        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002) 
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8061) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)     
```

**Expected behavior**
Can open `AttachmentSelectionDialogFragment`

**Device:**
 - Vendor and model: [Xiaomi Mi9]
 - Android version: [11]

**Comment by bychkovdmitry** [comment]
Hello @yangkx1024,

Could you verify that you are using Material theme? Most of the libraries nowadays use attributes from the Material theme, so you need to use it in your application. You can find more information here:
https://getstream.io/chat/docs/sdk/android/ui/overview/#requirements

Alternatively, if you don't want to transition to the new Material theme, you can use one of the "bridge" themes. Your app will look just the same, but it won't crash when accessing attrs which can only be found in the Material theme.
https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md#bridge-themes

**Comment by yangkx1024** [comment]
Thanks, using `bridge theme` solved this problem.
