### ISSUE TITLE
java.io.EOFException logged via ChatLoggerHandler

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#2440]
**Describe the bug**
We implement and set our own ChatLoggerHandler like [sample.](https://github.com/GetStream/stream-chat-android/blob/main/stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/FirebaseLogger.kt#L7)
Then, this exception logged so many times in firebase console.
```
Non-fatal Exception: java.io.EOFException
       at okio.RealBufferedSource.require(RealBufferedSource.java:199)
       at okio.RealBufferedSource.readByte(RealBufferedSource.java:209)
       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:119)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:102)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:293)
       at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.java:195)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```
**SDK version**
- 4.18.0

**To Reproduce**
1. set ChatLoggerHandler
2. see Firebase Crashlytics console

**Device:**
 - all devices and android versions

**Screenshots**
### devices
![image](https://user-images.githubusercontent.com/7759511/136127039-73d9daa4-cb03-48c5-8722-be93c39dfdac.png)
### os
![image](https://user-images.githubusercontent.com/7759511/136127105-4bf910f6-c59d-4ce6-9c52-17bfa6d7e1f1.png)
### device state
![image](https://user-images.githubusercontent.com/7759511/136127192-c53a1729-8497-46b1-b381-468cdc3a6775.png)
### event count
![image](https://user-images.githubusercontent.com/7759511/136127328-95a67b92-f12a-4fb9-af13-14ee9a2cddd9.png)

**Comment by zsmb13** [comment]
Hey, thanks for reporting this.

At a glance, since this is a non-fatal exception, it might just be a normal thing that happens whenever the websocket connection is terminated (whenever the app goes into background, or is closed). We'll look into it to make sure though.

**Comment by adasiewiczr** [comment]
hey @workspace,
as mentioned before - this non-fatal exception happens whenever the websocket is closed and it shouldn't cause any problems.
The websocket connection is established after calling `ChatClient::connectUser` and it's used for real-time updates. Some information can be outdated if the connection is closed (for example unread count). However, all the information should be refreshed once the connection is restored.
Moreover, if the connection was established and if for some reason the connection was closed (for example app goes into the background), it should be automatically restored after a short time.
Let us know if you have any further questions.
