### ISSUE TITLE
Crash  synced Attachment

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#2458]
**Describe the bug**
crash saw in my firebase

```
Fatal Exception: java.lang.IllegalArgumentException: Logical error. Messages with non-synchronized attachments should have another sync status!
       at io.getstream.chat.android.offline.ChatDomainImpl.retryMessagesWithSyncedAttachments(ChatDomainImpl.kt:760)
       at io.getstream.chat.android.offline.ChatDomainImpl.access$retryMessagesWithSyncedAttachments(ChatDomainImpl.kt:133)
       at io.getstream.chat.android.offline.ChatDomainImpl$retryMessagesWithSyncedAttachments$1.invokeSuspend(:14)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**SDK version**
- 4.19.0

**Device:**
 - Vendor and model: Samsung Galaxy A51
 - Android version: 11

**Comment by ogkuzmin** [comment]
@spvince Hello!
We iterated over this, we're not going to crash anymore just added logging that will help us to solve the rootcause in the future. This will be available in our release this week
