### ISSUE TITLE
Serialization exception related with DownstreamMemberDto 

### ISSUE THREAD

**Issue by workspace** [GetStream/stream-chat-android#2460]
**Describe the bug**
```
com.squareup.moshi.JsonDataException: Required value 'user' missing at $.member
       at com.squareup.moshi.internal.Util.missingProperty(Util.java:649)
       at io.getstream.chat.android.client.api2.model.dto.DownstreamMemberDtoJsonAdapter.fromJson(DownstreamMemberDtoJsonAdapter.java:90)
       at io.getstream.chat.android.client.api2.model.dto.DownstreamMemberDtoJsonAdapter.fromJson(DownstreamMemberDtoJsonAdapter.java:25)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
       at io.getstream.chat.android.client.api2.model.dto.NotificationRemovedFromChannelEventDtoJsonAdapter.fromJson(NotificationRemovedFromChannelEventDtoJsonAdapter.java:63)
       at io.getstream.chat.android.client.api2.model.dto.NotificationRemovedFromChannelEventDtoJsonAdapter.fromJson(NotificationRemovedFromChannelEventDtoJsonAdapter.java:21)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
       at com.squareup.moshi.JsonAdapter.fromJsonValue(JsonAdapter.java:126)
       at io.getstream.chat.android.client.parser2.adapters.EventDtoAdapter.fromJson(EventDtoAdapter.java:190)
       at io.getstream.chat.android.client.parser2.adapters.EventDtoAdapter.fromJson(EventDtoAdapter.java:66)
       at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
       at io.getstream.chat.android.client.parser2.MoshiChatParser.parseAndProcessEvent(MoshiChatParser.java:137)
       at io.getstream.chat.android.client.parser2.MoshiChatParser.fromJson(MoshiChatParser.java:100)
       at io.getstream.chat.android.client.parser.ChatParser$DefaultImpls.fromJsonOrError(ChatParser.java:23)
       at io.getstream.chat.android.client.parser2.MoshiChatParser.fromJsonOrError(MoshiChatParser.java:41)
       at io.getstream.chat.android.client.socket.EventsParser.handleEvent(EventsParser.java:72)
       at io.getstream.chat.android.client.socket.EventsParser.onMessage(EventsParser.java:36)
       at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:333)
       at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:245)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:106)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:293)
       at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.java:195)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**SDK version**
- 4.18.0

**To Reproduce**
- Can't get detail from firebase crashlytics.

**Device:**
 - Galaxy A42 5G
 - Android version: 11

**Comment by adasiewiczr** [comment]
hey @workspace,
The issue will be fixed on the backend. We'll notify you once it's available
