### ISSUE TITLE
AttachmentGalleryActivity crashes with ArrayIndexOutOfBoundsException error

### ISSUE THREAD

**Issue by rupinderjeet** [GetStream/stream-chat-android#2487]
**Describe the bug**

7 occurrences on Crashlytics so far.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.onGalleryPageSelected(AttachmentGalleryActivity.kt:174)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity.access$onGalleryPageSelected(AttachmentGalleryActivity.kt:38)
       at io.getstream.chat.android.ui.gallery.AttachmentGalleryActivity$observePageChanges$1.onPageSelected(AttachmentGalleryActivity.kt:143)
       at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageSelected(CompositeOnPageChangeCallback.java:73)
       at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageSelected(CompositeOnPageChangeCallback.java:73)
       at androidx.viewpager2.widget.ScrollEventAdapter.dispatchSelected(ScrollEventAdapter.java:432)
       at androidx.viewpager2.widget.ScrollEventAdapter.onScrollStateChanged(ScrollEventAdapter.java:146)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5384)
       at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1618)
       at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3558)
       at androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl.onTouchEvent(ViewPager2.java:991)
       at android.view.View.dispatchTouchEvent(View.java:13478)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2810)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3129)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2824)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3129)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2824)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3129)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2824)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3129)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2824)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3129)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2824)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3129)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2824)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3129)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2824)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:496)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1868)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4003)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:454)
       at android.view.View.dispatchPointerEvent(View.java:13737)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5693)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5496)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4943)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4996)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4962)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4970)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4943)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4996)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4962)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5118)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4970)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5175)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4943)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4996)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4962)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4970)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4943)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7750)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7717)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7678)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7904)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:7557)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
```

**SDK version**
- 4.17.2

**To Reproduce**
> Crashlytics

**Expected behavior**
Issue is fixed, and my app doesn't crash.

**Device:**
 - Vendor and model: LG G8 ThinQ™
 - Android version: 10

**Screenshots**
No.

**Comment by adasiewiczr** [comment]
Hey @rupinderjeet,
do you have any more details about this issue?
