### ISSUE TITLE
App crashes on loading message screen

### ISSUE THREAD

**Issue by bibinkrishnan** [GetStream/stream-chat-android#2518]
App getting crash after loading message screen

**SDK version**
- 4.20.0

**_java.lang.NoSuchFieldError: No static field INSTANCE of type Lio/getstream/chat/android/client/models/Attachment$UploadState$InProgress; in class Lio/getstream/chat/android/client/models/Attachment$UploadState$InProgress; or its superclasses (declaration of 'io.getstream.chat.android.client.models.Attachment$UploadState$InProgress' appears in /data/app/~~a1n5G3m0zRbZ-bXv-jqIZg==/com.evero.android.digitalagency-OrtLPTlC32MgWAoMoi6Y5w==/base.apk!classes22.dex)
        at io.getstream.chat.android.ui.message.list.adapter.viewholder.internal.TextAndAttachmentsViewHolder.setupUploads(TextAndAttachmentsViewHolder.kt:101)
        at io.getstream.chat.android.ui.message.list.adapter.viewholder.internal.TextAndAttachmentsViewHolder.bindData(TextAndAttachmentsViewHolder.kt:79)
        at io.getstream.chat.android.ui.message.list.adapter.viewholder.internal.TextAndAttachmentsViewHolder.bindData(TextAndAttachmentsViewHolder.kt:30)
        at io.getstream.chat.android.ui.message.list.adapter.BaseMessageItemViewHolder.bindListItem$stream_chat_android_ui_components_release(BaseMessageItemViewHolder.kt:33)
        at io.getstream.chat.android.ui.message.list.adapter.internal.MessageListItemAdapter.onBindViewHolder(MessageListItemAdapter.kt:50)
        at io.getstream.chat.android.ui.message.list.adapter.internal.MessageListItemAdapter.onBindViewHolder(MessageListItemAdapter.kt:12)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:643)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)_**

**Comment by bibinkrishnan** [comment]
Not getting this issue after I updated to 4.21.0
