### ISSUE TITLE
Concurrent modification on removing member from channel

### ISSUE THREAD

**Issue by Chikrix** [GetStream/stream-chat-android#269]
When I try to remove a member from a channel, it throws the following error;
```
 Process: com.salesrabbit.android.sales.universal, PID: 27697
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.getstream.sdk.chat.rest.response.ChannelState.removeMemberById(ChannelState.java:182)
        at com.getstream.sdk.chat.model.Channel.handelMemberRemoved(Channel.java:908)
        at com.getstream.sdk.chat.rest.core.Client$1.onMemberRemoved(Client.java:256)
...
```
Ways to reproduce
- Login as different members to a channel on different devices
- Remove one member from the channel that is active (at least has posted something in the same chat session on the channel)
- Crashes all active members across all different device

**Comment by tbarbugli** [comment]
this one is clearly a high priority bug @elevenetc
