### ISSUE TITLE
Crash User with the userId:  has not been found"

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#2756]
**Describe the bug**
Crash seen in my crashlytics

**SDK version**
- 4.23.0

**Crash**

```
Fatal Exception: java.lang.IllegalArgumentException: User with the userId: `113914` has not been found
       at io.getstream.chat.android.offline.repository.builder.RepositoryFacadeBuilder$build$getUser$1.invokeSuspend(RepositoryFacadeBuilder.kt:61)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Device:**
 - Vendor and model: Redmi Note 10 5G
 - Android version: 10

**Comment by adasiewiczr** [comment]
hey @spvince,
the fix is available in the latest release (4.24.0). Check our [CHANGELOG](https://github.com/GetStream/stream-chat-android/blob/main/CHANGELOG.md#december-9th-2021---4240) for further details
