### ISSUE TITLE
GetStream sample app crash on start

### ISSUE THREAD

**Issue by savked** [GetStream/stream-chat-android#293]
Installed the latest sample app to test something and got this crash:

2019-11-08 15:14:45.607 31039-31105/io.getstream.chat.sdk E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
Process: io.getstream.chat.sdk, PID: 31039
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:399)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalArgumentException: No enum constant com.getstream.sdk.chat.enums.MessageStatus.received
at java.lang.Enum.valueOf(Enum.java:257)
at com.getstream.sdk.chat.enums.MessageStatus.valueOf(MessageStatus.java:3)
at com.getstream.sdk.chat.storage.converter.MessageStatusConverter.fromString(MessageStatusConverter.java:11)
at com.getstream.sdk.chat.storage.ChannelsDao_Impl.getChannels(ChannelsDao_Impl.java:623)
at com.getstream.sdk.chat.storage.Storage.getChannels(Storage.java:349)
at com.getstream.sdk.chat.storage.Storage$QueryTask.doInBackground(Storage.java:481)
at com.getstream.sdk.chat.storage.Storage$QueryTask.doInBackground(Storage.java:465)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
at java.lang.Thread.run(Thread.java:919)

**Comment by adrian09h** [comment]
@savked , Thanks for your reporting this issue.
The issue was occurred by `MessageStatus` and we have fixed it on master yesterday.(removed the enum)
Please try sample again.

**Comment by savked** [comment]
Issue fixed.
