### ISSUE TITLE
viewModel.sendMessage - java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.getstream.sdk.chat.rest.User.getId()' on a null object reference

### ISSUE THREAD

**Issue by savked** [GetStream/stream-chat-android#318]
Got a crash testing the custom MessageInput. Using the exact same example like from the https://github.com/GetStream/stream-chat-android/blob/master/docs/MessageList.md

Crash happens when I press the send button.

```
2019-11-20 12:00:54.313 25109-25109/de.tourlina.Tourlina.staging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.tourlina.Tourlina.staging, PID: 25109
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.getstream.sdk.chat.rest.User.getId()' on a null object reference
        at com.getstream.sdk.chat.rest.Message.preStorage(Message.java:310)
        at com.getstream.sdk.chat.storage.StreamStorage.insertMessageForChannel(StreamStorage.java:234)
        at com.getstream.sdk.chat.viewmodel.ChannelViewModel.sendMessage(ChannelViewModel.java:981)
        at de.tourlina.tourlina.chat.CustomMessageInputView.sendMessage(CustomMessageInputView.java:127)
        at de.tourlina.tourlina.chat.CustomMessageInputView.lambda$initBinding$0$CustomMessageInputView(CustomMessageInputView.java:83)
        at de.tourlina.tourlina.chat.-$$Lambda$CustomMessageInputView$a2vpbaqRIJDpSHY8VC7IcBh0d2c.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by adrian09h** [comment]
@savked  you mean https://github.com/GetStream/stream-chat-android/blob/master/docs/MessageInput.md#step-2-create-custommessageinputview ?

**Comment by savked** [comment]
Yes, excuse me.

**Comment by adrian09h** [comment]
Thanks for your reporting this bug. Will fix soon.

**Comment by savked** [comment]
After this is fixed, can we get a new release?

**Comment by adrian09h** [comment]
@savked I will inform you when new release lives. :)

**Comment by savked** [comment]
> @savked I will inform you when new release lives. :)

Thank you very much.
