### ISSUE TITLE
IllegalStateException crash

### ISSUE THREAD

**Issue by nrlquaker** [GetStream/stream-chat-android#3351]
**Describe the bug**
Crash in my firebase crashlytics.

```
Fatal Exception: java.lang.IllegalStateException: Can't handle io.getstream.chat.android.client.clientstate.UserStateService$UserStateEvent$UserUpdated@b62925c while being in state NotSet
       at io.getstream.chat.android.client.clientstate.UserStateService$fsm$1$1.invoke(UserStateService.kt:31)
       at io.getstream.chat.android.client.clientstate.UserStateService$fsm$1$1.invoke(UserStateService.kt:31)
       at io.getstream.chat.android.core.internal.fsm.FiniteStateMachine$sendEvent$1.invokeSuspend(FiniteStateMachine.kt:56)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(:1)
       at io.getstream.chat.android.core.internal.fsm.FiniteStateMachine.sendEvent(FiniteStateMachine.kt:49)
       at io.getstream.chat.android.client.clientstate.UserStateService.onUserUpdated(UserStateService.kt:8)
       at io.getstream.chat.android.client.ChatClient._init_$lambda-1(ChatClient.kt:139)
       at io.getstream.chat.android.client.ChatClient.$r8$lambda$4SW1X3ATXbq0z78M1PeFnMSpiTQ()
       at io.getstream.chat.android.client.ChatClient$$ExternalSyntheticLambda2.onEvent(:2)
       at io.getstream.chat.android.client.utils.observable.SubscriptionImpl.onNext(Subscriptions.kt:36)
       at io.getstream.chat.android.client.utils.observable.ChatEventsObservable.onNext(ChatEventsObservable.kt:30)
       at io.getstream.chat.android.client.utils.observable.ChatEventsObservable.access$onNext(ChatEventsObservable.kt:18)
       at io.getstream.chat.android.client.utils.observable.ChatEventsObservable$EventsMapper.onConnected(ChatEventsObservable.kt:90)
       at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$state$2$2.invoke(ChatSocketServiceImpl.kt:75)
       at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$state$2$2.invoke(ChatSocketServiceImpl.kt:75)
       at io.getstream.chat.android.client.socket.ChatSocketServiceImpl.callListeners$lambda-7$lambda-6$lambda-5(ChatSocketServiceImpl.kt:234)
       at io.getstream.chat.android.client.socket.ChatSocketServiceImpl.$r8$lambda$7Ojq6A_PsWy5uEUtc_avkjHWI70()
       at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$$ExternalSyntheticLambda0.run(:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7386)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**SDK version**
- 4.14.1

**Comment by filbabic** [comment]
HEy @nrlquaker !

Thanks for the report! Do you have any reproduction steps at hand maybe, that we can take a look at?

Also - the version of the SDK that you're using is fairly old - could you please update to [4.30.1](https://github.com/GetStream/stream-chat-android/releases/tag/v4.30.1), or [5.0.3](https://github.com/GetStream/stream-chat-android/releases/tag/v5.0.3) by following the migration guide here:
https://getstream.io/chat/docs/sdk/android/client/guides/chatdomain-migration/

And let me know if the issue persists?

**Comment by nrlquaker** [comment]
@filbabic thanks for the reply.
Unfortunately I don't have any simple repo with steps to reproduce. 
Will try to migrate to v5. Will notify if crash will persist.

**Comment by filbabic** [comment]
Hey there @nrlquaker !

Thank you - yeah we'd appreciate if you can upgrade and see if the issue persists. I'll forward the item to the Core team either way for investigation.

Thanks!
