### ISSUE TITLE
Crash at ChatDomain.Builder.build()

### ISSUE THREAD

**Issue by NitinPraksash9911** [GetStream/stream-chat-android#3465]
**Describe the bug**
We are getting ANR on Firebase while using. `ChatDomain.Builder(client, context)`

**SDK version**
Android SDK 30

**To Reproduce**
We are getting this ANR for random users

**Expected behavior**

**Device:**
 Brand:samsung
Model:Galaxy M21
Version:Android 11

**Crash Logs:**
`main (runnable): tid=1 systid=26759 
       at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
       at kotlin.reflect.jvm.internal.UtilKt.loadClass(UtilKt.java:84)
       at kotlin.reflect.jvm.internal.UtilKt.loadClass(UtilKt.java:80)
       at kotlin.reflect.jvm.internal.UtilKt.toJavaClass(UtilKt.java:72)
       at kotlin.reflect.jvm.internal.KTypeImpl.convert(KTypeImpl.java:54)
       at kotlin.reflect.jvm.internal.KTypeImpl.access$convert(KTypeImpl.java:38)
       at kotlin.reflect.jvm.internal.KTypeImpl$classifier$2.invoke(KTypeImpl.java:49)
       at kotlin.reflect.jvm.internal.KTypeImpl$classifier$2.invoke(KTypeImpl.java:38)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
       at kotlin.reflect.jvm.internal.KTypeImpl.getClassifier(KTypeImpl.java:1)
       at kotlin.reflect.TypesJVMKt.computeJavaType(TypesJVMKt.java:38)
       at kotlin.reflect.TypesJVMKt.getJavaType(TypesJVMKt.java:90)
       at kotlin.reflect.TypesJVMKt.createPossiblyInnerType(TypesJVMKt.java:69)
       at kotlin.reflect.TypesJVMKt.computeJavaType(TypesJVMKt.java:60)
       at kotlin.reflect.TypesJVMKt.computeJavaType$default(TypesJVMKt.java:37)
       at kotlin.reflect.TypesJVMKt.getJavaType(TypesJVMKt.java:33)
       at com.squareup.moshi._MoshiKotlinExtensionsKt.adapter(_MoshiKotlinExtensionsKt.java:40)
       at io.getstream.chat.android.offline.repository.database.converter.MapConverter.<init>(MapConverter.java:71)
       at io.getstream.chat.android.offline.repository.domain.message.MessageDao_Impl.<init>(MessageDao_Impl.java:59)
       at io.getstream.chat.android.offline.repository.database.ChatDatabase_Impl.messageDao(ChatDatabase_Impl.java:507)
       at io.getstream.chat.android.offline.repository.builder.RepositoryFacadeBuilder.createDatabase(RepositoryFacadeBuilder.java:42)
       at io.getstream.chat.android.offline.repository.builder.RepositoryFactory.createMessageRepository(RepositoryFactory.java:42)
       at io.getstream.chat.android.offline.repository.builder.RepositoryFacadeBuilder.build(RepositoryFacadeBuilder.java:64)
       at io.getstream.chat.android.offline.ChatDomainImpl.createNoOpRepos(ChatDomainImpl.java:1065)
       at io.getstream.chat.android.offline.ChatDomainImpl.<init>(ChatDomainImpl.java:185)
       at io.getstream.chat.android.offline.ChatDomain$Builder.buildImpl$stream_chat_android_offline_release(ChatDomain.java:757)
       at io.getstream.chat.android.offline.ChatDomain$Builder.build(ChatDomain.java:737)
       at io.getstream.chat.android.livedata.ChatDomain$Builder.build(ChatDomain.java:701)
       at app.geochat.common.getstream.ChatInitializer.init(ChatInitializer.java:49)
       at app.geochat.revamp.application.Trell.onCreate(Trell.java:206)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7573)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

**Comment by amitkma** [comment]
@NitinPraksash9911 We have recently released v5+ of our SDK. Could you please update to the latest version and let us know if the problem still persists?

**Comment by NitinPraksash9911** [comment]
@amitkma Thanks man, lemme check this with my team

**Comment by amitkma** [comment]
@NitinPraksash9911 Did you migrate to v5? Or are you still facing this issue?.
