### ISSUE TITLE
Coil 2.0 breaks stream-chat-android 5.2.0

### ISSUE THREAD

**Issue by julioromano** [GetStream/stream-chat-android#3527]
**Describe the bug**
Upgrading to Coil 2.0 in a project using stream-chat-android 5.2.0 crashes the app whenever loading the Stream SDK UI.

**Expected behavior**
The stream SDK shouldn't prevent projects from upgrading to Coil 2.0

Stack trace:
```
    java.lang.IllegalStateException: Unsupported
        at coil.util.-Utils.unsupported(Utils.kt:227)
        at coil.ImageLoader$Builder.availableMemoryPercentage(ImageLoader.kt:538)
        at com.getstream.sdk.chat.coil.StreamImageLoaderFactory.newImageLoader(StreamImageLoaderFactory.kt:37)
        at io.getstream.chat.android.compose.ui.util.DefaultStreamCoilImageLoaderFactory.newImageLoader(DefaultStreamCoilImageLoader.kt:82)
        at io.getstream.chat.android.compose.ui.util.DefaultStreamCoilImageLoaderFactory.imageLoader(DefaultStreamCoilImageLoader.kt:69)
        at io.getstream.chat.android.compose.ui.theme.ChatThemeKt.ChatTheme(ChatTheme.kt:139)
```

**Comment by mvm219** [comment]
Please fix coil code in `com.getstream.sdk.chat.coil.StreamImageLoaderFactory` like following

```
public class StreamImageLoaderFactory(
    private val context: Context,
    private val builder: ImageLoader.Builder.() -> Unit = {}
) : ImageLoaderFactory {
    override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(context)
            .allowHardware(false)
            .crossfade(true)
            .memoryCache {
                MemoryCache.Builder(context)
                    .maxSizePercent(0.25)
                    .build()
            }
            .diskCache {
                DiskCache.Builder()
                    .directory(context.cacheDir.resolve("image_cache"))
                    .maxSizePercent(0.02)
                    .build()
            }
            .okHttpClient {
                val cacheControlInterceptor = Interceptor { chain ->
                    chain.proceed(chain.request())
                        .newBuilder()
                        .header("Cache-Control", "max-age=3600,public")
                        .build()
                }
                // Don't limit concurrent network requests by host.
                val dispatcher = Dispatcher().apply { maxRequestsPerHost = maxRequests }

                OkHttpClient.Builder()
                    .dispatcher(dispatcher)
                    .addNetworkInterceptor(cacheControlInterceptor)
                    .build()
            }.components {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                    add(ImageDecoderDecoder.Factory(enforceMinimumFrameDelay = true))
                } else {
                    add(GifDecoder.Factory(enforceMinimumFrameDelay = true))
                }
            }
            .apply(builder)
            .build()
    }
}
```

**Comment by JcMinarro** [comment]
Hello @mvm219 
Coil has been already upgrade (#3538) and will be ready on the following release

**Comment by filbabic** [comment]
Closing this issue as we've released a version with the fix!
