### ISSUE TITLE
MessageListViewStyle.attachmentTitleTextTheirs - NullPointerException

### ISSUE THREAD

**Issue by savked** [GetStream/stream-chat-android#360]
Trying to solve the issue #335 and implementing the solution @adrian09h gave me, but got this crash from that code:

2019-12-04 09:30:29.778 1865-1865/de.tourlina.Tourlina.staging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.tourlina.Tourlina.staging, PID: 1865
    java.lang.NullPointerException: Attempt to read from field 'com.getstream.sdk.chat.style.TextStyle com.getstream.sdk.chat.view.MessageListViewStyle.attachmentTitleTextTheirs' on a null object reference
        at com.getstream.sdk.chat.adapter.AttachmentViewHolder.applyStyle(AttachmentViewHolder.java:226)
        at com.getstream.sdk.chat.adapter.AttachmentViewHolder.bind(AttachmentViewHolder.java:56)
        at com.getstream.sdk.chat.adapter.AttachmentListItemAdapter.onBindViewHolder(AttachmentListItemAdapter.java:68)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1654)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9322)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1615)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:587)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1654)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
2019-12-04 09:30:29.779 1865-1865/de.tourlina.Tourlina.staging E/AndroidRuntime:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
        at android.view.View.layout(View.java:21927)
        at android.view.ViewGroup.layout(ViewGroup.java:6260)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3080)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2590)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by adrian09h** [comment]
@savked , just checkout your stack trace in detail, atm I have found a problem in there.

![image](https://user-images.githubusercontent.com/11132956/70127759-f4ad2d80-167b-11ea-9b29-d7c5783f0f6a.png)

You created `AttachmentListViewHolderCustom` for your attachment type `I18N_TYPE`
But why does it calls `AttachmentViewHolder` instead your custom attachment view holder?

I have checked the solution first, and introduced to you yesterday.
I'd like you to check your code again if you are following correctly my solution.  ;)

**Comment by savked** [comment]
I am not using the `AttachmentViewHolder` anywhere, you can see here that I am using the `AttachmentViewHolderCustom` here:

        @Override
        public BaseAttachmentViewHolder createAttachmentViewHolder(AttachmentListItemAdapter adapter, ViewGroup parent, int viewType) {
            BaseAttachmentViewHolder holder;
            if (viewType == I18N_TYPE) {
                holder = new AttachmentViewHolderCustom(R.layout.chat_custom_attachment, parent);
            } else {
                holder = super.createAttachmentViewHolder(adapter, parent, viewType);
            }
            return holder;
        }

Just like the code you gave me.

**Comment by adrian09h** [comment]
@savked I have updated code example for `CustomMessageListViewHolder`.
https://github.com/GetStream/stream-chat-android/issues/335#issuecomment-561339775

Please read again.

**Comment by adrian09h** [comment]
@savked , please refer [this](https://github.com/GetStream/stream-chat-android/blob/update/readme-message-list/docs/MessageList.md#customizing-the-message-item-view-with-your-own-layout-file) for your customizing viewholders.
