### ISSUE TITLE
SDK crashes when app returns empty string as token

### ISSUE THREAD

**Issue by JayMehta97** [GetStream/stream-chat-android#3651]
**Describe the bug**
When a user starts our app, we call the backend to generate chat token for that user, in a case where user is not allowed to use chat the API returns error and the app returns an empty string to the stream `loadToken` method of `TokenProvider`. This scenario worked perfectly fine in 4.x.x versions but recently we upgraded to 5.x.x and now the app crashes on start.

Crash log:
```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.vahvah.android.app.vv_chat, PID: 26740
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.Collections$SingletonList.get(Collections.java:4872)
        at io.getstream.chat.android.client.utils.TokenUtils.getUserId(TokenUtils.kt:31)
        at io.getstream.chat.android.client.ChatClient.setUser(ChatClient.kt:309)
        at io.getstream.chat.android.client.ChatClient.access$setUser(ChatClient.kt:163)
        at io.getstream.chat.android.client.ChatClient$connectUser$1.invokeSuspend(ChatClient.kt:384)
        at io.getstream.chat.android.client.ChatClient$connectUser$1.invoke(Unknown Source:8)
        at io.getstream.chat.android.client.ChatClient$connectUser$1.invoke(Unknown Source:4)
        at io.getstream.chat.android.client.call.CoroutineCall$enqueue$1.invokeSuspend(CoroutineCall.kt:52)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f887121, Dispatchers.IO]
```

**SDK version**
- 5.3.1

**To Reproduce**
1. Return empty string in stream `loadToken` method of `TokenProvider`

**Expected behavior**
Should not crash

**Device:**
 - Vendor and model: Vivo Y12s (V2033)
 - Android version: 11

**Comment by JcMinarro** [comment]
Hello @JayMehta97 
It is due to an internal check we do to verify the userId and the token belong to the same user, and an empty JWT token doesn't contain it.
BTW, our SDK shouldn't crash because it, should provide a proper error notifying it.
Let me fix it

**Comment by JcMinarro** [comment]
Hi @JayMehta97 
We already fixed it and published a new version of our SDK.
Let us know if it works fine for you now.
