### ISSUE TITLE
NullPointerException:  'java.util.HashMap com.getstream.sdk.chat.enums.FilterObject.getData()'

### ISSUE THREAD

**Issue by Chikrix** [GetStream/stream-chat-android#385]
I get the following error randomly in my chat detail *fragment* when it returns from the background on process death. 

**How to reproduce**
- Enable *Do not keep activities*
- Open the channel conversation detail fragment
- Go Home so the app is pushed to background
- Open the application again (should resume in the channel detail conversation)
- Wait a while while still on the screen, app crashes with the following
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.HashMap com.getstream.sdk.chat.enums.FilterObject.getData()' on a null object reference
        at com.getstream.sdk.chat.enums.FilterObjectAdapter.write(FilterObjectAdapter.java:19)
        at com.getstream.sdk.chat.enums.FilterObjectAdapter.write(FilterObjectAdapter.java:15)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
        at com.google.gson.Gson.toJson(Gson.java:704)
        at com.google.gson.Gson.toJson(Gson.java:683)
        at com.google.gson.Gson.toJson(Gson.java:638)
        at com.google.gson.Gson.toJson(Gson.java:618)
        at com.getstream.sdk.chat.rest.core.Client$5.onSuccess(Client.java:761)
        at com.getstream.sdk.chat.rest.core.Client.onSetUserCompleted(Client.java:572)
        at com.getstream.sdk.chat.rest.core.Client.queryChannels(Client.java:758)
        at com.getstream.sdk.chat.viewmodel.ChannelListViewModel.queryChannelsInner(ChannelListViewModel.java:528)
        at com.getstream.sdk.chat.viewmodel.ChannelListViewModel.access$300(ChannelListViewModel.java:39)
        at com.getstream.sdk.chat.viewmodel.ChannelListViewModel$4.onConnectionRecovered(ChannelListViewModel.java:276)
        at com.getstream.sdk.chat.rest.core.ChatEventHandler.dispatchEvent(ChatEventHandler.java:202)
        at com.getstream.sdk.chat.rest.core.Client.onWSEvent(Client.java:648)
        at com.getstream.sdk.chat.rest.core.Client$4.onSuccess(Client.java:714)
        at com.getstream.sdk.chat.rest.core.Client.connectionResolved(Client.java:626)
        at com.getstream.sdk.chat.rest.StreamWebSocketService$EchoWebSocketListener.lambda$onMessage$3$StreamWebSocketService$EchoWebSocketListener(StreamWebSocketService.java:332)
        at com.getstream.sdk.chat.rest.-$$Lambda$StreamWebSocketService$EchoWebSocketListener$UbJWkzANTmTbVNGfPJ0Es9LKSGk.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by Chikrix** [comment]
Would be great if this issue can be addressed or at least acknowledged, so I know what my problem really is. This is the most common crash on my app.

**Comment by tschellenbach** [comment]
I recommend using the 4.x branch.
