### ISSUE TITLE
CAS-81: App crashes on attaching photo or video

### ISSUE THREAD

**Issue by Chikrix** [GetStream/stream-chat-android#403]
In the chat detail, clicking on the **"Upload a photo or video"** option when trying to attach a file to a conversation throws the error. I'm using version 3.6.1, my target sdk version is 29. I've noticed the error on devices running Android 10 
```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask 
    java.lang.IllegalArgumentException: Invalid column resolution
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.getstream.sdk.chat.utils.Utils.getMediaAttachments(Utils.java:226)
        at com.getstream.sdk.chat.utils.MessageInputController.getAttachmentsFromLocal(MessageInputController.java:183)
        at com.getstream.sdk.chat.utils.MessageInputController.configSelectAttachView(MessageInputController.java:164)
        at com.getstream.sdk.chat.utils.MessageInputController.lambda$onClickOpenSelectView$5$MessageInputController(MessageInputController.java:310)
        at com.getstream.sdk.chat.utils.-$$Lambda$MessageInputController$v0Qk8BORwmsngO6TsPKo64HGs2E.run(Unknown Source:4)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by andriizhumela** [comment]
@Chikrix Thanks for your reply. I'll check it as soon as I can.
