### ISSUE TITLE
ImagePreviewActivity: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by cvb941** [GetStream/stream-chat-android#4086]
**Describe the bug**
Tapping on an image preview in a message causes the following crash:
```
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.getstream.chat.android.compose.ui.attachments.preview.ImagePreviewActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3752)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3926)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2275)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8213)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
                                                                                                    Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:930)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:893)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:785)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:208)
                                                                                                    	at androidx.activity.compose.ComponentActivityKt.setContent(ComponentActivity.kt:68)
                                                                                                    	at androidx.activity.compose.ComponentActivityKt.setContent$default(ComponentActivity.kt:49)
                                                                                                    	at io.getstream.chat.android.compose.ui.attachments.preview.ImagePreviewActivity.onCreate(ImagePreviewActivity.kt:158)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8241)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8207)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3725)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3926) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2275) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8213) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
```

**SDK version**
- 5.8.1

**To Reproduce**
1. Send a message containing an image.
2. Tap on the image preview.

**Device:**
 - Vendor and model: Poco F4
 - Android version: 12

**Comment by bychkovdmitry** [comment]
Hello @cvb941 

Thanks for reaching out. Could you tell us the parent theme you use for your application?

**AndroidManifest.xml**
```
    <application
        ...
        android:theme="@style/Theme.YourAppTheme"
        >

```

**themes.xml**
```
<resources>
    <style name="Theme.YourAppTheme" parent="Theme.MaterialComponents.DayNight.NoActionBar">
     ...
    </style>
</resources>
```

Thanks!

**Comment by cvb941** [comment]
```
  <application
        android:theme="@style/Theme.Obv.Splash"
```

```
 <style name="Theme.Obv" parent="Theme.Material3.DayNight.NoActionBar">
    </style>

    <style name="Theme.Obv.Splash" parent="Theme.SplashScreen">
             <item name="postSplashScreenTheme">@style/Theme.Obv</item>
    </style>
```

The problem persists even if I switch `Theme.Material3.DayNight.NoActionBar` to `Theme.AppCompat.DayNight.NoActionBar`

**Comment by bychkovdmitry** [comment]
What about your code, as far as I know themes in Android don't have multiple inheritance. 
```
<style name="Theme.Obv.Splash" parent="Theme.SplashScreen">
    <item name="postSplashScreenTheme">@style/Theme.Obv</item>
</style>
```
This means that you are explicitly extending from `Theme.SplashScreen` instead of `Theme.Obv`. So, would be nice to check the parent of `Theme.SplashScreen`.


Our embedded activities don't have their own themes and rely on the inherited application theme. We recommend using `Theme.MaterialComponents` as your app theme or if you are still using `AppCompat` you can inherit `Theme.MaterialComponents.Bridge` without any side effects. You can read more about bridge themes [here](https://material.io/develop/android/docs/getting-started#bridge-themes). 


As a workaround we can suggest forcing material theme for our `ImagePreviewActivity`:

```kotlin
<activity
     android:name="io.getstream.chat.android.compose.ui.attachments.preview.ImagePreviewActivity"
      android:theme="@style/Theme.MaterialComponents.DayNight.NoActionBar"
      tools:replace="android:theme"  />
```
Let us know if this workaround works for you.

In the meantime we will work on specifying `ImagePreviewActivity` theme explicitly in our SDK so that it doesn't depend on the application theme.

**Comment by cvb941** [comment]
Our setup comes from the [AndroidX splash screen library](https://developer.android.com/develop/ui/views/launch/splash-screen/migrate), so I guess a lot of other people will face the same issue too.

I will try the workaround in the meantime, thanks!

**Comment by cvb941** [comment]
The workaround is working.

**Comment by bychkovdmitry** [comment]
We also have another Activity in Compose responsible for video preview. I suppose that you'll need to apply the workaround for it as well:
```
<activity
     android:name="io.getstream.chat.android.compose.ui.attachments.preview.MediaPreviewActivity"
      android:theme="@style/Theme.MaterialComponents.DayNight.NoActionBar"
      tools:replace="android:theme"  />
```

I created a [task](https://github.com/GetStream/stream-chat-android/issues/4091) for us to specify themes explicitly for the Activities we ship with our SDK. We will schedule it for one of our next sprints. 

So, if the workaround is working then I'm closing the ticket for now. Feel free to reopen if have more questions. Thanks
