### ISSUE TITLE
TokenProvider does not actually refresh the token

### ISSUE THREAD

**Issue by remvst** [GetStream/stream-chat-android#4387]
**Describe the bug**
`TokenProvider` is injected through `connectUser()`, queries the token, then doesn't refresh once the token has expired.

**SDK version**
- 5.11.2

**To Reproduce**
1. set up a backend with a short token expiry
2. call `connectUser()` with a `TokenProvider`
3. wait for the token to expire
4. exceptions in the logs start showing:

```
2022-11-09 14:39:02.006 26771-27201 Chat:Events             xxx             E  (OkHttp https://chat.stream-io-api.com/...:213) [onSocketError] closedByClient: false, error: ChatNetworkError http status -1, stream error code 1003: See stack trace in logs. Intercept error in error handler of setUser
2022-11-09 14:39:02.006 26771-27201 Chat:Socket             xxx             E  (OkHttp https://chat.stream-io-api.com/...:213) [onSocketError] error: ChatNetworkError http status -1, stream error code 1003: See stack trace in logs. Intercept error in error handler of setUser
2022-11-09 14:39:02.006 26771-27201 Chat:Socket             xxx             E  (OkHttp https://chat.stream-io-api.com/...:213) ChatNetworkError http status -1, stream error code 1003: See stack trace in logs. Intercept error in error handler of setUser
2022-11-09 14:39:02.006 26771-27201 Chat:Socket             xxx             E  (OkHttp https://chat.stream-io-api.com/...:213) [onChatNetworkError] error: ChatNetworkError http status -1, stream error code 1003: See stack trace in logs. Intercept error in error handler of setUser
2022-11-09 14:39:03.652 26771-27201 Chat:Events             xxx             E  (OkHttp https://chat.stream-io-api.com/...:213) [onFailure] throwable: java.io.EOFException
                                                                                                    java.io.EOFException
                                                                                                    	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
                                                                                                    	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
                                                                                                    	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
                                                                                                    	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

This keeps throwing over and over again until I call `disconnect()` then `connect()` again.

**Expected behavior**

Once the token is expired, `loadToken()` should be called again and connection to the websocket should be re-established using the new token.

Funnily enough I am able to send and receive messages but I don't receive "is typing..." events.

**Device:**
 - Vendor and model: Google Pixel 3 XL
 - Android version: Android 12
 
FWIW I think we're seeing the same issue on the iOS side, so maybe it's not a client issue.

**Comment by remvst** [comment]
Was able to fix it. Turns out I hadn't disabled dev tokens yet. Disabling them now makes the SDK request new tokens periodically (as expected).

![Screen Shot 2022-11-09 at 3 05 27 PM](https://user-images.githubusercontent.com/3472387/200930173-0e3eaf10-7199-4154-92f0-0488944294a8.png)

I'm going to close this, but it'd be really nice if that could be addressed, either on the client SDK, or on backend :)
