### ISSUE TITLE
Crash on connection

### ISSUE THREAD

**Issue by maxmaxandr** [GetStream/stream-chat-android#456]
HI,
 I've got the crash on release version 
`
io.getstream.chat.android.client.events.ConnectedEvent.getMe (ConnectedEvent.java:2)
io.getstream.chat.android.client.ChatClientImpl$1.invoke (ChatClientImpl.java:9)
io.getstream.chat.android.client.utils.observable.Subscription.deliver (Subscription.java:25)
io.getstream.chat.android.client.utils.observable.Subscription.b (Subscription.java:10)
io.getstream.chat.android.client.utils.observable.ChatObservableImpl.a (ChatObservableImpl.java:20)
io.getstream.chat.android.client.utils.observable.ChatObservableImpl$EventsMapper.a (ChatObservableImpl.java:4)
io.getstream.chat.android.client.socket.ChatSocketServiceImpl$updateState$3.run (ChatSocketServiceImpl.java:5)
-$$LambdaGroup$js$RX1rnaNIto64id03va9ghydZHnA.run (-.java:5)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:7811)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)

`
but it works on debug version of application.

**Comment by elevenetc** [comment]
Thanks for report. It seems you cut first line of stacktrace with exception, could you check it? Most probably it is NPE, but want to make sure.

**Comment by maxmaxandr** [comment]
> Thanks for report. It seems you cut first line of stacktrace with exception, could you check it? Most probably it is NPE, but want to make sure.

`
Fatal Exception: i.n: lateinit property me has not been initialized
       at io.getstream.chat.android.client.events.ConnectedEvent.getMe(ConnectedEvent.java:2)
       at io.getstream.chat.android.client.ChatClientImpl$1.invoke(ChatClientImpl.java:9)
       at io.getstream.chat.android.client.utils.observable.Subscription.deliver(Subscription.java:25)
       at io.getstream.chat.android.client.utils.observable.Subscription.b(Subscription.java:10)
       at io.getstream.chat.android.client.utils.observable.ChatObservableImpl.a(ChatObservableImpl.java:20)
       at io.getstream.chat.android.client.utils.observable.ChatObservableImpl$EventsMapper.a(ChatObservableImpl.java:4)
       at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$updateState$3.run(ChatSocketServiceImpl.java:5)
       at -$$LambdaGroup$js$RX1rnaNIto64id03va9ghydZHnA.run(-.java:5)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7811)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
`

**Comment by tbarbugli** [comment]
@maxmaxandr can you still reproduce this problem from your end? if yes can you share the version you are using on your project?

**Comment by JcMinarro** [comment]
`ConnectedEvent.me` is a property that could be init a posteriory by the backend, you need to check `ConnectedEvent.isValid()` before to access to this property
