### ISSUE TITLE
App crashes when add Ok2Curl dependency

### ISSUE THREAD

**Issue by nrlquaker** [GetStream/stream-chat-android#4582]
**Describe the bug**
After adding [Ok2Curl](https://github.com/mrmike/Ok2Curl) dependency to project, app crashes.
I don't use custom custom OkHttpClient.

```
val logLevel = if (BuildConfig.DEBUG) ChatLogLevel.ALL else ChatLogLevel.NOTHING
val client = ChatClient.Builder(apiKey, context)
    .loggerHandler(FirebaseLogger)
    .logLevel(logLevel)
    .build()
```

**SDK version**
- 4.30.1

**To Reproduce**
1. Add `implementation 'com.github.mrmike:ok2curl:0.8.0'` to build.gradle
2. Build and run the app.
3. See crash

**Expected behavior**
Adding dependency should not cause app to crash.

**Device:**
 - Vendor and model: Samsung Tab S6 Lite
 - Android version: 12

**Log:**
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/moczul/ok2curl/logger/Loggable;
    at io.getstream.chat.android.client.ChatClient$Builder.internalBuild(ChatClient.kt:1993)
    at io.getstream.chat.android.client.ChatClient$ChatClientBuilder.build(ChatClient.kt:2026)
    at ChatInitializer.init(ChatInitializer.kt:31)
    at App.onCreate(App.kt:153)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1229)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7698)
    at android.app.ActivityThread.access$1800(ActivityThread.java:324)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8855)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.moczul.ok2curl.logger.Loggable" on path: DexPathList
```

**Comment by filbabic** [comment]
Hey @nrlquaker !

Unfortunately we no longer support active development and improvements on v4. We recommend migrating to v5 as soon as possible and in the meantime, that could resolve the dependency issue you might have.

If it doesn't we can look into the issue again.
