### ISSUE TITLE
Crash with events  new member added

### ISSUE THREAD

**Issue by maxmaxandr** [GetStream/stream-chat-android#459]
When a new member added in the channel I got a crash with casting types.

`
I/Chat:ChatDomain QueryChannelsController: received channel event ChatEvent(type='member.added')
I/ChatDomain: ChatDomain: The channels changed
   
    
--------- beginning of a crash
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.witley, PID: 16682
    java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to io.getstream.chat.android.client.models.Member
        at io.getstream.chat.android.livedata.entity.ChannelEntity.<init>(ChannelEntity.kt:73)
        at io.getstream.chat.android.livedata.EventHandlerImpl.handleEventsInternal$library_release(EventHandlerImpl.kt:170)
        at io.getstream.chat.android.livedata.EventHandlerImpl$handleEventsInternal$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

`

**Comment by tschellenbach** [comment]
which version are you on? 1.4.1 of the LLC had some issues.

**Comment by tschellenbach** [comment]
Closing this, pretty confident it's fixed in the latest version
