### ISSUE TITLE
IncompatibleClassChangeError due to conflicting KeyboardVisibilityEvent library versions

### ISSUE THREAD

**Issue by maxkohne** [GetStream/stream-chat-android#4682]
**Description**
Our app is using the same library as `GetStream` to detect keyboard events, [KeyboardVisibilityEvent](https://github.com/yshrsmz/KeyboardVisibilityEvent). We are currently using the latest version `v3.0.0-RC3` within our app. According to the [source code](https://github.com/GetStream/stream-chat-android/blob/ad5f2893f3dfb7d13e50e4b24969bda7fcf90617/buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt#L51), `GetStream` is using `2.3.0`.

Because of the difference in versions, our app crashes when the keyboard is opened when a `MessageInputView` is tapped with the following stacktrace:

```
java.lang.IncompatibleClassChangeError: The method 'net.yslibrary.android.keyboardvisibilityevent.Unregistrar net.yslibrary.android.keyboardvisibilityevent.KeyboardVisibilityEvent.registerEventListener(android.app.Activity, net.yslibrary.android.keyboardvisibilityevent.KeyboardVisibilityEventListener)' was expected to be of type static but instead was found to be of type virtual (declaration of 'io.getstream.chat.android.ui.message.input.MessageInputView' appears in /data/app/~~J8-Z7sd2P6e5fI4Te2f22g==/[app_id]-EfVGRAIES8Ww8B3dJjLnrg==/base.apk!classes7.dex)
    at io.getstream.chat.android.ui.message.input.MessageInputView.registerKeyboardListener(MessageInputView.kt:875)
    at io.getstream.chat.android.ui.message.input.MessageInputView.configTextInput$lambda-30(MessageInputView.kt:836)
    at io.getstream.chat.android.ui.message.input.MessageInputView.$r8$lambda$7bDLL2Kw1npGTCzAD2FsvfcgRBM(Unknown Source:0)
    at io.getstream.chat.android.ui.message.input.MessageInputView$$ExternalSyntheticLambda11.onFocusChange(Unknown Source:2)
    at android.view.View.onFocusChanged(View.java:8174)
    at android.widget.TextView.onFocusChanged(TextView.java:11334)
    at android.view.View.handleFocusGainInternal(View.java:7844)
    at android.view.View.requestFocusNoSearch(View.java:13954)
    at android.view.View.requestFocus(View.java:13928)
    at android.view.View.requestFocus(View.java:13895)
    at android.view.View.requestFocus(View.java:13837)
    at android.view.View.onTouchEvent(View.java:16420)
    at android.widget.TextView.onTouchEvent(TextView.java:11444)
```

Would it be possible for GetStream to bump the keyboard library to the latest version?

**SDK version**
- 5.12.0

**To Reproduce**
1. Make a new project and import the [KeyboardVisibilityEvent](https://github.com/yshrsmz/KeyboardVisibilityEvent) with the latest version `v3.0.0-RC2` as well as importing `GetStream v5.12.0`
2. Click on a `MessageInputView` and the app crashes

**Comment by filbabic** [comment]
Hey @maxkohne!

Unfortunately, that's not a stable version or release so this is not really a bug. We cannot push transitive dependencies up to RC/high beta in our SDK as that's forcing all of our customers to do the same, and RCs don't necessarily mean it's well and stable.

Just look at some more popular RC and stable releases, like Compose 1.2 (which had to have an urgent 1.2.1 push) or Kotlin 1.8. Those introduced quite major changes in code, syntax, even semantics, but weren't stable and required a day one patch essentially to fix the issues. Because of that we have to be wary of when we push for higher releases.

We definitely suggest that you keep using an earlier major stable rather than RC and we'll update to 3.x.x accordingly, once it's out as stable!

Given that I'm not really able to provide more support her, I'll close this issue/bug, but I'll open up an internal (still publically visible) ticket to update to latest KeyboardVisibilityEvent library.

Hope this makes sense and you understand!

Thank you so much ^^
