### ISSUE TITLE
NotificationPermissionManager crashing

### ISSUE THREAD

**Issue by javier-delgado** [GetStream/stream-chat-android#4710]
**Describe the bug**
When trying to initialize the SDK with firebase notifications, it tries to request permissions for notifications but it crashes with the following error
```
java.lang.IllegalStateException: Attempting to launch an unregistered ActivityResultLauncher with contract androidx.activity.result.contract.ActivityResultContracts$RequestPermission@fc43582 and input android.permission.POST_NOTIFICATIONS. You must ensure the ActivityResultLauncher is registered before calling launch().
at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:168)
at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
at io.getstream.chat.android.client.notifications.permissions.NotificationPermissionManagerImpl.requestPermission(NotificationPermissionManagerImpl.kt:171)
at io.getstream.chat.android.client.notifications.permissions.NotificationPermissionManagerImpl.requestPermissionIfPossible(NotificationPermissionManagerImpl.kt:148)
at io.getstream.chat.android.client.notifications.permissions.NotificationPermissionManagerImpl.start$lambda-3(NotificationPermissionManagerImpl.kt:71)
at io.getstream.chat.android.client.notifications.permissions.NotificationPermissionManagerImpl.$r8$lambda$Xtcks5Uf1ekngTyu50exWrPSPAM(Unknown Source:0)
at io.getstream.chat.android.client.notifications.permissions.NotificationPermissionManagerImpl$$ExternalSyntheticLambda2.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

This error does not happen if the app already has notification permission enabled.

**SDK version**
- 5.13.0

**To Reproduce**
Initialize the SDK using an integration with firebase having the permission for notifications disabled.

**Device:**
 - Emulator pixel 2
 - Tiramisu (API 33)

**Comment by JcMinarro** [comment]
Let us investigate this issue.
In the meantime, you can disable this behavior on the `NotificationConfig`:

```
val notificationConfig = NotificationConfig(
            pushDeviceGenerators = listOf(
                FirebasePushDeviceGenerator()
            ),
            requestPermissionOnAppLaunch = { false }
        )
```

**Comment by javier-delgado** [comment]
I figured that the error was caused because I didn't have `android.permission.POST_NOTIFICATIONS` declared in my manifest, so it works now. Maybe a better error message would be a nice addition.
Thanks for the help
