### ISSUE TITLE
ANR DistinctCall.kt line 52

### ISSUE THREAD

**Issue by Energizz** [GetStream/stream-chat-android#4753]
**Describe the bug**
ANR when trying to start/see conversation

**SDK version**
io.getstream:stream-chat-android-ui-components:5.11.4
io.getstream:stream-chat-android-pushprovider-firebase:5.11.4

**To Reproduce**
Data get from crashlytics with random users

**Device:**
- Vivo (V2110)
- Vivo (Y21A)
- Vivo (1904)
- Oppo (Realme Q3 Pro Play)
- Samsung (various model)

**Screenshots**
<img width="1452" alt="Screenshot 2023-03-28 at 11 26 56" src="https://user-images.githubusercontent.com/4310553/228192600-a7699acb-e328-4d2b-bd29-bc5e06ac7a07.png">

**Stack trace**
`main (timed waiting):tid=1 systid=6585 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:88)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__Builders.kt:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__Builders.kt:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(Builders.kt:1)
       at io.getstream.chat.android.client.call.DistinctCall.execute(DistinctCall.kt:52)
       at io.walkietalkie.views.messaging.ChannelActivity.initChannelInfo(ChannelActivity.java:159)
       at io.walkietalkie.views.messaging.ChannelActivity.onCreate(ChannelActivity.java:75)
       at android.app.Activity.performCreate(Activity.java:8130)
       at android.app.Activity.performCreate(Activity.java:8110)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3975)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2377)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8205)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)`

**Comment by DanielNovak** [comment]
You are most probably using `execute()` instead of `await()` or `enqueue()` when executing the API call. The `execute()` is a blocking call:

```
    override fun execute(): Result<T> = runBlocking { await() }
```
