### ISSUE TITLE
Crash when user leave or add to channel

### ISSUE THREAD

**Issue by maxmaxandr** [GetStream/stream-chat-android#476]
I've got this crash when a user level a channel or somebody added to channel

```
 FATAL EXCEPTION: DefaultDispatcher-worker-1
    kotlin.KotlinNullPointerException
        at io.getstream.chat.android.livedata.EventHandlerImpl.updateOfflineStorageFromEvents$library_release(EventHandlerImpl.kt:170)
        at io.getstream.chat.android.livedata.EventHandlerImpl$updateOfflineStorageFromEvents$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by tschellenbach** [comment]
Going to look into this. Seems like our test suite and reality have a slightly different event structure which is causing issues.

**Comment by tschellenbach** [comment]
![image](https://user-images.githubusercontent.com/265409/81985391-6f974e80-95f3-11ea-9dfe-120360733452.png)
@tbarbugli

**Comment by tbarbugli** [comment]
@tschellenbach both `MemberRemovedEvent` and `NotificationRemovedFromChannel` do not have member user, you can find the removed user in `event.user`

**Comment by tschellenbach** [comment]
Fixed in 0.4.4: https://github.com/GetStream/stream-chat-android-livedata/releases/tag/0.4.4

**Comment by tschellenbach** [comment]
https://github.com/GetStream/stream-chat-android/releases/tag/4.2.7

**Comment by maxmaxandr** [comment]
> https://github.com/GetStream/stream-chat-android/releases/tag/4.2.7

Still have crash on 4.2.7,  Live data 0.4.4

```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-5
    kotlin.KotlinNullPointerException
        at io.getstream.chat.android.livedata.EventHandlerImpl.updateOfflineStorageFromEvents$livedata_release(EventHandlerImpl.kt:177)
        at io.getstream.chat.android.livedata.EventHandlerImpl$updateOfflineStorageFromEvents$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by tschellenbach** [comment]
Different but related problem:

![image](https://user-images.githubusercontent.com/265409/82221093-c09d9000-98dc-11ea-8473-af2ae4e61e5d.png)

Will let you know when it's fixed

**Comment by maxmaxandr** [comment]
Hi, any plan when it will be fixed?

**Comment by tschellenbach** [comment]
I can pick this one up in the weekend. Will post an update when its fixed

**Comment by tschellenbach** [comment]
@tbarbugli one of these 2 events (or both) sometimes don't have event.cid defined. I'm working around it in the android client. 

MemberRemovedEvent, is NotificationRemovedFromChannel

**Comment by tschellenbach** [comment]
https://github.com/GetStream/stream-chat-android/releases/tag/4.2.9-beta-1

**Comment by maxmaxandr** [comment]
@tschellenbach 
SDK: 4.2.9-beta-1
LiveData: 0.4.7

It still has crash
```
I/Chat:ChatDomain QueryChannelsController: received channel event ChatEvent(type='member.removed')
I/ChatDomain: ChatDomain: The channels changed
I/Chat:ChatDomain QueryChannelsController: received channel event ChatEvent(type='channel.updated')
I/ChatDomain: ChatDomain: The channels changed
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    kotlin.KotlinNullPointerException
        at io.getstream.chat.android.livedata.EventHandlerImpl.updateOfflineStorageFromEvents$livedata_release(EventHandlerImpl.kt:179)
        at io.getstream.chat.android.livedata.EventHandlerImpl$updateOfflineStorageFromEvents$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by tschellenbach** [comment]
Looks like the member.removed event doesn't have event.user

![image](https://user-images.githubusercontent.com/265409/82777515-93387100-9e0b-11ea-9b42-4293d3a084d9.png)

**Comment by tschellenbach** [comment]
The above code works for member removed event.

```
"member.removed": {
    "type": "member.removed",
    "cid": "messaging:904157e4-fd5b-4570-afab-fa2917cd1cab",
    "user": {
      "id": "member1-c30df970-2054-4ae9-ac34-6a4da4283c05",
      "role": "user",
      "created_at": "2020-05-26T03:31:21.365946Z",
      "updated_at": "2020-05-26T03:31:21.366487Z",
      "banned": false,
      "online": false
    },
    "created_at": "2020-05-26T03:31:22.442859279Z",
    "received_at": "2020-05-26T03:31:22.481Z"
  },
```

It however doesn't work for the NotificationRemovedFromChannel event. (that event triggers for the current user only.) 

```
"notification.removed_from_channel": {
    "type": "notification.removed_from_channel",
    "channel": {
      "id": "01644eff-d351-42c9-a08f-46fd61fba07f",
      "type": "messaging",
      "cid": "messaging:01644eff-d351-42c9-a08f-46fd61fba07f",
      "last_message_at": "2020-05-26T03:34:00.775754Z",
      "created_at": "2020-05-26T03:33:57.597097Z",
      "updated_at": "2020-05-26T03:33:57.597098Z",
      "created_by": {
        "id": "tommaso-f744ee8f-fb4e-499f-be3a-8284e4061c09",
        "role": "user",
        "created_at": "2020-05-26T03:33:57.454809Z",
        "updated_at": "2020-05-26T03:33:57.455296Z",
        "banned": false,
        "online": false
      },
      "frozen": false,
      "config": {
        "created_at": "2020-04-29T09:31:42.216834Z",
        "updated_at": "2020-05-26T03:27:39.956689Z",
        "name": "messaging",
        "typing_events": true,
        "read_events": true,
        "connect_events": true,
        "search": true,
        "reactions": true,
        "replies": true,
        "mutes": true,
        "uploads": true,
        "url_enrichment": true,
        "message_retention": "infinite",
        "max_message_length": 5000,
        "automod": "disabled",
        "automod_behavior": "flag",
        "commands": [
          {
            "name": "giphy",
            "description": "Post a random gif to the channel",
            "args": "[text]",
            "set": "fun_set"
          },
          {
            "name": "mute",
            "description": "Mute a user",
            "args": "[@username]",
            "set": "moderation_set"
          },
          {
            "name": "unmute",
            "description": "Unmute a user",
            "args": "[@username]",
            "set": "moderation_set"
          }
        ]
      }
    },
    "member": {
      "role": "member",
      "created_at": "2020-05-26T03:33:59.556382Z",
      "updated_at": "2020-05-26T03:33:59.556382Z"
    },
    "created_at": "2020-05-26T03:34:09.38340364Z",
    "received_at": "2020-05-26T03:34:09.436Z"
  },
```

**Comment by tschellenbach** [comment]
Fix it: https://github.com/GetStream/stream-chat-android-livedata/releases/tag/0.5.2

Also I have a todo scheduled for checking all event structures against our test data to prevent issues like these in the future.

**Comment by tschellenbach** [comment]
Did that work for you or are there more issues?

**Comment by maxmaxandr** [comment]
Looks like now there is no crash anymore.

**Comment by tschellenbach** [comment]
That's great, in a few weeks our test suite will be more reliable and these type of issues won't make it into production any more. 

Are you using any of our UI elements or just low level client + livedata?
