### ISSUE TITLE
lateinit property instance has not been initialized

### ISSUE THREAD

**Issue by psylinse** [GetStream/stream-chat-android#480]
Version: `4.2.5`

Hit an issue with `ChannelViewModel`:

```
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property instance has not been initialized
        at io.getstream.chat.android.livedata.ChatDomain$Companion.instance(ChatDomain.kt:140)
        at io.getstream.chat.android.livedata.ChatDomain.instance(Unknown Source:2)
        at com.getstream.sdk.chat.viewmodel.ChannelViewModel.<init>(ChannelViewModel.java:109)
        at com.getstream.sdk.chat.viewmodel.ChannelViewModelFactory.create(ChannelViewModelFactory.java:23)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at io.getstream.thestream.ChannelActivity.initViewModel(ChannelActivity.kt:59)
```

It looks like `ChatViewModel` is trying to reference something called `ChatDomain`. I'm unsure what this is. I have set up my client in a fairly vanilla way following the example [here](https://getstream.io/tutorials/android-chat/#kotlin):

```kotlin
fun init(context: Context, user: String, credentials: BackendService.StreamCredentials) {
    val chat = Chat.Builder(credentials.apiKey, context)
        .logLevel(ChatLogLevel.ALL)
        .build()

    this.user = User(user)
    this.user.extraData["name"] = user
    this.client = chat.client
    this.client.setUser(this.user, credentials.token, object : InitConnectionListener() {
        override fun onSuccess(data: ConnectionData) {
            Log.i("MainActivity", "setUser completed")
        }

        override fun onError(error: ChatError) {
            Toast.makeText(context, error.toString(), Toast.LENGTH_LONG).show()
            Log.e("MainActivity", "setUser onError")
        }
    })
}
```

This was working on `4.0.13`

**Comment by tschellenbach** [comment]
Calling something like this will help resolve this:

```
chatDomain = new ChatDomain.Builder(getContext().getApplicationContext(), Chat.getInstance().getClient(), user).offlineEnabled().userPresenceEnabled().build();
```

We need to change the builder flow for the `Chat` class to make this more explicit in the future

**Comment by psylinse** [comment]
That worked, however I have no idea what this thing is. Do you mind explaining it a bit? Not sure why I need to initialize a `Chat` instance and a `ChatDomain` instance. Wouldn't the `Chat` instance initialize this, or visa versa?


Also, hit another bug right after this:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.getstream.thestream, PID: 30702
    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
        at com.getstream.sdk.chat.view.AvatarView.createImageRounded(AvatarView.kt:87)
        at com.getstream.sdk.chat.view.AvatarView.createBitmap(AvatarView.kt:68)
        at com.getstream.sdk.chat.view.AvatarView$createBitmap$2.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7478)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

Looks like this one? https://github.com/GetStream/stream-chat-android/issues/478

**Comment by tschellenbach** [comment]
@samiuelson on our team is working on cleaning up the initialization of the Chat instance. 

The image loading bug is already fixed I believe, @JcMinarro

**Comment by psylinse** [comment]
Awesome, thank you! Do users need to understand `ChatDomain` (writing a post for the blog)?

**Comment by tschellenbach** [comment]
Yes, but it's not 100% ready yet for an announcement, still polishing things a bit: https://getstream.io/chat/docs/livedata/?language=js

**Comment by JcMinarro** [comment]
Hi @psylinse the bug related with the bitmap creation is already fixed, you can use the version 2.4.6
According to the issue with ChatDomain, try to use the snippet code Thierry posted.
BTW, we are working to simplify how it is initialized and will be easier to use soon

**Comment by psylinse** [comment]
The snippet works great along with 2.4.6 (other issues not withstanding), just don't understand chat domain. I'll hold on for now, thank you!

**Comment by tschellenbach** [comment]
Thanks again for reporting this. New version of the builder is in progress in the "develop" branch. Will go live in the coming weeks. Looking forward to that release.

**Comment by adasiewiczr** [comment]
hey @Sibm02021,
can you tell me which SDK version are you using?
Make sure you are building `io.getstream.chat.android.livedataChatDomain`. You can also find `io.getstream.chat.android.offline.ChatDomain` but you need to initialize the first one in order to use UI components.
We are currently working on next major release which will simplify the process and prevent issues like that.

**Comment by Sibm02021** [comment]
@adasiewiczr I was using the latest one, however the issue has now disappeared and the chat is working fine. I think the issue was due to something I did wrong as opposed to any issues with the SDK.
