### ISSUE TITLE
Cannot send a message with offline plugin (cid can not be empty)

### ISSUE THREAD

**Issue by rocklass** [GetStream/stream-chat-android#4854]
**Describe the bug**
Cannot send a message when offline plugin is active (client)

**SDK version**
- 5.17.6

**To Reproduce**
1. Init `ChatClient` with offline plugin
2. Connect the user
3. Send a message to any channel

**Expected behavior**
Message is sent

**Device:**
 - Vendor and model: Android Emulator
 - Android version: API 33

**Screenshots**
N/A

**Error log**
```
FATAL EXCEPTION: DefaultDispatcher-worker-18
Process: xxx, PID: 6484
java.lang.IllegalStateException: cid can not be empty
	at io.getstream.chat.android.client.extensions.StringExtensionsKt.cidToTypeAndId(StringExtensions.kt:56)
	at io.getstream.chat.android.offline.plugin.logic.internal.LogicRegistry.channelFromMessage(LogicRegistry.kt:159)
	at io.getstream.chat.android.offline.interceptor.internal.SendMessageInterceptorImpl.prepareAndUploadIfNeeded(SendMessageInterceptorImpl.kt:104)
	at io.getstream.chat.android.offline.interceptor.internal.SendMessageInterceptorImpl.interceptMessage(SendMessageInterceptorImpl.kt:72)
	at io.getstream.chat.android.client.ChatClient$sendMessage$2.invokeSuspend(ChatClient.kt:1636)
	at io.getstream.chat.android.client.ChatClient$sendMessage$2.invoke(Unknown Source:8)
	at io.getstream.chat.android.client.ChatClient$sendMessage$2.invoke(Unknown Source:4)
	at io.getstream.chat.android.client.call.CoroutineCall$enqueue$2.invokeSuspend(CoroutineCall.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [io.getstream.chat.android.client.call.SharedCalls@57e415f, StandaloneCoroutine{Cancelling}@5822c67, Dispatchers.IO]
```

**Comment by rocklass** [comment]
I managed to solve the issue by setting the `cid` "manually" in the `Message` constructor, not ideal as we must already provide the channel ID and type to the `sendMessage` function

```
client.sendMessage(
    channelType = channelType,
    channelId = channelId,
    message = Message(cid = "$channelType:$channelId", text = message)
)
```
