### ISSUE TITLE
App crash on attachment icon click

### ISSUE THREAD

**Issue by posakya** [GetStream/stream-chat-android#4903]
### Discussed in https://github.com/GetStream/stream-chat-android/discussions/4902

<div type='discussions-op-text'>

<sup>Originally posted by **posakya** July 27, 2023</sup>
The app gets crash when clicking on the attachment icon on stream chat
sdk version :  5.17.7

```
 java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/viewpager2/adapter/FragmentStateAdapter;
                                                                                                    	at io.getstream.chat.android.ui.message.input.MessageInputView.configAttachmentButton$lambda-23(MessageInputView.kt:647)
                                                                                                    	at io.getstream.chat.android.ui.message.input.MessageInputView.$r8$lambda$Te-p0mOekgHeRH37pYAo--6Ueuk(Unknown Source:0)
                                                                                                    	at io.getstream.chat.android.ui.message.input.MessageInputView$$ExternalSyntheticLambda13.onAttachmentButtonClicked(Unknown Source:2)
                                                                                                    	at io.getstream.chat.android.ui.message.input.MessageInputView.setAttachmentButtonClickListener$lambda-24(MessageInputView.kt:671)
                                                                                                    	at io.getstream.chat.android.ui.message.input.MessageInputView.$r8$lambda$Z39LURGpUH4cNoH05tK8_bdX9cQ(Unknown Source:0)
                                                                                                    	at io.getstream.chat.android.ui.message.input.MessageInputView$$ExternalSyntheticLambda6.onClick(Unknown Source:2)
                                                                                                    	at android.view.View.performClick(View.java:7751)
                                                                                                    	at android.view.View.performClickInternal(View.java:7724)
                                                                                                    	at android.view.View.access$3700(View.java:858)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29336)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8280)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by DanielNovak** [comment]
Hi @posakya , are you still experiencing this issue?

**Comment by DanielNovak** [comment]
Closing due to inactivity.
