### ISSUE TITLE
UserDao maybe leak to crash by cannot start a transaction within a transaction (code 1 SQLITE_ERROR)

### ISSUE THREAD

**Issue by donlan** [GetStream/stream-chat-android#4907]
**Describe the bug**
There are many fatal exceptions (**cannot start a transaction within a transaction (code 1 SQLITE_ERROR)**) reported on our app's firebase for **UserDao**, the logs are as follows:
`
Fatal Exception: android.database.sqlite.SQLiteException: cannot start a transaction within a transaction (code 1 SQLITE_ERROR)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:648)
       at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:321)
       at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:568)
       at android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive(SQLiteDatabase.java:502)
       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransactionNonExclusive(FrameworkSQLiteDatabase.kt:59)
       at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.kt:524)
       at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.kt:508)
       at io.getstream.chat.android.offline.repository.domain.user.internal.UserDao_Impl$3.call(UserDao_Impl.java:135)
       at io.getstream.chat.android.offline.repository.domain.user.internal.UserDao_Impl$3.call(UserDao_Impl.java)
       at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:65)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
`

Not only version 5.17.8 has encountered this exception again, but also previous versions.

**SDK version**
- 5.17.8

**To Reproduce**
I can't reproduce the bug, but many of these bugs are reported on our app's firebase.

**Expected behavior**
No crash.

**Device:**
 
<img width="341" alt="image" src="https://github.com/GetStream/stream-chat-android/assets/11363921/b51cd10b-229d-42b7-91be-f4d9d09e4b67">

**Screenshots**
Only crash logs from firebase.

**Comment by DanielNovak** [comment]
Hi @donlan , sorry for the late reply. We have been seeing this issues but so far we don't have a solution. It seems to be a platform bug that is then propagated in Room but also for example in SqlDelight (see issue https://github.com/cashapp/sqldelight/issues/4361). The platform bug itself is maybe described here: https://issuetracker.google.com/issues/37001653

Maybe defining a single thread for the whole Room instance would prevent this: 
(this code could be used when you create the ChatDatabase)

```kotlin
val executor = Executors.newSingleThreadExecutor {
    Thread(it, "stream-db-$userId")
}

Room.databaseBuilder(...)
    .fallbackToDestructiveMigration()
    .setTransactionExecutor(executor)
    .setQueryExecutor(executor)
```

**Comment by donlan** [comment]
> Hi @donlan , sorry for the late reply. We have been seeing this issues but so far we don't have a solution. It seems to be a platform bug that is then propagated in Room but also for example in SqlDelight (see issue [cashapp/sqldelight#4361](https://github.com/cashapp/sqldelight/issues/4361)). The platform bug itself is maybe described here: https://issuetracker.google.com/issues/37001653
> 
> Maybe defining a single thread for the whole Room instance would prevent this: (this code could be used when you create the ChatDatabase)
> 
> ```kotlin
> val executor = Executors.newSingleThreadExecutor {
>     Thread(it, "stream-db-$userId")
> }
> 
> Room.databaseBuilder(...)
>     .fallbackToDestructiveMigration()
>     .setTransactionExecutor(executor)
>     .setQueryExecutor(executor)
> ```

Thanks for your reply. I had tried your solution tips,but we also catched the crash reported events from our firebase dashboard.

**Comment by donlan** [comment]
And we also catch some **ReactionDao** exceptions as flow:

`
Non-fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:608)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:570)
       at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.kt:75)
       at androidx.room.RoomDatabase.internalEndTransaction(RoomDatabase.kt:550)
       at androidx.room.RoomDatabase.endTransaction(RoomDatabase.kt:540)
       at io.getstream.chat.android.offline.repository.domain.reaction.internal.ReactionDao_Impl$4.call(ReactionDao_Impl.java:138)
       at io.getstream.chat.android.offline.repository.domain.reaction.internal.ReactionDao_Impl$4.call(ReactionDao_Impl.java)
       at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:65)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
`


Devices info:
<img width="1022" alt="image" src="https://github.com/GetStream/stream-chat-android/assets/11363921/ea18c011-d6af-4e22-9d66-a5dbd6e86b5a">

Please have a look.

**Comment by DanielNovak** [comment]
We have finally identified and fixed the problem in this PR: https://github.com/GetStream/stream-chat-android/pull/5164
(this bug had an sideffect of causing the SQLite exception)
