### ISSUE TITLE
App crashing on startup constantly.

### ISSUE THREAD

**Issue by elevenetc** [GetStream/stream-chat-android#492]
App crashing on startup constantly.
```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: io.getstream.chat.sdk, PID: 17276
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter role
        at io.getstream.chat.android.client.models.Member.<init>(Unknown Source:7)
        at io.getstream.chat.android.client.models.Member.<init>(Member.kt:19)
        at io.getstream.chat.android.livedata.entity.MemberEntity.toMember(MemberEntity.kt:41)
        at io.getstream.chat.android.livedata.entity.ChannelEntity.toChannel(ChannelEntity.kt:98)
        at io.getstream.chat.android.livedata.ChatDomainImpl.selectAndEnrichChannels$livedata_release(ChatDomainImpl.kt:657)
        at io.getstream.chat.android.livedata.ChatDomainImpl$selectAndEnrichChannels$2.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Stops crashing if cache is cleaned. So most probably the issue in database data.

Possible way to reproduce:
1. Open channel on device A
2. Change name of the channel on device B
3. Scroll channel messages on device A
4. Crash.
5. Restart app
6. the same crash

**Comment by elevenetc** [comment]
Fix in `4.2.9-beta-1`
