### ISSUE TITLE
Push notifications not working with R8 enabled - java.lang.ClassNotFoundException: io.getstream.chat.android.client.notifications.ChatPushDelegate

### ISSUE THREAD

**Issue by matteinn** [GetStream/stream-chat-android#4953]
**Describe the bug**
With R8 (full mode) turned on, push notifications are not working.
I've found some warnings on the logs complaining about that, I think it's due to some missing consumer rules on either the main SDK or the [push artifacts](https://github.com/GetStream/stream-android-push).

Warnings:
```
2023-09-12 17:35:11'746 (main:2) [E/Push:Delegate]: PushDelegate not created for 'io.getstream.chat.android.client.notifications.ChatPushDelegate'
java.lang.ClassNotFoundException: io.getstream.chat.android.client.notifications.ChatPushDelegate
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.lang.Class.forName(Class.java:379)
	at io.getstream.android.push.delegate.PushDelegateProvider.e(Unknown Source:5)
	at io.getstream.android.push.delegate.PushDelegateProvider.c(Unknown Source:73)
	at io.getstream.android.push.delegate.PushDelegateProvider.b(Unknown Source:37)
	at io.getstream.android.push.delegate.PushDelegateProvider.d(Unknown Source:13)
	at io.getstream.android.push.delegate.PushDelegateProvider.onCreate(Unknown Source:0)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2494)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2464)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7602)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7125)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7009)
	at android.app.ActivityThread.access$1700(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2098)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.ClassNotFoundException: io.getstream.chat.android.client.notifications.ChatPushDelegate
	... 21 more
```

Can you please provide the correct set of rules, and eventually add them as consumer rules in the SDK itself?

Usage:
```
    implementation("io.getstream:stream-chat-android-state:6.0.2")
    implementation("io.getstream:stream-chat-android-offline:6.0.2")
    implementation("io.getstream:stream-chat-android-compose:6.0.2")
    implementation("io.getstream:stream-android-push-firebase:1.1.4")
```

**SDK version**
- 6.0.2

**To Reproduce**
1. Enable R8
2. Launch app
3. Observe logs

**Expected behavior**

**Device:**
 - Vendor and model: all
 - Android version: all

**Screenshots**
None

**Comment by kanat** [comment]
Hi @matteinn,

Thank you for reporting this issue.
It will be fixed in the next upcoming release.

In the meantime, could you please apply the following rule on your end:
```gradle
-keep class io.getstream.chat.android.client.notifications.ChatPushDelegate { *; }
```

**Comment by kanat** [comment]
Has been fixed in [v6.0.3](https://github.com/GetStream/stream-chat-android/releases/tag/v6.0.3).

**Comment by kanat** [comment]
Hi @matteinn,

Could you please check the [v6.0.3](https://github.com/GetStream/stream-chat-android/releases/tag/v6.0.3) out?

**Comment by matteinn** [comment]
Hey @kanat , sure I'll have a look ASAP and keep you posted

**Comment by matteinn** [comment]
Works fine, thank you!
