### ISSUE TITLE
Sream SDK data serialisation problem

### ISSUE THREAD

**Issue by lukicmarko** [GetStream/stream-chat-android#4993]
**Describe the bug**
The stream SDK returns an error while calling the 
`streamChatClient.queryChannel(channelType = "messaging", channelId = "group_match_chat_6_138", request = QueryChannelRequest().withState()).await()`

The error is:
`com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: Non-null value 'thread_participants' was null at $.thread_participants at $.messages[83]`

My application id is `1253904`
Can you please double check how to fix the problem?

```
                                                                                                    Process: rs.matchit.candidate.staging, PID: 8255
                                                                                                    java.lang.Exception: com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: Non-null value 'thread_participants' was null at $.thread_participants at $.messages[83]
                                                                                                    	at rs.matchit.matchit.chatdatasourcekmm.ChatDataSourceAndroid.getChannel(ChatDataSourceAndroid.kt:114)
                                                                                                    	at rs.matchit.matchit.chatdatasourcekmm.ChatDataSourceAndroid.access$getChannel(ChatDataSourceAndroid.kt:16)
                                                                                                    	at rs.matchit.matchit.chatdatasourcekmm.ChatDataSourceAndroid$getChannel$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
                                                                                                    	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                                                                                                    	at rs.matchit.matchit.chatdatasourcekmm.ChatDataSourceAndroid.getLastUnreadChannelsMessagesCount(ChatDataSourceAndroid.kt:49)
                                                                                                    	at rs.matchit.matchit.chatdatasourcekmm.ChatDataSourceAndroid$getLastUnreadChannelsMessagesCount$1.invokeSuspend(Unknown Source:14)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c5c489e, Dispatchers.Main]
                                                                                                    Caused by: com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: Non-null value 'thread_participants' was null at $.thread_participants at $.messages[83]
                                                                                                    	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:101)
                                                                                                    	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
                                                                                                    	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
                                                                                                    	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
                                                                                                    	at io.getstream.chat.android.client.api2.model.response.ChannelResponseJsonAdapter.fromJson(ChannelResponseJsonAdapter.kt:92)
                                                                                                    	at io.getstream.chat.android.client.api2.model.response.ChannelResponseJsonAdapter.fromJson(ChannelResponseJsonAdapter.kt:32)
                                                                                                    	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
                                                                                                    	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:46)
                                                                                                    	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
                                                                                                    	at io.getstream.chat.android.client.parser2.MoshiErrorLoggingKt$withErrorLogging$1.responseBodyConverter$lambda-0(MoshiErrorLogging.kt:37)
                                                                                                    	at io.getstream.chat.android.client.parser2.MoshiErrorLoggingKt$withErrorLogging$1.$r8$lambda$7GNy0P4X8KBJIev6Fenhub08RzQ(Unknown Source:0)
                                                                                                    	at io.getstream.chat.android.client.parser2.MoshiErrorLoggingKt$withErrorLogging$1$$ExternalSyntheticLambda0.convert(Unknown Source:4)
                                                                                                    	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
                                                                                                    	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
                                                                                                    	at com.google.firebase.perf.network.InstrumentOkHttpEnqueueCallback.onResponse(InstrumentOkHttpEnqueueCallback.java:71)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
2023-10-06 19:31:46.004  8255-8255  AndroidRuntime          rs.matchit.candidate.staging         E  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: com.squareup.moshi.JsonDataException: Non-null value 'thread_participants' was null at $.thread_participants
                                                                                                    	at com.squareup.moshi.internal.Util.unexpectedNull(Util.java:674)
                                                                                                    	at io.getstream.chat.android.client.api2.model.dto.DownstreamMessageDtoJsonAdapter.fromJson(DownstreamMessageDtoJsonAdapter.kt:192)
                                                                                                    	at io.getstream.chat.android.client.api2.model.dto.DownstreamMessageDtoJsonAdapter.fromJson(DownstreamMessageDtoJsonAdapter.kt:29)
                                                                                                    	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
                                                                                                    	at com.squareup.moshi.JsonAdapter.fromJsonValue(JsonAdapter.java:126)
                                                                                                    	at io.getstream.chat.android.client.parser2.adapters.CustomObjectDtoAdapter.parseWithExtraData(CustomObjectDtoAdapter.kt:79)
                                                                                                    	at io.getstream.chat.android.client.parser2.adapters.DownstreamMessageDtoAdapter.fromJson(MessageDtoAdapters.kt:35)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:383)
                                                                                                    	at com.squareup.moshi.AdapterMethodsFactory$4.fromJson(AdapterMethodsFactory.java:269)
                                                                                                    	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:97)
                                                                                                    	... 18 more
```

**SDK version**
- 5.17.12

**To Reproduce**

**Expected behavior**
The SDK should return the expected data not the error

**Device:**

**Screenshots**

**Comment by fedefrappi** [comment]
We're seeing a similar error on our app and in the sample app with sdks v6.0.3/6.0.4 when querying the channel list with _any_ filter applied, resulting in users not being able to see any of their chats

`2023-10-06 23:07:45.305  2896-3017  QueryChannelsLogic      io.....android.compose.sample.debug  D  (DefaultDispatcher-worker-17:117) loadingPerPage: false. success: Failure(value=NetworkError(message=Response is failed. See cause, serverErrorCode=1000, statusCode=-1, cause=com.squareup.moshi.JsonDataException: com.squareup.moshi.JsonDataException: Non-null value 'thread_participants' was null at $.thread_participants at $.channels[2].messages[1])).isSuccess`

**Comment by lukicmarko** [comment]
Wow, it looks like critical bug!

**Comment by fedefrappi** [comment]
I was just in contact with their tech support and it should be solved now!

**Comment by lukicmarko** [comment]
Great! It looks that they fixed the bug.
