### ISSUE TITLE
App crashes on Android 14 when receiving chat push message

### ISSUE THREAD

**Issue by damianpetla** [GetStream/stream-chat-android#4995]
**Describe the bug**
Receiving push notification on Android 14 and letting getstream handle it crashes the app with the following exception:
```kotlin
android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{9c477c0 959:xxxxxxxxxxxxxxx/u0a650} targetSDK=34 has been prohibited
 at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
 at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
 at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
 at android.os.Parcel.readParcelable(Parcel.java:4852)
 at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
 at android.os.Parcel.createException(Parcel.java:3041)
 at android.os.Parcel.readException(Parcel.java:3024)
 at android.os.Parcel.readException(Parcel.java:2966)
 at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
 at android.app.Service.startForeground(Service.java:862)
 at androidx.work.impl.foreground.SystemForegroundService$1.run(SystemForegroundService.java:124)
 at android.os.Handler.handleCallback(Handler.java:958)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:205)
 at android.os.Looper.loop(Looper.java:294)
 at android.app.ActivityThread.main(ActivityThread.java:8177)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

It crashes on `LoadNotificationDataWorker` when you set it to be foreground but without type. Check out Google docs where they explain that https://developer.android.com/guide/background/persistent/how-to/long-running#foreground-service-type

**SDK version**
- 5.17.13

**To Reproduce**
1. Enable push notifications and wait for a push message from another device.

**Expected behavior**
Expect getstream handle the push message and display it. Not crash.

**Device:**
 - Vendor and model: Google Pixel 5
 - Android version: 14

**Comment by JcMinarro** [comment]
Hi @damianpetla 
Thanks for reporting it.
Let us fix it.

**Comment by damianpetla** [comment]
Thanks @JcMinarro Any ETA on this? If it takes a while we will have to release hot fix with getstream pushes disabled.

**Comment by JcMinarro** [comment]
I just added a fix for it, it will be ready on the following release

**Comment by damianpetla** [comment]
Great news @JcMinarro !!! Thank you. May I ask when do you plan following release and is it going to be on top of V5 so we don't have to migrate to V6 yet?

**Comment by JcMinarro** [comment]
I just created the same patch for V5.
BTW, Remember that, from now on, V5 will  only be updated with bug-fixes, any new feature will only be implemented on V6

**Comment by damianpetla** [comment]
Thanks @JcMinarro We will migrate soon to V6, I actually did a quick migration already but few things did not work as expected so need more time to look into that. In the meantime we need to resolve crashes ASAP.

**Comment by damianpetla** [comment]
Hey @JcMinarro what about new release date? Number of Android 14 users is growing and app keep crashing. We need to either release with your fix or disable pushes.

**Comment by JcMinarro** [comment]
We should release a new version this week.

**Comment by JcMinarro** [comment]
A new V5 patch that contains this and other fixes has been released.
It will be public available on Maven Central in the following hours
