### ISSUE TITLE
Crash on MediaGalleryPreviewActivity: Missing messageId necessary to load images.

### ISSUE THREAD

**Issue by matteinn** [GetStream/stream-chat-android#5148]
**Describe the bug**

```
Caused by java.lang.IllegalArgumentException: Missing messageId necessary to load images.
       at io.getstream.chat.android.compose.ui.attachments.preview.MediaGalleryPreviewActivity.onCreate(MediaGalleryPreviewActivity.kt:260)
       at android.app.Activity.performCreate(Activity.java:8305)
       at android.app.Activity.performCreate(Activity.java:8284)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
        
```

**SDK version**
- 6.0.10

**To Reproduce**
Steps to reproduce the behavior: unknown, but I have a feeling it happens when opening the media gallery

**Expected behavior**
No crash happens

**Device:**
 - Vendor and model: Google Nexus 5X only, apparently
 - Android version: 8 and 11 only, apparently

**Screenshots**

![Screenshot 2024-01-15 at 13 56 58](https://github.com/GetStream/stream-chat-android/assets/531755/bb10c503-4bd0-4075-98cf-25494f8789a3)

**Comment by kanat** [comment]
Hey @matteinn,

Could you please check if it still replicates for you on v6.5.0?

**Comment by matteinn** [comment]
Hello! I confirm this is still happening at scale with 6.5.0, I can't reproduce on my own though

**Comment by andremion** [comment]
Hi @matteinn ,
Can you please check if it's still reproducible with one of the latest releases?
Thanks

**Comment by matteinn** [comment]
Hi @andremion , still happening on `6.10.0`

**Comment by andremion** [comment]
Hi @matteinn , 
Unfortunately, I am unable to reproduce the problem on my end.
To help us investigate further, could you please provide all the necessary steps to reproduce it?
Thanks,

**Comment by matteinn** [comment]
No, sadly I can't reproduce either but it seems to happen at scale (not even large, we are talking about few thousands of monthly active users)

**Comment by andremion** [comment]
Do you know if those users have low-end devices?

**Comment by matteinn** [comment]
Good call, apparently it's only happening on 22 different Google Nexus 5X on Android 13 and 8.1.0.
Maybe this comes from the automated tests performed by the google play store when releasing new app versions, but I'm not sure.

**Comment by andremion** [comment]
Can you confirm if those crashes come from actual users? Are they constantly happening?

**Comment by matteinn** [comment]
> Can you confirm if those crashes come from actual users? Are they constantly happening?

I can't guarantee that, it's weird that it only appeared on 30 different Nexus 5X devices on Android 13 in the past 90 days.

**Comment by andremion** [comment]
OK. I will close this ticket for now since no one can reproduce it.
Feel free to reopen it in case you find out how to reproduce it.
Thanks,
