### ISSUE TITLE
ConcurrentModificationException crash

### ISSUE THREAD

**Issue by matteinn** [GetStream/stream-chat-android#5149]
**Describe the bug**

```
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
       at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:782)
       at io.getstream.chat.android.client.utils.observable.ChatEventsObservable.onNext(ChatEventsObservable.java:14)
       at io.getstream.chat.android.client.utils.observable.ChatEventsObservable.access$onNext(ChatEventsObservable.java)
       at io.getstream.chat.android.client.utils.observable.ChatEventsObservable$EventsMapper.onConnecting(ChatEventsObservable.java:15)
       at io.getstream.chat.android.client.socket.ChatSocket$observeSocketStateService$1$1$5.invoke(ChatSocket.java:5)
       at io.getstream.chat.android.client.socket.ChatSocket$observeSocketStateService$1$1$5.invoke(ChatSocket.java:2)
       at io.getstream.chat.android.client.socket.ChatSocket$callListeners$1$1$1.invokeSuspend(ChatSocket.java:14)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:11)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:93)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:3)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:2)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:14)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:28)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java)
```

**SDK version**
- 6.0.10

**To Reproduce**
Steps to reproduce the behavior: unknown

**Expected behavior**
App doesn't crash

**Device:**
 - Vendor and model: see screenshots
 - Android version: see screenshots

![Screenshot 2024-01-15 at 14 31 14](https://github.com/GetStream/stream-chat-android/assets/531755/9f8047a7-972c-4ac0-8edb-a8d2de971a1f)
![Screenshot 2024-01-15 at 14 31 19](https://github.com/GetStream/stream-chat-android/assets/531755/b7320e80-7fa4-41d8-a149-10942dad16c4)
![Screenshot 2024-01-15 at 14 31 24](https://github.com/GetStream/stream-chat-android/assets/531755/2e94e824-ddd4-4930-bc45-17af7e2ab5ab)

**Screenshots**

**Comment by rocklass** [comment]
Same issue for me on version 6.0.11
