### ISSUE TITLE
Crash with Gif

### ISSUE THREAD

**Issue by spvince** [GetStream/stream-chat-android#516]
<h2>What did you do?</h2>
I send a gif in a channel

<h2>What did you expect to happen?</h2>
No crash and the gif should be displayed in channel

<h2>What happened instead?</h2>
I have a crash

<br/> <details>
<summary>Crash </summary>
<p>

```java
    java.lang.UnsupportedOperationException
        at java.util.AbstractList.remove(AbstractList.java:161)
        at java.util.AbstractList$Itr.remove(AbstractList.java:374)
        at java.util.AbstractList.removeRange(AbstractList.java:571)
        at java.util.AbstractList.clear(AbstractList.java:234)
        at com.getstream.sdk.chat.utils.MessageInputController.initAdapter(MessageInputController.java:385)
        at com.getstream.sdk.chat.utils.MessageInputController.initSendMessage(MessageInputController.java:380)
        at com.getstream.sdk.chat.view.MessageInputView.initSendMessage(MessageInputView.java:385)
        at com.getstream.sdk.chat.view.MessageInputView.handleSentMessage(MessageInputView.java:380)
        at com.getstream.sdk.chat.view.MessageInputView.onSendMessage(MessageInputView.java:360)
        at com.getstream.sdk.chat.view.MessageInputView.onSendMessage(MessageInputView.java:373)
        at com.getstream.sdk.chat.view.MessageInputView.sendGiphyFromKeyboard(MessageInputView.java:446)
        at com.getstream.sdk.chat.view.MessageInputView.lambda$7isDU6nwn6hPbwpNCP-kATPrdUc(Unknown Source:0)
        at com.getstream.sdk.chat.view.-$$Lambda$MessageInputView$7isDU6nwn6hPbwpNCP-kATPrdUc.onCommitContent(Unknown Source:2)
        at androidx.core.view.inputmethod.InputConnectionCompat$1.commitContent(InputConnectionCompat.java:275)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:566)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
</p>
</details>

<h2>GetStream Environment</h2>

GetStream Chat version:
4.2.11-beta-4

**Comment by samiuelson** [comment]
Thank you for reporting this, we are currently pushing on a new major release which will not be affected by this problem. You can already try the beta release and subscribe to this issue to stay up-to-date to the release https://github.com/GetStream/stream-chat-android/issues/554

**Comment by JcMinarro** [comment]
Hello @spvince 
The `MessageInputView` has been refactored and it should be working fine now on version [4.2.11-beta-7](https://github.com/GetStream/stream-chat-android/releases/tag/4.2.11-beta-7)
Could you check it?
