### ISSUE TITLE
when another user starts typing the channelListFragment crashes with issue unable to create instance of ChannelListViewModelClass

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#517]
I am integrated chat in an app and have added user in splash screen of the app. I am using channel list as fragment. when i enter into it, the instance is created without any problem. Even the unread message count is updated on realtime but when i have clicked on the channel and go into channel activity and there if any user starts typing in another device, the app crashes with error of unable to created instance of the ChannelListViewModel class. I have used chat domain declaration when i am adding the user in the splash screen

**Comment by abhirup-patra** [comment]
for your reference i am attaching the stack trace with the errors please have a look.




2020-06-09 14:39:12.699 13674-13674/qqq.com E/AndroidRuntime: FATAL EXCEPTION: main
    Process: abentra.com, PID: 13674
    java.lang.RuntimeException: Unable to resume activity {abentra.com/qqq.com.views.activities.HomeActivity}: java.lang.RuntimeException: Cannot create an instance of class com.getstream.sdk.chat.viewmodel.ChannelListViewModel
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.getstream.sdk.chat.viewmodel.ChannelListViewModel
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:275)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at qqq.com.views.fragments.stream_chat.ChannelListFragment.onCreateView(ChannelListFragment.java:185)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:310)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1185)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:2727)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:355)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1192)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1495)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2617)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2581)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:269)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:478)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:467)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:195)
        at android.app.Activity.performResume(Activity.java:7964)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
2020-06-09 14:39:12.699 13674-13674/qqq.com E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:267)
        	... 40 more
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property instance has not been initialized
        at io.getstream.chat.android.livedata.ChatDomain$Companion.instance(ChatDomain.kt:140)
        at io.getstream.chat.android.livedata.ChatDomain.instance(Unknown Source:2)
        at com.getstream.sdk.chat.viewmodel.ChannelListViewModel.<init>(ChannelListViewModel.java:77)

**Comment by elevenetc** [comment]
Could you show code where you initialise SDK? The cause of crash is not initialised `ChatDomain`:
```
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property instance has not been initialized
at io.getstream.chat.android.livedata.ChatDomain$Companion.instance(ChatDomain.kt:140)
```
So there is no instance:
```
    companion object {

        private lateinit var instance: ChatDomain

        @JvmStatic
        fun instance(): ChatDomain {
            return instance // 140 line with crash
        }
    }
```

**Comment by abhirup-patra** [comment]
```
public static void clientInitialization(String id, String username,String token,String image,Context context) {

        // normally you would call init in your Application class and not the activity
       /* Chat chat = new Chat.Builder("yegntpd4k4kg", getApplicationContext()).logLevel(
                ChatLogLevel.ALL).build();
        client =chat.getClient();
*/

       /* USER_ID = String.valueOf(AppPreferences.getInstance().getLoginUserDetails().getData().getUser_details().getUser_id());
        USER_TOKEN = AppPreferences.getInstance().getChatToken();
        USER_NAME = AppPreferences.getInstance().getLoginUserDetails().getData().getUser_details().getDisplay_name();
        String USER_IMAGE = AppPreferences.getInstance().getLoginUserDetails().getData().getUser_details().getUser_image();*/

        Crashlytics.setUserIdentifier(id);

        HashMap<String, Object> extraData = new HashMap<>();
        extraData.put("name", username);
        extraData.put("image", image);

        user = new User();
        user.setId(id);
        user.setExtraData(extraData);

        new ChatDomain.Builder(getApplicationContext(), client, user).build();

        Log.e("clientInitialization: ",extraData.toString() );
        Log.e("clientToken: ",token );
        client.setUser(user, token, new InitConnectionListener(){
            @Override
            public void onError(@NotNull ChatError error) {
                super.onError(error);
                Log.i("StreamChatError", error.getLocalizedMessage());
            }

            @Override
            public void onSuccess(@NotNull ConnectionData data) {

                user=data.getUser();
                unread_count= user.getUnreadCount();

               // Log.i("StreamChatError", "works");

                Log.i("countTest", "onSuccess: "+unread_count);

                if(unread_count > 0){
                    AppPreferences.getInstance().setNewPushEnable(true);
                }else {
                    AppPreferences.getInstance().setNewPushEnable(false);
                }
                Log.e("clientInitSuccess: ", String.valueOf(data));
                Log.i("StreamChat", "setUser completed"+id);
                Log.i("unread_count", String.valueOf(unread_count));
                Log.e("showNewMsgIndicator1: ", String.valueOf(AppPreferences.getInstance().getNewPushEnable()));
                super.onSuccess(data);
            }
        });

    }
```

this is inside a public class that is accessed by passing the values from the splash screen

**Comment by abhirup-patra** [comment]
`@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        // setup the client
        //configureStreamClient();
        // example for how to observe the unread counts

        viewModel = new ViewModelProvider(this).get(ChannelListViewModel.class);
        Chat.getInstance().getUnreadMessages().observe(getViewLifecycleOwner(), (Number count) -> {
            Log.i(TAG, String.format("Total unread message count is now %d", count));
             chat_count = (int) count;
            if ( chat_count > 0) {
                AppPreferences.getInstance().setNewPushEnable(true);
               //showNewMessageIndicatorNew
                if (myactivity != null) {
                    myactivity.runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            ((HomeActivity) getActivity()).showNewMessageIndicatorNew();
                        }
                    });
                }

            }else {
                AppPreferences.getInstance().setNewPushEnable(false);
            }
        });
       // LiveData<Int> totalUnreadCountLive = chatDomain.getUseCases().getTotalUnreadCount().invoke().execute().data();
        /*Chat.getInstance().getUnreadChannels().observe(getViewLifecycleOwner(), (Number count) -> {
            Log.i(TAG, String.format("There are %d channels with unread messages", count));
        });*/

        // we're using data binding in this example
        binding = FragmentChannelListBinding.inflate(inflater, container, false);

        // Specify the current activity as the lifecycle owner.
        binding.setLifecycleOwner(this);

        // most the business logic for chat is handled in the ChannelListViewModel view model
//        viewModel = new ViewModelProvider(this).get(ChannelListViewModel.class);

        // just get all channels
        FilterObject filter = Filters.INSTANCE.eq("type", "messaging");

        // ChannelViewHolderFactory factory = new ChannelViewHolderFactory();
        //binding.channelList.setViewHolderFactory(factory);
        QuerySort querySort = new QuerySort().desc("last_message_at");
        viewModel.setQuery(filter,querySort);



        if(Utils.isInternetConnected(getActivity())) {
            binding.setViewModel(viewModel);
            binding.channelList.setViewModel(viewModel, this);

//            Log.i(TAG, "onCreateView: "+viewModel.getChannels().getValue().size());

        }else {
            Utils.showToastLong("No internet connection available",getActivity());
            binding.progressBar.setVisibility(View.GONE);
            binding.pBar.setVisibility(View.GONE);
        }

        setCustomChannelItem(getActivity(), binding);

        return binding.getRoot();
    }`

this is where i am accessing the viewmodel
