### ISSUE TITLE
ArrayIndexOutOfBoundsException of ApiRequestsDumper

### ISSUE THREAD

**Issue by donlan** [GetStream/stream-chat-android#5186]
**Describe the bug**
I catch a crash with the below console prints:
```
java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
 at java.util.ArrayList.add(ArrayList.java:468)
 at io.getstream.chat.android.client.plugins.requests.ApiRequestsDumper.registerRequest(ApiRequestsDumper.kt:47)
 at io.getstream.chat.android.client.api.interceptor.ApiRequestAnalyserInterceptor.intercept(ApiRequestAnalyserInterceptor.kt:42)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at io.getstream.chat.android.client.api.interceptor.HeadersInterceptor.intercept(HeadersInterceptor.kt:33)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at io.getstream.chat.android.client.api.interceptor.ApiKeyInterceptor.intercept(ApiKeyInterceptor.kt:31)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
 at okhttp3.OkHttpOkHttp3Extension.okhttp3RealCall_getResponseWithInterceptorChain$okhttp(OkHttpSourceFile:57)
 at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)
```

**SDK version**
- 6.0.14

**To Reproduce**
I have no idea,occasionally.

**Expected behavior**

**Device:**
 - Vendor and model: Xiaomi M2102J2SC
 - Android version: 13

**Screenshots**
None.

**Comment by kanat** [comment]
Fixed in [v6.1.0](https://github.com/GetStream/stream-chat-android/releases/tag/v6.1.0)
