### ISSUE TITLE
Crash issue with version 5.17.23

### ISSUE THREAD

**Issue by dhaivat29** [GetStream/stream-chat-android#5228]
**Describe the bug**
Fatal Exception: java.lang.NullPointerException: key == null
       at androidx.collection.LruCache.get(LruCache.java:84)
       at io.getstream.chat.android.offline.repository.domain.user.UserRepositoryImpl.selectUser(UserRepository.kt:54)
       at io.getstream.chat.android.offline.repository.builder.RepositoryFacadeBuilder$build$getUser$1.invokeSuspend(RepositoryFacadeBuilder.kt:54)
       at io.getstream.chat.android.offline.repository.builder.RepositoryFacadeBuilder$build$getUser$1.invoke(:8)
       at io.getstream.chat.android.offline.repository.builder.RepositoryFacadeBuilder$build$getUser$1.invoke(:4)
       at io.getstream.chat.android.offline.repository.domain.channel.member.MemberMapperKt.toModel(MemberMapper.kt:18)
       at io.getstream.chat.android.offline.repository.domain.channel.ChannelMapperKt.toModel(ChannelMapper.kt:63)
       at io.getstream.chat.android.offline.repository.domain.channel.ChannelRepositoryImpl.selectChannels(ChannelRepository.kt:58)
       at io.getstream.chat.android.offline.repository.domain.channel.ChannelRepositoryImpl$selectChannels$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**SDK version**
- 5.17.23

**To Reproduce**

**Expected behavior**
Crash should not occor

**Device:**
 - Devices : Samsung S22, Samsung s23+
 - Android version: [14,13]

**Comment by kanat** [comment]
Hi @dhaivat29 ,

We don't have `ChannelRepositoryImpl` and `UserRepositoryImpl` classes in `v5.17.23`
