### ISSUE TITLE
io.getstream.android.push.delegate.PushDelegateProvider obfuscated 

### ISSUE THREAD

**Issue by orafaaraujo** [GetStream/stream-chat-android#5254]
**Describe the bug**
Hello, 

We are facing an issue with a class that is removed when we obfuscate the app.

```java
Fatal Exception: java.lang.RuntimeException: Unable to get provider io.getstream.android.push.delegate.PushDelegateProvider: java.lang.ClassNotFoundException: Didn't find class "io.getstream.android.push.delegate.PushDelegateProvider" on path: DexPathList[[zip file "/data/app/fr.vestiairecollective-8H_Hac6XWrQKRRf9c9nP6w==/base.apk"],nativeLibraryDirectories=[/data/app/fr.vestiairecollective-8H_Hac6XWrQKRRf9c9nP6w==/lib/arm64, /data/app/fr.vestiairecollective-8H_Hac6XWrQKRRf9c9nP6w==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
       at android.app.ActivityThread.installProvider(ActivityThread.java:8186)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7722)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7586)
       at android.app.ActivityThread.access$2600(ActivityThread.java:259)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8673)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

The fix is to add the line below in our rules, but I believe this should be provided by the SDK directly. 

```java
-keep class io.getstream.android.push.delegate.PushDelegateProvider
```

**SDK version**
- `6.2.3`

**To Reproduce**
We couldn't reproduce it, but it's happening when the user opens the app.

**Expected behavior**
 No crashes. 

**Device:**
 - Vendor and model: Galaxy Note9, Redmi K20, Huawei P30...
 - Android version: 10 only

**Comment by JcMinarro** [comment]
Hello @orafaaraujo 
Thanks for reporting it.
Let me move this issue to the [Stream Android Push](https://github.com/GetStream/stream-android-push) repository where this implementation lives
