### ISSUE TITLE
ConnectivityManager issue

### ISSUE THREAD

**Issue by sina-seyfi** [GetStream/stream-chat-android#5288]
**Describe the bug**
There is a problem when you connect and disconnect multiple times with stream chat. On our application, we only connect when the user logs in, and then we disconnect if the user logs out of our application. When we log in and log out multiple times in a row with different users (always 3 log in and then log out) we encounter a crash that is caused by an internal uncaught exception inside the library from ConnectivityManager of Android that prevents the library from registering more callbacks. I read the codes of the library and it seems when we disconnect the library would remove the callback, and I don't know what's the problem.

**Exception**
`FATAL EXCEPTION: DefaultDispatcher-worker-3
                                                                                                    Process: ********, PID: 10896
                                                                                                    android.net.ConnectivityManager$TooManyRequestsException
                                                                                                    	at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4165)
                                                                                                    	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4357)
                                                                                                    	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4364)
                                                                                                    	at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4746)
                                                                                                    	at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4716)
                                                                                                    	at io.getstream.chat.android.client.network.NetworkStateProvider.subscribe(NetworkStateProvider.kt:102)
                                                                                                    	at io.getstream.chat.android.client.socket.ChatSocket.connect(ChatSocket.kt:244)
                                                                                                    	at io.getstream.chat.android.client.socket.ChatSocket.connectUser(ChatSocket.kt:216)
                                                                                                    	at io.getstream.chat.android.client.ChatClient.setUser(ChatClient.kt:499)
                                                                                                    	at io.getstream.chat.android.client.ChatClient.connectUserSuspend(ChatClient.kt:627)
                                                                                                    	at io.getstream.chat.android.client.ChatClient.access$connectUserSuspend(ChatClient.kt:225)
                                                                                                    	at io.getstream.chat.android.client.ChatClient$connectUser$1.invokeSuspend(ChatClient.kt:616)
                                                                                                    	at io.getstream.chat.android.client.ChatClient$connectUser$1.invoke(Unknown Source:8)
                                                                                                    	at io.getstream.chat.android.client.ChatClient$connectUser$1.invoke(Unknown Source:4)
                                                                                                    	at io.getstream.chat.android.client.call.CoroutineCall$enqueue$2.invokeSuspend(CoroutineCall.kt:59)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [io.getstream.chat.android.client.call.SharedCalls@419235a, StandaloneCoroutine{Cancelling}@eabb9cb, Dispatchers.IO]`

**SDK version**
- 5.17.23

**To Reproduce**
1. Connect with the library (with docs provided by the library)
2. Disconnect with the library (with docs provided by the library)
3. Create another ChatClient object and Connect with another user
4. Then disconnect again
5. On the third login after creating a new ChatClient object, when you connect, it will crash

**Expected behavior**
I expect the library to not make our application crash

**Device:**
 - All devices (whether actual or emulator ones) will crash.
 - At least 8.0.0

**Screenshots**
Nothing to put in here.

**Comment by JcMinarro** [comment]
Hello @sina-seyfi 
Why are you recreating a new `ChatClient` instance? :thinking: 
It shouldn't be needed, you can (And should) reuse the same `ChatClient` instance.
