### ISSUE TITLE
Hiding channel causes app crash.

### ISSUE THREAD

**Issue by DmitriiAfonin** [GetStream/stream-chat-android#572]
Hiding channel with clearing history causes app crash.

**SDK ver.** 4.2.11-beta-6
Code: `client.channel(channel.type, channel.id).hide(true)`
Debug details:

**Crashing code(SDK):**
EventHandlerImpl.kt
`is ChannelHiddenEvent -> {
                    val channelEntity = ChannelEntity(event.channel!!)`

`event.channel` is null at the moment of receiving event.

**Received event:**
`
event = {ChannelHiddenEvent@16844} "ChatEvent(type='channel.hidden')"
 channel = null
 cid = "messaging:!members-FJg6K2RrRM2l9i3ig_H8QgrSwhZOXCLPAGUStqjufcA"
 clearHistory = {Boolean@17122} false
 createdAt = {Date@17123} "Fri Jul 17 10:48:35 GMT+07:00 2020"
 member = null
 message = null
 reaction = null
 receivedAt = {Date@17124} "Fri Jul 17 10:48:36 GMT+07:00 2020"
 totalUnreadCount = null
 type = "channel.hidden"
 unreadChannels = null
 user = {User@17126} "User(id=ea7ce212-0ba2-4325-8e33-85e0453e49e9, role=user, invisible=false, banned=false, devices=[], online=true, createdAt=Wed Jul 08 09:32:03 GMT+07:00 2020, updatedAt=Fri Jul 17 10:47:57 GMT+07:00 2020, lastActive=Fri Jul 17 10:41:48 GMT+07:00 2020, totalUnreadCount=0, unreadChannels=0, unreadCount=0, mutes=[], teams=[], channelMutes=[], extraData={image=https://apphuset-cms-test.azurewebsites.net/api/assets/7be02e9c-00d1-41be-a1d2-6c6b968f8184, name=Dmitrii2})"
 shadow$_klass_ = {Class@16386} "class io.getstream.chat.android.client.events.ChannelHiddenEvent"
 shadow$_monitor_ = 0
`

**Debug log:**
`
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.apphuset.dps.dev, PID: 7245
    kotlin.KotlinNullPointerException
        at io.getstream.chat.android.livedata.EventHandlerImpl.updateOfflineStorageFromEvents$livedata_release(EventHandlerImpl.kt:107)
        at io.getstream.chat.android.livedata.EventHandlerImpl$updateOfflineStorageFromEvents$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
`

**Comment by shodgetts** [comment]
Agent comment from Séni Gueye in <a href='https://getstream.zendesk.com/agent/tickets/4494'>Zendesk ticket #4494</a>:<br><br>Hi,

Thanks for the report.
I'm passing this on to our Android team for further investigation.
We'll get back to you shortly.

Best regards,
Seni
