### ISSUE TITLE
Bug: Concurrent Modification Exception

### ISSUE THREAD

**Issue by josheroff-livly** [GetStream/stream-chat-android#59]
Steps to Reproduce:
1. Load channel list
2. Wait an arbitrary amount of time (I waited around 20 seconds)
3. Close out of app
4. Open app again

Reproducibility: ~10%

Stacktrace:
> 2019-09-23 11:05:34.074 17365-17448/com.osh.streamchatpoc E/AndroidRuntime: FATAL EXCEPTION: WSS - event handler thread
    Process: com.osh.streamchatpoc, PID: 17365
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.getstream.sdk.chat.rest.core.Client.connectionResolved(Client.java:379)
        at com.getstream.sdk.chat.rest.WebSocketService$EchoWebSocketListener.lambda$onMessage$1$WebSocketService$EchoWebSocketListener(WebSocketService.java:272)
        at com.getstream.sdk.chat.rest.-$$Lambda$WebSocketService$EchoWebSocketListener$f9N2ARRqFxybqCam0RKr38hIg2U.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at com.getstream.sdk.chat.rest.WebSocketService$EventHandlerThread.run(WebSocketService.java:323)

Version: 1.10.0

**Comment by tschellenbach** [comment]
@tbarbugli interesting bug above.

**Comment by tbarbugli** [comment]
I am unable to reproduce this; @josheroff-livly can you upgrade to latest version and try again?

**Comment by tbarbugli** [comment]
I never managed to reproduce this; @josheroff-livly please re-open if you can still manage to
