### ISSUE TITLE
ConcurrentModificationException in updateState

### ISSUE THREAD

**Issue by sanyadita** [GetStream/stream-chat-android#606]
My team've got 1k+ reports in Crashlytics with this error:
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at io.getstream.chat.android.client.socket.ChatSocketServiceImpl$updateState$3.run(ChatSocketServiceImpl.kt:193)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6977)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:910)
```
Unfortunately can't reproduce it for now. Happens on different devices and versions

**Comment by JcMinarro** [comment]
Hello @sanyadita Could you tell us which version are you using?

**Comment by sanyadita** [comment]
4.0.13

**Comment by AlexeyYalovik** [comment]
As I see ChannelViewModel was marked as depricated. I'll try to implement all staf according sample from github(https://github.com/GetStream/stream-chat-android/tree/master/sample/src/main/kotlin/io/getstream/chat/sample/feature) and let you know

**Comment by JcMinarro** [comment]
Hello,
We have done a lot of improvement and we are refactoring our old implementation.
Network Layer has been delegated to ou [API-Client](https://github.com/getstream/stream-chat-android-client)
Could you try with the [last version](https://github.com/GetStream/stream-chat-android/releases/tag/4.2.11-beta-11) we have released if it is working fine?

**Comment by AlexeyYalovik** [comment]
4.2.11-beta-11 looks good to me.

**Comment by tschellenbach** [comment]
@sanyadita did it work for you as well?
