### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property me has not been initialized

### ISSUE THREAD

**Issue by zetbrush** [GetStream/stream-chat-android#607]
`kotlin.UninitializedPropertyAccessException: lateinit property me has not been initialized
at io.getstream.chat.android.client.ChatClientImpl$1.io.getstream.chat.android.client.events.ConnectedEvent.getMe(SourceFile:15)
                                                     invoke
at io.getstream.chat.android.client.ChatClientImpl$1.invoke(SourceFile:1)
at io.getstream.chat.android.client.utils.observable.Subscription.deliver(SourceFile:9)
at io.getstream.chat.android.client.utils.observable.Subscription.onNext(SourceFile:2)
at io.getstream.chat.android.client.utils.observable.ChatObservableImpl.onNext(SourceFile:3)
at io.getstream.chat.android.client.utils.observable.ChatObservableImpl$EventsMapper.onConnected(SourceFile:2)
at -$$LambdaGroup$js$RX1rnaNIto64id03va9ghydZHnA.io.getstream.chat.android.client.socket.ChatSocketServiceImpl$updateState$3.run(java-style lambda group:6)
                                                 run
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`
library version: 4.0.13
10 out of 10 reproducible on **release** build

**Comment by tschellenbach** [comment]
I believe @JcMinarro already fixed this

**Comment by JcMinarro** [comment]
Hello @zetbrush 
Thanks for your feedback.
We have done tons of improvements on the SDK from the version you are using.
Could you check [last version](https://github.com/GetStream/stream-chat-android/releases/tag/4.2.11-beta-11) where it should be fixed?

**Comment by tschellenbach** [comment]
Hi @zetbrush, checking in here if that resolved your issue.
