### ISSUE TITLE
java.lang.IllegalStateException: no event down from INITIALIZED

### ISSUE THREAD

**Issue by AlexeyYalovik** [GetStream/stream-chat-android#616]
I faced a problem in 4.2.11-beta-11. It is reproducing on fragment attaching.
Looks like problem with androidx.fragment:fragment-ktx.

java.lang.IllegalStateException: no event down from INITIALIZED
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:281)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:62)
        at androidx.fragment.app.Fragment.performDestroyView(Fragment.java:3130)
        at androidx.fragment.app.FragmentStateManager.destroyFragmentView(FragmentStateManager.java:706)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1407)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1477)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1555)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:449)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2333)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2117)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2055)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1957)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3056)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2983)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2923)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:562)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1324)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1477)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1555)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1608)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3046)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2983)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2923)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:562)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1324)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2392)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2137)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2061)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1957)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:496)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by AlexeyYalovik** [comment]
I just added implementation "androidx.fragment:fragment-ktx:1.3.0-alpha08" to dependencies and problem was solved
