### ISSUE TITLE
a new problem cropped up. Unable to understand the error.

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#685]
When am receiving a new message. The app is crashing with this error.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.getstream.chat.android.client.models.User.getId()' on a null object reference
        at io.getstream.chat.android.livedata.EventHandlerImpl.updateOfflineStorageFromEvents$livedata_release(EventHandlerImpl.kt:95)
        at io.getstream.chat.android.livedata.EventHandlerImpl.handleEventsInternal(EventHandlerImpl.kt:412)
        at io.getstream.chat.android.livedata.EventHandlerImpl$handleEvents$1.invokeSuspend(EventHandlerImpl.kt:73)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by JcMinarro** [comment]
Hello @abhirup-patra 
Are you able to reproduce it?
Do you know which event you are receiving at this time?
Could you debug it and let us know which event is the one that is crashing your app?

**Comment by abhirup-patra** [comment]
not able to understand the error here

when i am receiving a message at that time it is crashing

**Comment by abhirup-patra** [comment]
hi @JcMinarro were you able to understand the problem here?

**Comment by abhirup-patra** [comment]
ok its fixed now.

**Comment by abhirup-patra** [comment]
sometime it works and sometimes it keeps crashing without any warning

Previously i made it work by calling the viewModel when setting user.

```
client.setUser(user, token, new InitConnectionListener(){
            @Override
            public void onError(@NotNull ChatError error) {
                super.onError(error);
//                Log.i("StreamChatError", error.getLocalizedMessage());
            }

            @Override
            public void onSuccess(@NotNull ConnectionData data) {

                user=data.getUser();
                unread_count= user.getUnreadCount();

                viewModel = new ChannelsViewModelImpl();

               // Log.i("StreamChatError", "works");
                if (from.equalsIgnoreCase("splash") || from.equalsIgnoreCase("login")){
                    Intent appLinkIntent = context.getIntent();
//                    String appLinkAction = appLinkIntent.getAction();

                    if (appLinkIntent.getData()!=null) {
                        String appLinkData = appLinkIntent.getData().toString();
                        Uri uri = Uri.parse(appLinkData);

                        String adSlugFromLink = "";
                        String slugFromLink = "";
                        if (uri.toString().contains("link")) {

                            Uri link = Uri.parse(uri.getQueryParameter("link"));
                            if (link != null) {

                                Log.i("linkData", "adSlug: " + adSlugFromLink);
                                List<String> params = link.getPathSegments();
                                Log.i("linkData", "params: " + params);
                                adSlugFromLink = params.get(params.size() - 1);
                                Log.i("linkData", "adSlug: " + adSlugFromLink);

                            }
                        } else {
                            Log.i("linkData", "getIntentData: " + uri);
                            if (uri != null) {

                                if (uri.toString().contains("ad")) {

                                    Log.i("linkData", "adSlug: " + adSlugFromLink);
                                    List<String> params = uri.getPathSegments();
                                    Log.i("linkData", "params: " + params);
                                    adSlugFromLink = params.get(params.size() - 1);
                                    Log.i("linkData", "adSlug: " + adSlugFromLink);
                                    PageRedirection.redirecToAvailableAdDetailsActivityFromDiscover(context, "discover", adSlugFromLink);
                                    context.finish();
                                } else {

                                    Log.i("linkData", "adSlug: " + slugFromLink);
                                    List<String> params = uri.getPathSegments();
                                    Log.i("linkData", "params: " + params);
                                    slugFromLink = params.get(params.size() - 1);
                                    Log.i("linkData", "adSlug: " + slugFromLink);
                                    PageRedirection.redirectToPublicProfileFromChat(context,slugFromLink,null);
                                    context.finish();
                                }

                            }
                        }
                    }
                    else
                        PageRedirection.gotoHomeActivity(context);
                }

                Log.i("countTest", "onSuccess: "+unread_count);

                if(unread_count > 0){
                    AppPreferences.getInstance().setNewPushEnable(true);
                }else {
                    AppPreferences.getInstance().setNewPushEnable(false);
                }
                Log.e("clientInitSuccess: ", String.valueOf(data));
                Log.i("StreamChat", "setUser completed"+id);
                Log.i("unread_count", String.valueOf(unread_count));
                Log.e("showNewMsgIndicator1: ", String.valueOf(AppPreferences.getInstance().getNewPushEnable()));
                super.onSuccess(data);
            }
        });
```

the error was happening when i called the view model over here

```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        // setup the client
        //configureStreamClient();
        // example for how to observe the unread counts

        //abhirup changed 6/8/20

//        configureStreamClient();



        viewModel = new ChannelsViewModelImpl();
        Chat.getInstance().getUnreadMessages().observe(getViewLifecycleOwner(), (Number count) -> {
            Log.i(TAG, String.format("Total unread message count is now %d", count));
            chat_count = (int) count;
            if ( chat_count > 0) {
                AppPreferences.getInstance().setNewPushEnable(true);
                //showNewMessageIndicatorNew
                if (myactivity != null) {
                    myactivity.runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            ((HomeActivity) getActivity()).showNewMessageIndicatorNew();
                        }
                    });
                }

            }else {
                AppPreferences.getInstance().setNewPushEnable(false);
            }
        });
        //abhirup changed 6/8/20
//        viewModel = StreamChat.viewModel;
        binding = FragmentChannelListBinding.inflate(inflater, container, false);

        // Specify the current activity as the lifecycle owner.
        binding.setLifecycleOwner(this);

        // just get all channels
        FilterObject filter = Filters.INSTANCE.eq("type", "messaging");

//        QuerySort querySort = new QuerySort().desc("last_message_at");
//        viewModel.setQuery(filter,querySort);



        if(Utils.isInternetConnected(getActivity())) {
            ChannelsViewModelBinding.bind(viewModel, binding.channelList, getViewLifecycleOwner());

        }else {
            Utils.showToastLong("No internet connection available",getActivity());
//            binding.progressBar.setVisibility(View.GONE);
//            binding.pBar.setVisibility(View.GONE);
        }

        setCustomChannelItem(getContext(), binding);
        return binding.getRoot();
    }
```

**Comment by JcMinarro** [comment]
Thanks for the update, We are investigating this error

**Comment by JcMinarro** [comment]
Hello @abhirup-patra It has been fixed.
Could you check our [last version](https://github.com/GetStream/stream-chat-android/releases/latest)?

**Comment by abhirup-patra** [comment]
yes its fixed
