### ISSUE TITLE
Crash after migrate to the latest androidx beta versions

### ISSUE THREAD

**Issue by letos** [GetStream/stream-chat-android#694]
Hi! Chat's Views crashed our app after we updated `androidx.fragment` and `androidx.activity` to the latest versions.

**Versions:**
```
implementation 'com.github.GetStream:stream-chat-android:4.3.0-beta-6'

implementation 'androidx.activity:activity-ktx:1.2.0-beta01'
implementation 'androidx.fragment:fragment-ktx:1.3.0-beta01'
```

**Error stacktrace from sample app:**
```
android.view.InflateException: Binary XML file line #43: Binary XML file line #43: Error inflating class com.getstream.sdk.chat.view.messageinput.MessageInputView
    Caused by: android.view.InflateException: Binary XML file line #43: Error inflating class com.getstream.sdk.chat.view.messageinput.MessageInputView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at androidx.fragment.app.Fragment.onCreateView(Fragment.java:1922)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2094)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
Caused by: java.lang.IllegalStateException: LifecycleOwner io.getstream.chat.sample.feature.HostActivity@812a1d2 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
        at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:116)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:653)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:662)
        at com.getstream.sdk.chat.view.messageinput.MessageInputView.<init>(MessageInputView.kt:104)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at androidx.fragment.app.Fragment.onCreateView(Fragment.java:1922) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2094) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990) 
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
```

Looks like the reason is this change from [androidx changelogs](https://developer.android.com/jetpack/androidx/releases/fragment#1.3.0-alpha08) and fact that f.e. `MessageInputView` registers listener for activity result:
> Calling registerForActivityResult() after onCreate() now throws an exception indicating that this is not allowed rather than silently failing to deliver results after a configuration change. (b/162255449)

**Steps to reproduce:**
Just update [sample app](https://github.com/GetStream/stream-chat-android/tree/master/sample) to the latest version of fragment & activity, than try to open any ChannelFragment

**Comment by zsmb13** [comment]
You've correctly identified the problem, thanks for looking into it! `1.3.0-alpha08` introduced a behaviour change here that breaks our usages. I'll attempt to work around this.

**Comment by JcMinarro** [comment]
Hello @letos 
We have updated `activity-ktx` and `fragment-ktx` dependencies to the last version and did a patch on #697 that should fix your issue.
Could you check the [last version](https://github.com/GetStream/stream-chat-android/releases/latest) and let us know if it is working fine for you?

**Comment by letos** [comment]
Yes, it's working fine now. Big thanks!
