### ISSUE TITLE
ChatClient.instance().setAnonymousUser is getting error.

### ISSUE THREAD

**Issue by harrunisk** [GetStream/stream-chat-android#729]
Hi Guys,
We have been implementing chat features for a while. Setting user by using `ChatCLient.instance().setUser` is succeed. But when we set a anonymous user by using `ChatClient.instance().setAnonymousUser`, it is getting error. Most probably back end side creating this error. Could you help me with it? The error is as the following:

```
2020-10-22 14:34:18.490 16431-16766/E/Chat:SocketService: Status code: 400, with stream code: 4, description: user_details is a required field
2020-10-22 14:34:18.491 16431-16766/ E/Chat:Events: onFailure
2020-10-22 14:34:18.491 16431-16766/ E/Chat:SocketService: Status code: -1, with stream code: 1003, description: See stack trace in logs. Intercept error in error handler of setUser
2020-10-22 14:34:19.160 16431-16431/E/Chat:ChatParser: java.lang.IllegalStateException: Cannot read raw response body of a converted body.
        at retrofit2.OkHttpCall$NoContentResponseBody.source(OkHttpCall.java:297)
        at okhttp3.Response.peekBody(Response.kt:195)
        at io.getstream.chat.android.client.parser.ChatParserImpl.toError(ChatParserImpl.kt:81)
        at io.getstream.chat.android.client.call.RetrofitCall.getResult(RetrofitCall.kt:96)
        at io.getstream.chat.android.client.call.RetrofitCall.access$getResult(RetrofitCall.kt:11)
        at io.getstream.chat.android.client.call.RetrofitCall$enqueue$2.onResponse(RetrofitCall.kt:47)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
        at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

SDK version is:` 4.3.1-beta-1`

**Comment by JcMinarro** [comment]
Hello @harrunisk 
Thanks for report it.
We need to investigate it.
We will update this issue when it is fixed

**Comment by bychkovdmitry** [comment]
Hello @harrunisk 
Thanks again for reporting it. The issue was fixed on [#737](https://github.com/GetStream/stream-chat-android/pull/737) and will be added to the next release.

**Comment by JcMinarro** [comment]
Hello @harrunisk 

It has been fixed on the last release
It should be working fine now

**Comment by harrunisk** [comment]
@JcMinarro @bychkovdmitry thank you guys for your support. We are going to update the SDK soon. I will let you know.
