### ISSUE TITLE
how to use typing indicator in a custom messageview holder?

### ISSUE THREAD

**Issue by abhirup-patra** [GetStream/stream-chat-android#843]
Right now i am using custom message view holder and while the other user types a blank space comes. How to populate that with a typing indicator?

**Comment by JcMinarro** [comment]
Hello @abhirup-patra 

First of all, you need to create your own TypingViewHolder
```
public class TypingViewHolder extends BaseMessageListItemViewHolder<MessageListItem.TypingItem> {
    
    public TypingViewHolder(@NotNull View itemView) {
        super(itemView);
    }

    @Override
    protected void bind(@NotNull MessageListItem.TypingItem messageListItem) {
        // Here you render your viewHolder
    }
}
```

Then, you need to use this `TypingViewHolder` in your factory:
```
public class MyMessageViewHolderFactory extends MessageViewHolderFactory {
        @NotNull
        @Override
        public BaseMessageListItemViewHolder<?> createMessageViewHolder(
                @NotNull ViewGroup parent,
                int viewType,
                @NotNull MessageListViewStyle style,
                @NotNull Channel channel) {
            if (viewType == MessageViewHolderFactory.MESSAGEITEM_TYPING) {
                return new TypingViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.layout_typing, parent))
            }
            return super.createMessageViewHolder(parent, viewType, style, channel);
        }
    }
```

**Comment by abhirup-patra** [comment]
@JcMinarro 

can i get an example of any sort? It would be really helpful.

**Comment by abhirup-patra** [comment]
@JcMinarro 
I am using something like this.

```
class TypingViewHolder extends BaseMessageListItemViewHolder<MessageListItem.TypingItem> {

    TextView typingTv;

    public TypingViewHolder(@NotNull View itemView) {
        super(itemView);
        typingTv = itemView.findViewById(R.id.typingTv);
    }

    @Override
    protected void bind(@NotNull MessageListItem.TypingItem typingItem) {
        typingTv.setText(typingItem.toString());
    }
}
```

and calling the viewHolder like this

```
if (viewType == MessageViewHolderFactory.MESSAGEITEM_TYPING){
                    return new TypingViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.typing_indicator, parent));
                }
```

but an error is coming up

**Comment by JcMinarro** [comment]
Which error?

**Comment by abhirup-patra** [comment]
This is shown as an error when calling the typing indicator viewholder.

`Make 'bind' return 'abentra.com.views.fragments.stream_chat.TypingViewHolder'`

**Comment by JcMinarro** [comment]
This error said you need to return a `abentra.com.views.fragments.stream_chat.TypingViewHolder` instance from your `bind()` method
Why does compiler asking you to return a instance of `abentra.com.views.fragments.stream_chat.TypingViewHolder` in your method `bind()`
Could you share your `bind()` method?

**Comment by abhirup-patra** [comment]
sure

```
@Override
    protected void bind(@NotNull MessageListItem.TypingItem typingItem) {
        typingTv.setText(typingItem.toString());
    }
```

**Comment by JcMinarro** [comment]
Hello @abhirup-patra 

On the code you are providing we don't see any error.
Could you share the code of your `abentra.com.views.fragments.stream_chat.TypingViewHolder` class and your `ViewHolderFactory` class?

**Comment by abhirup-patra** [comment]
@JcMinarro 

This is the code of the typingviewholder class

```
class TypingViewHolder extends BaseMessageListItemViewHolder<MessageListItem.TypingItem> {

    TextView typingTv;

    public TypingViewHolder(@NotNull View itemView) {
        super(itemView);
        typingTv = itemView.findViewById(R.id.typingTv);
    }

    @Override
    protected void bind(@NotNull MessageListItem.TypingItem typingItem) {
        
        typingTv.setText(typingItem.toString());
    }
}
```

and the viewholderfactory class is

```
public class CustomViewHolderFactory extends ChannelViewHolderFactory {

    CircleImageView ivUser;
    ImageView ivUserStatus;
    AppCompatTextView lastM;
    TextView userTv, channelTv, unreadTv, dateTv;
    ArrayList<ChatMember> members_data = new ArrayList<>();
    private Fragment fragment;
    private Client algoliaClient;
    private int nbPage = 0;
    Context context;


    @Override
    protected void configureHolder(BaseChannelListItemViewHolder holder, ChannelListItemAdapter adapter) {
        super.configureHolder(holder, adapter);


    }

    public CustomViewHolderFactory(Fragment fragment, Context context) {

        this.fragment = fragment;
        this.context = context;
    }



    @Override
    public BaseChannelListItemViewHolder createChannelViewHolder
            (ChannelListItemAdapter adapter, ViewGroup parent, int viewType) {

        // inflate the layout specified in the style
//        View v = LayoutInflater.from(parent.getContext()).inflate(style.channelPreviewLayout, parent, false);
        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.ad_chat_user_item_new, parent, false);

        BaseChannelListItemViewHolder holder = new BaseChannelListItemViewHolder(v) {
            @Override
            public void bind(Context context, Channel channelState, int position, @Nullable ChannelItemPayloadDiff payloads) {

                ivUser = v.findViewById(R.id.iv_users_image);
                ivUserStatus = v.findViewById(R.id.iv_user_status);
                lastM = v.findViewById(R.id.tv_last_message);
                userTv = v.findViewById(R.id.tv_chat_username);
                channelTv = v.findViewById(R.id.tv_ad_title);
                unreadTv = v.findViewById(R.id.tv_notification_count);
                dateTv = v.findViewById(R.id.lastUpdatedDate);

                int msgSize = channelState.getMessages().size()-1;

                try {

                    if (!channelState.getMessages().get(msgSize).getAttachments().isEmpty()) {
                        if (channelState.getMessages().get(msgSize).getAttachments().get(0).getType().equalsIgnoreCase("file")) {
                            lastM.setText("file");
                            lastM.setCompoundDrawablesWithIntrinsicBounds(context.getResources().getDrawable(R.drawable.ic_insert_drive_file_black_24dp),null,null,null);
                        }
                        else if (channelState.getMessages().get(msgSize).getAttachments().get(0).getType().equalsIgnoreCase("image")) {
                            lastM.setText("image");
                            lastM.setCompoundDrawablesWithIntrinsicBounds(context.getResources().getDrawable(R.drawable.ic_image_black_24dp),null,null,null);
                        }

                    }
                    else {
                        lastM.setText(channelState.getMessages().get(msgSize).getText());
                        lastM.setCompoundDrawablesWithIntrinsicBounds(null,null,null,null);

                    }
                    userTv.setText(channelState.getMembers().get(0).getUser().getId());
                    channelTv.setText(channelState.getExtraData().get("name").toString());

                    if (channelState.getUnreadCount()>0)
                        unreadTv.setVisibility(View.VISIBLE);
                    else
                        unreadTv.setVisibility(View.INVISIBLE);

                    unreadTv.setText(channelState.getUnreadCount().toString());

                    Date date = channelState.getLastMessageAt();
                    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
                    String strDate = dateFormat.format(date);
                    // System.out.println("Converted String: " + strDate);
                    getTimeFromDate(strDate);
//                dateTv.setText(channelState.getLastMessageAt().getTime());

                    if (channelState.getMembers().size()>=2) {

                        String u1 = channelState.getMembers().get(0).getUserId().substring(4);
                        String u2 = channelState.getMembers().get(1).getUserId().substring(4);

                        int userNumber = 0;

                        if (!u1.equalsIgnoreCase(String.valueOf(AppPreferences.getInstance().getLoginUserDetails().getData().getUser_details().getUser_id()))) {
                            userNumber = 0;
                        } else if (!u2.equalsIgnoreCase(String.valueOf(AppPreferences.getInstance().getLoginUserDetails().getData().getUser_details().getUser_id()))) {
                            userNumber = 1;
//                    getCategoryDataFromAlgoliaForListScreen(channelState,u2);
                        }


                        ImageLoader.DisplayImageWithPlaceHolder(context, (String) channelState.getMembers().get(userNumber).getUser().getExtraData().get("image"), R.drawable.profile, ivUser);
                        userTv.setText(String.valueOf(channelState.getMembers().get(userNumber).getUser().getExtraData().get("name")));

                        if (channelState.getMembers().get(userNumber).getUser().getOnline()) {
                            ivUserStatus.setVisibility(View.VISIBLE);
                        } else {
                            ivUserStatus.setVisibility(View.GONE);
                            //getTimeFromDate((CharSequence)channel.createdBy.getLastActive());
                        }
                    }
                }
                catch (Exception e){
                    e.printStackTrace();
//                    Utils.showToast("Some error occured, Please try again",context);
                }


                v.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        ((ChannelListFragment)fragment).openChannel(channelState);

                    }
                });

            }

            @Override
            public void setStyle(ChannelListViewStyle style) {

            }

            @Override
            public void setUserClickListener(ChannelListView.UserClickListener l) {

            }

            @Override
            public void setChannelClickListener(ChannelListView.ChannelClickListener l) {

            }

            @Override
            public void setChannelLongClickListener(ChannelListView.ChannelClickListener l) {

            }
        };
        configureHolder(holder, adapter);
        return holder;


    }

    private String getTimeFromDate(String date) {
        String res_time = "";
        String res_timeOnlyDate = "";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
        sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy h:mm a");
        DateFormat formatOnlyTime = new SimpleDateFormat("h:mm a");
        DateFormat formatOnlyDate = new SimpleDateFormat("dd-MMMM-yyyy");
        String currentDate = DateUtils.getCurrentDateInDDMMYYYY();

        if (AppPreferences.getInstance().getLoginUserDetails().getData().getUser_details().getCountry_code().equalsIgnoreCase("UA")) {
            format.setTimeZone(TimeZone.getTimeZone("Asia/Dubai"));
            formatOnlyDate.setTimeZone(TimeZone.getTimeZone("Asia/Dubai"));
            formatOnlyTime.setTimeZone(TimeZone.getTimeZone("Asia/Dubai"));
        }
        else {
            format.setTimeZone(TimeZone.getTimeZone("IST"));
            formatOnlyTime.setTimeZone(TimeZone.getTimeZone("IST"));
            formatOnlyDate.setTimeZone(TimeZone.getTimeZone("IST"));
        }
        try {
            final Date dateObj = sdf.parse(date);
            res_timeOnlyDate = formatOnlyDate.format(dateObj);
            if (res_timeOnlyDate.equalsIgnoreCase(currentDate))
                res_time = formatOnlyTime.format(dateObj);
            else
                res_time = format.format(dateObj);
            dateTv.setText(res_time);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        return res_time;
    }

}
```

please see to it

**Comment by ogkuzmin** [comment]
Hello, @abhirup-patra !
I think it's not appropriate to usage ViewHolder and ViewHolderFactory.
First of all, `BaseMessageListItemViewHolder` is a basic type for any `ViewHodler` in `MessageListView`. So you can create your own TypingViewHolder by extending `BaseMessageListItemViewHolder` (you actually did it).
Secondly, we provided the `MessageViewHolderFactory` class that creates standard versions of all possible ViewHolders. But you're free create your own `ViewHolderFactory` by extending `MessageViewHolderFactory`. There is the `createMessageViewHolder` method that has a following signature:
``` java
public BaseMessageListItemViewHolder<?> createMessageViewHolder(@NotNull ViewGroup parent, int viewType, @NotNull MessageListViewStyle style, @NotNull Channel channel)
```
It should return some `BaseMessageListItemViewHolder` depending on `viewType`. So if you want to override only TypingViewHolder your `ViewHolderFactory` should have the following type:

``` java
 public class CustomViewHolderFactory extends MessageViewHolderFactory {

    @NotNull
    @Override
    public BaseMessageListItemViewHolder<?> createMessageViewHolder(
            @NotNull ViewGroup parent, 
            int viewType, 
            @NotNull MessageListViewStyle style, 
            @NotNull Channel channel) {
        if (viewType == MessageViewHolderFactory.MESSAGEITEM_TYPING) {
            return new TypingViewHolder(LayoutInflater.from(parent.getContext())
                    .inflate(R.layout.typing_indicator, parent));
        }
        return super.createMessageViewHolder(parent, viewType, style, channel);
    }
}
```
If you want to override for example some other view holder you can add one more condition before ` return super.createMessageViewHolder(parent, viewType, style, channel);`

**Comment by abhirup-patra** [comment]
ok so i was calling the return of typingViewholder inside bind method that is why the error was coming. But now as i called it before the bind function and ran the app, it crashed giving this error.

```
Process: abentra.com, PID: 13935
    java.lang.RuntimeException: Unable to resume activity {abentra.com/abentra.com.views.activities.HomeActivity}: java.lang.IllegalStateException: ChatDomain.Builder::build() must be called before obtaining ChatDomain instance
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: ChatDomain.Builder::build() must be called before obtaining ChatDomain instance
        at io.getstream.chat.android.livedata.ChatDomain$Companion.instance(ChatDomain.kt:189)
        at com.getstream.sdk.chat.viewmodel.channels.ChannelsViewModel.<init>(ChannelsViewModel.kt:27)
        at com.getstream.sdk.chat.viewmodel.channels.ChannelsViewModel.<init>(Unknown Source:8)
        at abentra.com.views.fragments.stream_chat.ChannelListFragment.onCreateView(ChannelListFragment.java:183)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3122)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3049)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2975)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:550)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:277)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1636)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2184)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:451)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:414)
        at abentra.com.views.activities.HomeActivity.onResume(HomeActivity.java:1310)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
        at android.app.Activity.performResume(Activity.java:7939)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
D/TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler: Upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) is already scheduled. Returning...
V/FA: Connection attempt already in progress
V/FA: Recording user engagement, ms: 142
V/FA: Connection attempt already in progress

```

While this is where the error is occuring

```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        //abhirup changed 6/8/20
        viewModel = new ChannelsViewModel();
        binding = FragmentChannelListBinding.inflate(inflater, container, false);

        // Specify the current activity as the lifecycle owner.
        binding.setLifecycleOwner(this);

        // just get all channels
        FilterObject filter = Filters.INSTANCE.eq("type", "messaging");

//        QuerySort querySort = new QuerySort().desc("last_message_at");
//        viewModel.setQuery(filter,querySort);



        if(Utils.isInternetConnected(getActivity())) {
            ChannelsViewModelBinding.bind(viewModel, binding.channelList, getViewLifecycleOwner());

        }else {
            Utils.showToastLong("No internet connection available",getActivity());
//            binding.progressBar.setVisibility(View.GONE);
//            binding.pBar.setVisibility(View.GONE);
        }

        setCustomChannelItem(getContext(), binding);
        return binding.getRoot();
    }
```

this is for channellistfragment.

The chat domain is initialized in another function and it works fine until i call this typingviewHolder thing.

**Comment by ogkuzmin** [comment]
This error said that you had to initialize SDK and set your user before showing the channels list. In order to make initialization lightweight, we have provided the `ChatInitializer` class. It has the `init` method that let you initialize SDK

**Comment by abhirup-patra** [comment]
how to use that? i was using the chat domain initialization like this

 ```
public static void clientInitialization(String id, String username, String token, String image, Activity context, String from) {

        HashMap<String, Object> extraData = new HashMap<>();
        extraData.put("name", username);
        extraData.put("image", image);

        user = new User();
        user.setId(id);
        user.setExtraData(extraData);

        disconnectChatDomainIfAlreadyInitialized();



        Log.e("clientInitialization: ",extraData.toString() );
        Log.e("clientToken: ",token );

        client.setUser(user, token, new InitConnectionListener(){
            @Override
            public void onError(@NotNull ChatError error) {
                super.onError(error);
//                Log.i("StreamChatError", error.getLocalizedMessage());
            }

            @Override
            public void onSuccess(@NotNull ConnectionData data) {

                user=data.getUser();
                unread_count= user.getUnreadCount();

                if (from.equalsIgnoreCase("splash") || from.equalsIgnoreCase("login")){
                    Intent appLinkIntent = context.getIntent();
//                    String appLinkAction = appLinkIntent.getAction();

                    if (appLinkIntent.getData()!=null) {
                        String appLinkData = appLinkIntent.getData().toString();
                        Uri uri = Uri.parse(appLinkData);

                        String adSlugFromLink = "";
                        String slugFromLink = "";
                        if (uri.toString().contains("link")) {

                            Uri link = Uri.parse(uri.getQueryParameter("link"));
                            if (link != null) {

                                Log.i("linkData", "adSlug: " + adSlugFromLink);
                                List<String> params = link.getPathSegments();
                                Log.i("linkData", "params: " + params);
                                adSlugFromLink = params.get(params.size() - 1);
                                Log.i("linkData", "adSlug: " + adSlugFromLink);

                            }
                        } else {
                            Log.i("linkData", "getIntentData: " + uri);
                            if (uri != null) {

                                if (uri.toString().contains("ad")) {

                                    Log.i("linkData", "adSlug: " + adSlugFromLink);
                                    List<String> params = uri.getPathSegments();
                                    Log.i("linkData", "params: " + params);
                                    adSlugFromLink = params.get(params.size() - 1);
                                    Log.i("linkData", "adSlug: " + adSlugFromLink);
                                    PageRedirection.redirecToAvailableAdDetailsActivityFromDiscover(context, "discover", adSlugFromLink);
                                    context.finish();
                                } else {

                                    Log.i("linkData", "adSlug: " + slugFromLink);
                                    List<String> params = uri.getPathSegments();
                                    Log.i("linkData", "params: " + params);
                                    slugFromLink = params.get(params.size() - 1);
                                    Log.i("linkData", "adSlug: " + slugFromLink);
                                    PageRedirection.redirectToPublicProfileFromChat(context,slugFromLink,null);
                                    context.finish();
                                }

                            }
                        }
                    }
                    else
                        PageRedirection.gotoHomeActivity(context);
                }

                Log.i("countTest", "onSuccess: "+unread_count);

                if(unread_count > 0){
                    AppPreferences.getInstance().setNewPushEnable(true);
                }else {
                    AppPreferences.getInstance().setNewPushEnable(false);
                }
                Log.e("clientInitSuccess: ", String.valueOf(data));
                Log.i("StreamChat", "setUser completed"+id);
                Log.i("unread_count", String.valueOf(unread_count));
                Log.e("showNewMsgIndicator1: ", String.valueOf(AppPreferences.getInstance().getNewPushEnable()));
                super.onSuccess(data);
            }
        });

    }

    public static void disconnectChatDomainIfAlreadyInitialized() {
        try {
//            chatDomain = ChatDomain.instance();
            chatDomain = new ChatDomain.Builder(client,getApplicationContext()).build();
            BuildersKt.launch(GlobalScope.INSTANCE,
                    Dispatchers.getIO(),
                    CoroutineStart.DEFAULT,
                    (scope, continuation) -> chatDomain.disconnect(continuation));

//            chatDomain = new ChatDomain.Builder(getApplicationContext(), client, user).build();

        } catch(UninitializedPropertyAccessException e) {
            ChatLogger.Companion.get("ChatImpl").logD("ChatDomain was not initialized yet. No need to disconnect.");
            chatDomain = new ChatDomain.Builder(client,getApplicationContext()).build();
        }
    }
```

**Comment by ogkuzmin** [comment]
Now, you don't to do all this stuff in `disconnectChatDomainIfAlreadyInitialized()`. 
Create and store an instance of `ChatInitializer` in your God class (Application e.g. or some Static entity in your app). For the first time per invocation of  `clientInitialization` (in your Application instance for example) you have to invoke `chatInitializer.init("put here your API key")`. And  then rewrite your `clientInitialization` method.
``` java
public static void clientInitialization(String id, String username, String token, String image, Activity context, String from) {
 if (chatInitializer.isUserSet()) {
  ChatClient.instance().disconnect();
 } else {
       HashMap<String, Object> extraData = new HashMap<>();
       extraData.put("name", username);
       extraData.put("image", image);

       user = new User();
       user.setId(id);
       user.setExtraData(extraData);

     ChatClient.instance().setUser(user, token, new InitConnectionListener(){
     ...
}
```

**Comment by abhirup-patra** [comment]
@ogkuzmin 

Unable to locate ChatInitlizer class in the new build of 4.4.1

**Comment by ogkuzmin** [comment]
@abhirup-patra Sorry for misleading you. You're right `ChatInitializer` is available only in our sample app and can't be used in your own app. You can see how we use it.
Returning to your case, now you don't need to reinit `ChatDomain` and invoke `disconnect` there.
``` java
public static void clientInitialization(String id, String username, String token, String image, Activity context, String from) {
 ensureSDKinitialized();
 if (chatInitializer.isUserSet()) {
  ChatClient.instance().disconnect();
 } 
 HashMap<String, Object> extraData = new HashMap<>();
 extraData.put("name", username);
 extraData.put("image", image);

 user = new User();
 user.setId(id);
 user.setExtraData(extraData);

 ChatClient.instance().setUser(user, token, new InitConnectionListener(){
 ...
}

private static void ensureSDKinitialized() {
 if (ChatClient.Companion.isInitialized) {
     /** init ChatClient here **/
  }
 if (ChatDomain.Companion.isInitialized) {
   /** init ChatDomain here. Not need to set User **/
 }
}

```

**Comment by abhirup-patra** [comment]
@ogkuzmin 

Ok so did as you asked me.

this is how i am calling the clientInitialisation and inside it the chatInitialisation. You can see that i had to initialise the chatDomain outside the ensureSDKInitialisation as well as previously as the chatDomain is empty so it is not going inside the if statement.

```
public static void clientInitialization(String id, String username, String token, String image, Activity context, String from) {

        ensureSDKinitialized(context);

        HashMap<String, Object> extraData = new HashMap<>();
        extraData.put("name", username);
        extraData.put("image", image);

        user = new User();
        user.setId(id);
        user.setExtraData(extraData);

        chatDomain = new ChatDomain.Builder(client,getApplicationContext()).build();

//        disconnectChatDomainIfAlreadyInitialized();



        Log.e("clientInitialization: ",extraData.toString() );
        Log.e("clientToken: ",token );

        client.setUser(user, token, new InitConnectionListener(){
            @Override
            public void onError(@NotNull ChatError error) {
                super.onError(error);
//                Log.i("StreamChatError", error.getLocalizedMessage());
            }

            @Override
            public void onSuccess(@NotNull ConnectionData data) {

                user=data.getUser();
                unread_count= user.getUnreadCount();

                if (from.equalsIgnoreCase("splash") || from.equalsIgnoreCase("login")){
                    Intent appLinkIntent = context.getIntent();
//                    String appLinkAction = appLinkIntent.getAction();

                    if (appLinkIntent.getData()!=null) {
                        String appLinkData = appLinkIntent.getData().toString();
                        Uri uri = Uri.parse(appLinkData);

                        String adSlugFromLink = "";
                        String slugFromLink = "";
                        if (uri.toString().contains("link")) {

                            Uri link = Uri.parse(uri.getQueryParameter("link"));
                            if (link != null) {

                                Log.i("linkData", "adSlug: " + adSlugFromLink);
                                List<String> params = link.getPathSegments();
                                Log.i("linkData", "params: " + params);
                                adSlugFromLink = params.get(params.size() - 1);
                                Log.i("linkData", "adSlug: " + adSlugFromLink);

                            }
                        } else {
                            Log.i("linkData", "getIntentData: " + uri);
                            if (uri != null) {

                                if (uri.toString().contains("ad")) {

                                    Log.i("linkData", "adSlug: " + adSlugFromLink);
                                    List<String> params = uri.getPathSegments();
                                    Log.i("linkData", "params: " + params);
                                    adSlugFromLink = params.get(params.size() - 1);
                                    Log.i("linkData", "adSlug: " + adSlugFromLink);
                                    PageRedirection.redirecToAvailableAdDetailsActivityFromDiscover(context, "discover", adSlugFromLink);
                                    context.finish();
                                } else {

                                    Log.i("linkData", "adSlug: " + slugFromLink);
                                    List<String> params = uri.getPathSegments();
                                    Log.i("linkData", "params: " + params);
                                    slugFromLink = params.get(params.size() - 1);
                                    Log.i("linkData", "adSlug: " + slugFromLink);
                                    PageRedirection.redirectToPublicProfileFromChat(context,slugFromLink,null);
                                    context.finish();
                                }

                            }
                        }
                    }
                    else
                        PageRedirection.gotoHomeActivity(context);
                }

                Log.i("countTest", "onSuccess: "+unread_count);

                if(unread_count > 0){
                    AppPreferences.getInstance().setNewPushEnable(true);
                }else {
                    AppPreferences.getInstance().setNewPushEnable(false);
                }
                Log.e("clientInitSuccess: ", String.valueOf(data));
                Log.i("StreamChat", "setUser completed"+id);
                Log.i("unread_count", String.valueOf(unread_count));
                Log.e("showNewMsgIndicator1: ", String.valueOf(AppPreferences.getInstance().getNewPushEnable()));
                super.onSuccess(data);
            }
        });

    }

    private static void ensureSDKinitialized(Activity context) {
        if (ChatClient.Companion.isInitialized()) {
            chatClientBuilder = new ChatClient.Builder(ApiConstant.GET_STREAMT_KEY,context);
        }
        if (ChatDomain.Companion.isInitialized()) {
            chatDomain = new ChatDomain.Builder(client,getApplicationContext()).build();
        }
    }
```


This is the custom messageviewholder where i am calling the typingviewholder along with the other viewholders.

```
public BubbleMessageViewHolderFactory(Activity activity) {
        this.activity = activity;
    }


    @NotNull
    @Override
    public BaseMessageListItemViewHolder<?> createMessageViewHolder(
            @NotNull ViewGroup parent,
            int viewType,
            @NotNull MessageListViewStyle style,
            @NotNull Channel channel) {
        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.message_list_new, parent, false);

        if (viewType == MessageViewHolderFactory.MESSAGEITEM_TYPING){
            return new TypingViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.typing_indicator, parent));
        }

        BaseMessageListItemViewHolder holder = new BaseMessageListItemViewHolder(v) {

            @Override
            protected void bind(@NotNull MessageListItem messageListItem) {

                headerSpace = itemView.findViewById(R.id.space_header);
                text = itemView.findViewById(R.id.tv_text);
                tvAttachment = itemView.findViewById(R.id.tv_attachment_text);
                iv = itemView.findViewById(R.id.iv_attachment_message);
                String ownID = "user"+AppPreferences.getInstance().getLoginUserDetails().getData().getUser_details().getUser_id();

                //abhirup changed 6/8/20
                if (messageListItem instanceof MessageListItem.MessageItem){

                    handleMessageItem((MessageListItem.MessageItem) messageListItem, activity, ownID);


                }


                //abhirup changed 6/8/20
                if (messageListItem instanceof MessageListItem.DateSeparatorItem) {

//                    read1.setVisibility(View.GONE);
//                    read2.setVisibility(View.GONE);
//                    read3.setVisibility(View.GONE);
                    text.setText(DateFormat
                            .getDateTimeInstance(DateFormat.MEDIUM, DateFormat.SHORT)
                            .format(((MessageListItem.DateSeparatorItem) messageListItem).getDate()));
                }
//                else
//                    headerSpace.setVisibility(View.GONE);
//                    text.setVisibility(View.GONE);

                itemView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {

                        //abhirup changed 6/8/20
                        if (messageListItem instanceof MessageListItem.MessageItem) {
                            clickEvent((MessageListItem.MessageItem) messageListItem,activity);
                        }
                    }
                });

            }
        };

        return holder;
    }
```

But still it is crashing from the channelActivity and leading to the same error of that of the chatDomain. Please advice

**Comment by abhirup-patra** [comment]
Its done, i used a different approach to show the typing indicator and it is working flawlessly
