### ISSUE TITLE
Cannot inflate MessageInputView

### ISSUE THREAD

**Issue by daniribalbert** [GetStream/stream-chat-android#867]
**Describe the bug**
App crash when trying to inflate MessageInputView.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.imgur.mobile.debug, PID: 4282
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.imgur.mobile.debug/com.imgur.mobile.messaging.stream.ConversationActivity}: android.view.InflateException: Binary XML file line #102 in com.imgur.mobile.debug:layout/activity_conversation: Binary XML file line #102 in com.imgur.mobile.debug:layout/activity_conversation: Error inflating class com.getstream.sdk.chat.view.messageinput.MessageInputView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #102 in com.imgur.mobile.debug:layout/activity_conversation: Binary XML file line #102 in com.imgur.mobile.debug:layout/activity_conversation: Error inflating class com.getstream.sdk.chat.view.messageinput.MessageInputView
     Caused by: android.view.InflateException: Binary XML file line #102 in com.imgur.mobile.debug:layout/activity_conversation: Error inflating class com.getstream.sdk.chat.view.messageinput.MessageInputView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at androidx.databinding.DataBindingUtil.inflate(SourceFile:126)
        at androidx.databinding.ViewDataBinding.inflateInternal(SourceFile:1368)
        at com.imgur.mobile.databinding.ActivityConversationBinding.inflate(SourceFile:111)
        at com.imgur.mobile.databinding.ActivityConversationBinding.inflate(SourceFile:97)
        at com.imgur.mobile.messaging.stream.ConversationActivity.onCreate(SourceFile:81)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-11-16 16:15:01.076 4282-4282/com.imgur.mobile.debug E/AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 36 to color: type=0x5
        at android.content.res.TypedArray.getColor(TypedArray.java:532)
        at com.getstream.sdk.chat.view.messages.AvatarStyle$Builder.avatarBorderColor(SourceFile:64)
        at com.getstream.sdk.chat.view.messageinput.MessageInputStyle.<init>(SourceFile:238)
        at com.getstream.sdk.chat.view.messageinput.MessageInputView.<init>(SourceFile:54)
```

You'll probably want to take a look at this particular code, I believe this should be a color resource instead o `Color.WHITE`:
MessagInputStyle
```.avatarBorderColor(
    R.styleable.MessageListView_streamAvatarBorderColor,
    Color.WHITE
)
```

**SDK version**
- 4.4.2

**To Reproduce**
1. Add a `MessageInputView` to your activity layout.
2. Run the app and try to open the activity.
3. Notice the app crashes because it can't inflate class `MessageInputView`.

**Expected behavior**
App should not crash and MessageInputView should be inflated correctly.

**Device:**
 - Vendor and model: Pixel 2 emulator API 29
 - Android version: 10 - API 29

**Comment by JcMinarro** [comment]
Hello @daniribalbert 
It has been fixed on #868 and will be released on the next version
Thanks
