### ISSUE TITLE
When open chat with file app crashes with java.lang.NullPointerException: Missing required view with ID: com.onoff24.android:id/iv_file_thumb

### ISSUE THREAD

**Issue by Kravet** [GetStream/stream-chat-android#952]
**Describe the bug**
Hello I use Message List according to [this tutorial](https://getstream.io/tutorials/android-chat/#message-list). As soon as I open my MessageFragment for a chat which has a message with pdf file (or video) I get this crash.

And I have this crash

```
2020-12-03 18:17:24.811 16228-16228/com.onoff24.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.onoff24.android, PID: 16228
    java.lang.NullPointerException: Missing required view with ID: com.onoff24.android:id/iv_file_thumb
        at com.getstream.sdk.chat.databinding.StreamItemAttachmentFileBinding.bind(StreamItemAttachmentFileBinding.java:127)
        at com.getstream.sdk.chat.databinding.StreamItemAttachmentFileBinding.inflate(StreamItemAttachmentFileBinding.java:76)
        at com.getstream.sdk.chat.adapter.viewholder.attachment.AttachmentViewHolderFile.<init>(AttachmentViewHolderFile.kt:23)
        at com.getstream.sdk.chat.adapter.AttachmentViewHolderFactory.createAttachmentViewHolder(AttachmentViewHolderFactory.kt:64)
        at com.getstream.sdk.chat.adapter.AttachmentListItemAdapter.onCreateViewHolder(AttachmentListItemAdapter.kt:25)
        at com.getstream.sdk.chat.adapter.AttachmentListItemAdapter.onCreateViewHolder(AttachmentListItemAdapter.kt:9)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7301)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6426)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6310)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6306)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
        at android.view.View.measure(View.java:24710)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:792)
        at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:583)
        at androidx.constraintlayout.solver.widgets.analyzer.Direct.horizontalSolvingPass(Direct.java:234)
        at androidx.constraintlayout.solver.widgets.analyzer.Direct.solveHorizontalMatchConstraint(Direct.java:596)
        at androidx.constraintlayout.solver.widgets.analyzer.Direct.horizontalSolvingPass(Direct.java:286)
        at androidx.constraintlayout.solver.widgets.analyzer.Direct.solvingPass(Direct.java:118)
        at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:642)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:159)
        at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:290)
        at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:119)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1578)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1690)
        at android.view.View.measure(View.java:24710)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9687)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1657)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:643)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:22085)
        at android.view.ViewGroup.layout(ViewGroup.java:6290)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
```

My MessageFragment where I reuse get stream components
```
class MessageFragment : Fragment() {
    
    // This property is only valid between onCreateView and onDestroyView
    private var _binding: MessageFragmentBinding? = null
    private val binding get() = _binding!!

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        _binding = MessageFragmentBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

    private lateinit var viewModel: MessageViewModel
    private val chanelId: String
        get() = MessageFragmentArgs.fromBundle(requireArguments()).channelId

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        viewModel = ViewModelProvider(this).get(MessageViewModel::class.java)

        // Step 1 - Create 3 separate ViewModels for the views so it's easy to customize one of the components
        val factory = ChannelViewModelFactory(chanelId)
        val channelHeaderViewModel: ChannelHeaderViewModel by viewModels { factory }
        val messageListViewModel: MessageListViewModel by viewModels { factory }
        val messageInputViewModel: MessageInputViewModel by viewModels { factory }

        // Step 2 - Bind the view and ViewModels, they are loosely coupled so it's easy to customize
        channelHeaderViewModel.bindView(binding.channelHeaderView, this)
        messageListViewModel.bindView(binding.messageListView, this)
        messageInputViewModel.bindView(binding.messageInputView, this)

        // Step 3 - Let the message input know when we open a thread
        messageListViewModel.mode.observe(viewLifecycleOwner) { mode ->
            when (mode) {
                is MessageListViewModel.Mode.Thread -> messageInputViewModel.setActiveThread(mode.parentMessage)
                is MessageListViewModel.Mode.Normal -> messageInputViewModel.resetThread()
            }
        }

        // Step 4 - Let the message input know when we are editing a message
        binding.messageListView.setOnMessageEditHandler {
            messageInputViewModel.editMessage.postValue(it)
        }

        // Step 5 - Handle navigate up state
        messageListViewModel.state.observe(viewLifecycleOwner) { state ->
            if (state is MessageListViewModel.State.NavigateUp) {
                Navigation.findNavController(requireView())
                        .runCatching { popBackStack() }
            }
        }

        // Step 6 - Handle back button behaviour correctly when you're in a thread
        binding.channelHeaderView.onBackClick = {
            messageListViewModel.onEvent(MessageListViewModel.Event.BackButtonPressed)
        }
    }

}
```

**SDK version**
"com.github.getstream:stream-chat-android:4.4.5"

**To Reproduce**
1. Open MessageFragment
2. Open the chat which has downloaded pdf file or video.
3. Crash.

**Expected behavior**
I can open chats with pdf and videos without crash.

**Device:**
 - Vendor and model: OnePlus 5t (android 10), Samsung Galaxy S3.

**Comment by zsmb13** [comment]
Thanks for reporting the issue! We found the cause, and we're working on a solution.

**Comment by zsmb13** [comment]
In the meantime, you should be able to fix this for your own project by including the Stream Chat library from MavenCentral instead of from Jitpack.

This would mean having MavenCentral listed in your repositories:

```gradle
repositories {
    mavenCentral()
    ...
}
```

And then using the new dependency name for Chat:

```gradle
dependencies {
    implementation "io.getstream:stream-chat-android:4.4.5"
    ...
}
```

**Comment by Kravet** [comment]
Thanks for quick response.
Btw, the temp solution you mentioned above helped.

**Comment by zsmb13** [comment]
Awesome! I'll leave this open for visibility until we merge the more permanent fix.

**Comment by JcMinarro** [comment]
Hello @Kravet 

We recently migrated our lib to Maven Central, so the dependency you need to use is the one that Márton recommended you.
BTW, a new version of the SDK has been released that fixes other bugs, would be great if you update to this version
```
dependencies {
    implementation "io.getstream:stream-chat-android:4.4.6"
    ...
}
```

**Comment by Kravet** [comment]
Checked! it works well on 4.4.6
